/* tslint:disable */
/* eslint-disable */
/**
 * CRADLE
 * Threat Intelligence Knowledge Management
 *
 * The version of the OpenAPI document: 2.10.2-beta.9bd46310 (2.10.2-beta.9bd46310)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AccessEntityList404Response,
  FileDownload,
  FileProcessRequest,
  FileUploadFinalizeRequest,
  FileUploadFinalizeResponse,
  FileUploadResponse,
} from '../models/index';
import {
    AccessEntityList404ResponseFromJSON,
    AccessEntityList404ResponseToJSON,
    FileDownloadFromJSON,
    FileDownloadToJSON,
    FileProcessRequestFromJSON,
    FileProcessRequestToJSON,
    FileUploadFinalizeRequestFromJSON,
    FileUploadFinalizeRequestToJSON,
    FileUploadFinalizeResponseFromJSON,
    FileUploadFinalizeResponseToJSON,
    FileUploadResponseFromJSON,
    FileUploadResponseToJSON,
} from '../models/index';

export interface FileTransferDeleteDestroyRequest {
    fileId: string;
}

export interface FileTransferDownloadRetrieveRequest {
    fileId: string;
}

export interface FileTransferProcessCreateRequest {
    fileProcessRequest: FileProcessRequest;
}

export interface FileTransferUploadFinalizeCreateRequest {
    uploadId: string;
    fileUploadFinalizeRequest?: FileUploadFinalizeRequest;
}

export interface FileTransferUploadRetrieveRequest {
    fileName: string;
}

/**
 * 
 */
export class FileTransferApi extends runtime.BaseAPI {

    /**
     * Deletes a file reference and removes the associated file from storage.
     * Delete a file reference
     */
    async fileTransferDeleteDestroyRaw(requestParameters: FileTransferDeleteDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['fileId'] == null) {
            throw new runtime.RequiredError(
                'fileId',
                'Required parameter "fileId" was null or undefined when calling fileTransferDeleteDestroy().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['fileId'] != null) {
            queryParameters['fileId'] = requestParameters['fileId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/file-transfer/delete/`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Deletes a file reference and removes the associated file from storage.
     * Delete a file reference
     */
    async fileTransferDeleteDestroy(requestParameters: FileTransferDeleteDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.fileTransferDeleteDestroyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Generates a presigned URL for downloading a file.
     * Get file download URL
     */
    async fileTransferDownloadRetrieveRaw(requestParameters: FileTransferDownloadRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileDownload>> {
        if (requestParameters['fileId'] == null) {
            throw new runtime.RequiredError(
                'fileId',
                'Required parameter "fileId" was null or undefined when calling fileTransferDownloadRetrieve().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['fileId'] != null) {
            queryParameters['fileId'] = requestParameters['fileId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/file-transfer/download/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FileDownloadFromJSON(jsonValue));
    }

    /**
     * Generates a presigned URL for downloading a file.
     * Get file download URL
     */
    async fileTransferDownloadRetrieve(requestParameters: FileTransferDownloadRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileDownload> {
        const response = await this.fileTransferDownloadRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Triggers processing for a file (calculates hashes, mimetype, etc.).
     * Process an uploaded file
     */
    async fileTransferProcessCreateRaw(requestParameters: FileTransferProcessCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['fileProcessRequest'] == null) {
            throw new runtime.RequiredError(
                'fileProcessRequest',
                'Required parameter "fileProcessRequest" was null or undefined when calling fileTransferProcessCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/file-transfer/process/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FileProcessRequestToJSON(requestParameters['fileProcessRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Triggers processing for a file (calculates hashes, mimetype, etc.).
     * Process an uploaded file
     */
    async fileTransferProcessCreate(requestParameters: FileTransferProcessCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.fileTransferProcessCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Verifies the file was uploaded to storage and creates a FileReference. Optionally connects the file to a note.
     * Finalize file upload
     */
    async fileTransferUploadFinalizeCreateRaw(requestParameters: FileTransferUploadFinalizeCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileUploadFinalizeResponse>> {
        if (requestParameters['uploadId'] == null) {
            throw new runtime.RequiredError(
                'uploadId',
                'Required parameter "uploadId" was null or undefined when calling fileTransferUploadFinalizeCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/file-transfer/upload/{upload_id}/finalize/`;
        urlPath = urlPath.replace(`{${"upload_id"}}`, encodeURIComponent(String(requestParameters['uploadId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FileUploadFinalizeRequestToJSON(requestParameters['fileUploadFinalizeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FileUploadFinalizeResponseFromJSON(jsonValue));
    }

    /**
     * Verifies the file was uploaded to storage and creates a FileReference. Optionally connects the file to a note.
     * Finalize file upload
     */
    async fileTransferUploadFinalizeCreate(requestParameters: FileTransferUploadFinalizeCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileUploadFinalizeResponse> {
        const response = await this.fileTransferUploadFinalizeCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Generates a presigned URL for uploading a file. Returns upload_id, presigned_url, object_key, and expires_in. The upload must be finalized within the expiration time.
     * Initiate file upload
     */
    async fileTransferUploadRetrieveRaw(requestParameters: FileTransferUploadRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileUploadResponse>> {
        if (requestParameters['fileName'] == null) {
            throw new runtime.RequiredError(
                'fileName',
                'Required parameter "fileName" was null or undefined when calling fileTransferUploadRetrieve().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['fileName'] != null) {
            queryParameters['fileName'] = requestParameters['fileName'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/file-transfer/upload/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FileUploadResponseFromJSON(jsonValue));
    }

    /**
     * Generates a presigned URL for uploading a file. Returns upload_id, presigned_url, object_key, and expires_in. The upload must be finalized within the expiration time.
     * Initiate file upload
     */
    async fileTransferUploadRetrieve(requestParameters: FileTransferUploadRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileUploadResponse> {
        const response = await this.fileTransferUploadRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
