/* tslint:disable */
/* eslint-disable */
/**
 * CRADLE
 * Threat Intelligence Knowledge Management
 *
 * The version of the OpenAPI document: 2.10.2-beta.9bd46310 (2.10.2-beta.9bd46310)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AccessEntityList404Response,
  BaseDigest,
  DigestSubclass,
  EnrichmentRequest,
  EnrichmentRequestDetail,
  EnrichmentRequestRequest,
  EnrichmentSettings,
  EnrichmentSettingsRequest,
  EnrichmentSubclass,
  MappingSubclass,
  PaginatedBaseDigestSerializerResponse,
  PaginatedEnrichmentRelationSerializerResponse,
  PaginatedEnrichmentRequestListSerializerResponse,
} from '../models/index';
import {
    AccessEntityList404ResponseFromJSON,
    AccessEntityList404ResponseToJSON,
    BaseDigestFromJSON,
    BaseDigestToJSON,
    DigestSubclassFromJSON,
    DigestSubclassToJSON,
    EnrichmentRequestFromJSON,
    EnrichmentRequestToJSON,
    EnrichmentRequestDetailFromJSON,
    EnrichmentRequestDetailToJSON,
    EnrichmentRequestRequestFromJSON,
    EnrichmentRequestRequestToJSON,
    EnrichmentSettingsFromJSON,
    EnrichmentSettingsToJSON,
    EnrichmentSettingsRequestFromJSON,
    EnrichmentSettingsRequestToJSON,
    EnrichmentSubclassFromJSON,
    EnrichmentSubclassToJSON,
    MappingSubclassFromJSON,
    MappingSubclassToJSON,
    PaginatedBaseDigestSerializerResponseFromJSON,
    PaginatedBaseDigestSerializerResponseToJSON,
    PaginatedEnrichmentRelationSerializerResponseFromJSON,
    PaginatedEnrichmentRelationSerializerResponseToJSON,
    PaginatedEnrichmentRequestListSerializerResponseFromJSON,
    PaginatedEnrichmentRequestListSerializerResponseToJSON,
} from '../models/index';

export interface EnrichmentDetailDeleteRequest {
    id: number;
}

export interface EnrichmentDetailRetrieveRequest {
    id: number;
}

export interface EnrichmentRelationsRetrieveRequest {
    enricherType: string;
    id: number;
    details?: string;
    page?: number;
    pageSize?: number;
    query?: string;
}

export interface EnrichmentRequestCreateRequest {
    enrichmentRequestRequest: EnrichmentRequestRequest;
}

export interface EnrichmentRequestListRequest {
    orderBy?: string;
    page?: number;
    pageSize?: number;
    status?: EnrichmentRequestListStatusEnum;
    title?: string;
    userUsername?: string;
}

export interface EnrichmentRestartRequest {
    id: number;
}

export interface EnrichmentSettingsRetrieveRequest {
    enricherType: string;
}

export interface EnrichmentSettingsUpdateRequest {
    enricherType: string;
    enrichmentSettingsRequest?: EnrichmentSettingsRequest;
}

export interface IntelioDigestCreateRequest {
    title: string;
    digestType: string;
    file: Blob;
    entity?: number;
}

export interface IntelioDigestDestroyRequest {
    id?: string;
}

export interface IntelioDigestRetrieveRequest {
    author?: string;
    createdAtGte?: string;
    createdAtLte?: string;
    createdDate?: string;
    orderBy?: string;
    page?: number;
    pageSize?: number;
    status?: IntelioDigestRetrieveStatusEnum;
    title?: string;
}

export interface MappingsKeysSchemaRequest {
    className: string;
}

export interface MappingsSchemaCreateOrUpdateRequest {
    className: string;
    requestBody?: { [key: string]: any; };
}

export interface MappingsSchemaDestroyRequest {
    className: string;
    mappingId?: string;
}

export interface MappingsSchemaListRequest {
    className: string;
}

/**
 * 
 */
export class IntelioApi extends runtime.BaseAPI {

    /**
     * Delete a specific enrichment request. Only the owner or staff can delete an enrichment request.
     * Delete enrichment request
     */
    async enrichmentDetailDeleteRaw(requestParameters: EnrichmentDetailDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling enrichmentDetailDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/intelio/enrich/{id}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a specific enrichment request. Only the owner or staff can delete an enrichment request.
     * Delete enrichment request
     */
    async enrichmentDetailDelete(requestParameters: EnrichmentDetailDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.enrichmentDetailDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Retrieve detailed information about a specific enrichment request including enricher types, entries requested, warnings, and errors.
     * Retrieve enrichment request details
     */
    async enrichmentDetailRetrieveRaw(requestParameters: EnrichmentDetailRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnrichmentRequestDetail>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling enrichmentDetailRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/intelio/enrich/{id}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnrichmentRequestDetailFromJSON(jsonValue));
    }

    /**
     * Retrieve detailed information about a specific enrichment request including enricher types, entries requested, warnings, and errors.
     * Retrieve enrichment request details
     */
    async enrichmentDetailRetrieve(requestParameters: EnrichmentDetailRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnrichmentRequestDetail> {
        const response = await this.enrichmentDetailRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve the relations created by a specific enrichment request, filtered by enricher type.
     * Retrieve relations created by enrichment
     */
    async enrichmentRelationsRetrieveRaw(requestParameters: EnrichmentRelationsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedEnrichmentRelationSerializerResponse>> {
        if (requestParameters['enricherType'] == null) {
            throw new runtime.RequiredError(
                'enricherType',
                'Required parameter "enricherType" was null or undefined when calling enrichmentRelationsRetrieve().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling enrichmentRelationsRetrieve().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['details'] != null) {
            queryParameters['details'] = requestParameters['details'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/intelio/enrich/{id}/{enricher_type}/`;
        urlPath = urlPath.replace(`{${"enricher_type"}}`, encodeURIComponent(String(requestParameters['enricherType'])));
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedEnrichmentRelationSerializerResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve the relations created by a specific enrichment request, filtered by enricher type.
     * Retrieve relations created by enrichment
     */
    async enrichmentRelationsRetrieve(requestParameters: EnrichmentRelationsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedEnrichmentRelationSerializerResponse> {
        const response = await this.enrichmentRelationsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new enrichment request for an entity. Required fields: enricher_name, entity, title, and request.
     * Create enrichment request
     */
    async enrichmentRequestCreateRaw(requestParameters: EnrichmentRequestCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnrichmentRequest>> {
        if (requestParameters['enrichmentRequestRequest'] == null) {
            throw new runtime.RequiredError(
                'enrichmentRequestRequest',
                'Required parameter "enrichmentRequestRequest" was null or undefined when calling enrichmentRequestCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/intelio/enrich/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EnrichmentRequestRequestToJSON(requestParameters['enrichmentRequestRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnrichmentRequestFromJSON(jsonValue));
    }

    /**
     * Create a new enrichment request for an entity. Required fields: enricher_name, entity, title, and request.
     * Create enrichment request
     */
    async enrichmentRequestCreate(requestParameters: EnrichmentRequestCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnrichmentRequest> {
        const response = await this.enrichmentRequestCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a paginated list of enrichment requests for the current user. Can filter by user and title. Results are ordered by created_at descending.
     * List enrichment requests
     */
    async enrichmentRequestListRaw(requestParameters: EnrichmentRequestListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedEnrichmentRequestListSerializerResponse>> {
        const queryParameters: any = {};

        if (requestParameters['orderBy'] != null) {
            queryParameters['order_by'] = requestParameters['orderBy'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['title'] != null) {
            queryParameters['title'] = requestParameters['title'];
        }

        if (requestParameters['userUsername'] != null) {
            queryParameters['user__username'] = requestParameters['userUsername'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/intelio/enrich/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedEnrichmentRequestListSerializerResponseFromJSON(jsonValue));
    }

    /**
     * Returns a paginated list of enrichment requests for the current user. Can filter by user and title. Results are ordered by created_at descending.
     * List enrichment requests
     */
    async enrichmentRequestList(requestParameters: EnrichmentRequestListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedEnrichmentRequestListSerializerResponse> {
        const response = await this.enrichmentRequestListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Restart a specific enrichment request by resetting its status and rerunning the enrichment process. Only the owner or staff can restart an enrichment request.
     * Restart enrichment request
     */
    async enrichmentRestartRaw(requestParameters: EnrichmentRestartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnrichmentRequestDetail>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling enrichmentRestart().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/intelio/enrich/{id}/restart/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnrichmentRequestDetailFromJSON(jsonValue));
    }

    /**
     * Restart a specific enrichment request by resetting its status and rerunning the enrichment process. Only the owner or staff can restart an enrichment request.
     * Restart enrichment request
     */
    async enrichmentRestart(requestParameters: EnrichmentRestartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnrichmentRequestDetail> {
        const response = await this.enrichmentRestartRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get enrichment settings for a specific enricher type.
     * Get enrichment settings
     */
    async enrichmentSettingsRetrieveRaw(requestParameters: EnrichmentSettingsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnrichmentSettings>> {
        if (requestParameters['enricherType'] == null) {
            throw new runtime.RequiredError(
                'enricherType',
                'Required parameter "enricherType" was null or undefined when calling enrichmentSettingsRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/intelio/enrichment/{enricher_type}/`;
        urlPath = urlPath.replace(`{${"enricher_type"}}`, encodeURIComponent(String(requestParameters['enricherType'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnrichmentSettingsFromJSON(jsonValue));
    }

    /**
     * Get enrichment settings for a specific enricher type.
     * Get enrichment settings
     */
    async enrichmentSettingsRetrieve(requestParameters: EnrichmentSettingsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnrichmentSettings> {
        const response = await this.enrichmentSettingsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create or update enrichment settings for a specific enricher type.
     * Update enrichment settings
     */
    async enrichmentSettingsUpdateRaw(requestParameters: EnrichmentSettingsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnrichmentSettings>> {
        if (requestParameters['enricherType'] == null) {
            throw new runtime.RequiredError(
                'enricherType',
                'Required parameter "enricherType" was null or undefined when calling enrichmentSettingsUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/intelio/enrichment/{enricher_type}/`;
        urlPath = urlPath.replace(`{${"enricher_type"}}`, encodeURIComponent(String(requestParameters['enricherType'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EnrichmentSettingsRequestToJSON(requestParameters['enrichmentSettingsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnrichmentSettingsFromJSON(jsonValue));
    }

    /**
     * Create or update enrichment settings for a specific enricher type.
     * Update enrichment settings
     */
    async enrichmentSettingsUpdate(requestParameters: EnrichmentSettingsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnrichmentSettings> {
        const response = await this.enrichmentSettingsUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a list of all subclasses of BaseEnricher with their names.
     * Get enrichment subclasses
     */
    async enrichmentSubclassesListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<EnrichmentSubclass>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/intelio/enrichment/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EnrichmentSubclassFromJSON));
    }

    /**
     * Returns a list of all subclasses of BaseEnricher with their names.
     * Get enrichment subclasses
     */
    async enrichmentSubclassesList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<EnrichmentSubclass>> {
        const response = await this.enrichmentSubclassesListRaw(initOverrides);
        return await response.value();
    }

    /**
     * Create a new digest for the current user with file upload.
     * Create digest
     */
    async intelioDigestCreateRaw(requestParameters: IntelioDigestCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseDigest>> {
        if (requestParameters['title'] == null) {
            throw new runtime.RequiredError(
                'title',
                'Required parameter "title" was null or undefined when calling intelioDigestCreate().'
            );
        }

        if (requestParameters['digestType'] == null) {
            throw new runtime.RequiredError(
                'digestType',
                'Required parameter "digestType" was null or undefined when calling intelioDigestCreate().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling intelioDigestCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Api-Key"] = await this.configuration.apiKey("Api-Key"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['title'] != null) {
            formParams.append('title', requestParameters['title'] as any);
        }

        if (requestParameters['digestType'] != null) {
            formParams.append('digest_type', requestParameters['digestType'] as any);
        }

        if (requestParameters['entity'] != null) {
            formParams.append('entity', requestParameters['entity'] as any);
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/intelio/digest/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseDigestFromJSON(jsonValue));
    }

    /**
     * Create a new digest for the current user with file upload.
     * Create digest
     */
    async intelioDigestCreate(requestParameters: IntelioDigestCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseDigest> {
        const response = await this.intelioDigestCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a specific digest by ID.
     * Delete digest
     */
    async intelioDigestDestroyRaw(requestParameters: IntelioDigestDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Api-Key"] = await this.configuration.apiKey("Api-Key"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/intelio/digest/`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete a specific digest by ID.
     * Delete digest
     */
    async intelioDigestDestroy(requestParameters: IntelioDigestDestroyRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.intelioDigestDestroyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a list of all subclasses of BaseDigest with their names.
     * Get digest subclasses
     */
    async intelioDigestOptionsListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DigestSubclass>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Api-Key"] = await this.configuration.apiKey("Api-Key"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/intelio/digest/options/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DigestSubclassFromJSON));
    }

    /**
     * Returns a list of all subclasses of BaseDigest with their names.
     * Get digest subclasses
     */
    async intelioDigestOptionsList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DigestSubclass>> {
        const response = await this.intelioDigestOptionsListRaw(initOverrides);
        return await response.value();
    }

    /**
     * Create and retrieve digests for the current user.
     * Manage digests
     */
    async intelioDigestRetrieveRaw(requestParameters: IntelioDigestRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedBaseDigestSerializerResponse>> {
        const queryParameters: any = {};

        if (requestParameters['author'] != null) {
            queryParameters['author'] = requestParameters['author'];
        }

        if (requestParameters['createdAtGte'] != null) {
            queryParameters['created_at_gte'] = requestParameters['createdAtGte'];
        }

        if (requestParameters['createdAtLte'] != null) {
            queryParameters['created_at_lte'] = requestParameters['createdAtLte'];
        }

        if (requestParameters['createdDate'] != null) {
            queryParameters['created_date'] = requestParameters['createdDate'];
        }

        if (requestParameters['orderBy'] != null) {
            queryParameters['order_by'] = requestParameters['orderBy'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['title'] != null) {
            queryParameters['title'] = requestParameters['title'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Api-Key"] = await this.configuration.apiKey("Api-Key"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/intelio/digest/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedBaseDigestSerializerResponseFromJSON(jsonValue));
    }

    /**
     * Create and retrieve digests for the current user.
     * Manage digests
     */
    async intelioDigestRetrieve(requestParameters: IntelioDigestRetrieveRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedBaseDigestSerializerResponse> {
        const response = await this.intelioDigestRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Given a class name, return the possible field mappings.
     * Get mapping keys schema
     */
    async mappingsKeysSchemaRaw(requestParameters: MappingsKeysSchemaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['className'] == null) {
            throw new runtime.RequiredError(
                'className',
                'Required parameter "className" was null or undefined when calling mappingsKeysSchema().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Api-Key"] = await this.configuration.apiKey("Api-Key"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/intelio/mappings/{class_name}/keys`;
        urlPath = urlPath.replace(`{${"class_name"}}`, encodeURIComponent(String(requestParameters['className'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Given a class name, return the possible field mappings.
     * Get mapping keys schema
     */
    async mappingsKeysSchema(requestParameters: MappingsKeysSchemaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.mappingsKeysSchemaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new mapping or update an existing one for a given class.
     * Create or update mapping
     */
    async mappingsSchemaCreateOrUpdateRaw(requestParameters: MappingsSchemaCreateOrUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['className'] == null) {
            throw new runtime.RequiredError(
                'className',
                'Required parameter "className" was null or undefined when calling mappingsSchemaCreateOrUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Api-Key"] = await this.configuration.apiKey("Api-Key"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/intelio/mappings/{class_name}/`;
        urlPath = urlPath.replace(`{${"class_name"}}`, encodeURIComponent(String(requestParameters['className'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Create a new mapping or update an existing one for a given class.
     * Create or update mapping
     */
    async mappingsSchemaCreateOrUpdate(requestParameters: MappingsSchemaCreateOrUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.mappingsSchemaCreateOrUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a mapping instance for a given class.
     * Delete mapping
     */
    async mappingsSchemaDestroyRaw(requestParameters: MappingsSchemaDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['className'] == null) {
            throw new runtime.RequiredError(
                'className',
                'Required parameter "className" was null or undefined when calling mappingsSchemaDestroy().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['mappingId'] != null) {
            queryParameters['mapping_id'] = requestParameters['mappingId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Api-Key"] = await this.configuration.apiKey("Api-Key"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/intelio/mappings/{class_name}/`;
        urlPath = urlPath.replace(`{${"class_name"}}`, encodeURIComponent(String(requestParameters['className'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete a mapping instance for a given class.
     * Delete mapping
     */
    async mappingsSchemaDestroy(requestParameters: MappingsSchemaDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.mappingsSchemaDestroyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all mapping instances for a given class.
     * Get mapping instances
     */
    async mappingsSchemaListRaw(requestParameters: MappingsSchemaListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<object>>> {
        if (requestParameters['className'] == null) {
            throw new runtime.RequiredError(
                'className',
                'Required parameter "className" was null or undefined when calling mappingsSchemaList().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Api-Key"] = await this.configuration.apiKey("Api-Key"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/intelio/mappings/{class_name}/`;
        urlPath = urlPath.replace(`{${"class_name"}}`, encodeURIComponent(String(requestParameters['className'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get all mapping instances for a given class.
     * Get mapping instances
     */
    async mappingsSchemaList(requestParameters: MappingsSchemaListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<object>> {
        const response = await this.mappingsSchemaListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a list of all subclasses of ClassMapping with their names.
     * Get class mapping subclasses
     */
    async mappingsSubclassesListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MappingSubclass>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/intelio/mappings/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MappingSubclassFromJSON));
    }

    /**
     * Returns a list of all subclasses of ClassMapping with their names.
     * Get class mapping subclasses
     */
    async mappingsSubclassesList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MappingSubclass>> {
        const response = await this.mappingsSubclassesListRaw(initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const EnrichmentRequestListStatusEnum = {
    Done: 'done',
    Error: 'error',
    Waiting: 'waiting',
    Warning: 'warning',
    Working: 'working'
} as const;
export type EnrichmentRequestListStatusEnum = typeof EnrichmentRequestListStatusEnum[keyof typeof EnrichmentRequestListStatusEnum];
/**
 * @export
 */
export const IntelioDigestRetrieveStatusEnum = {
    Done: 'done',
    Error: 'error',
    Working: 'working'
} as const;
export type IntelioDigestRetrieveStatusEnum = typeof IntelioDigestRetrieveStatusEnum[keyof typeof IntelioDigestRetrieveStatusEnum];
