/* tslint:disable */
/* eslint-disable */
/**
 * CRADLE
 * Threat Intelligence Knowledge Management
 *
 * The version of the OpenAPI document: 2.10.2-beta.9bd46310 (2.10.2-beta.9bd46310)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GraphInaccessibleResponse,
  LazyPaginatedEntryWithDepthSerializerViewResponse,
  LazyPaginatedSubGraphSerializerResponse,
  PathfindQueryRequest,
  SubGraph,
} from '../models/index';
import {
    GraphInaccessibleResponseFromJSON,
    GraphInaccessibleResponseToJSON,
    LazyPaginatedEntryWithDepthSerializerViewResponseFromJSON,
    LazyPaginatedEntryWithDepthSerializerViewResponseToJSON,
    LazyPaginatedSubGraphSerializerResponseFromJSON,
    LazyPaginatedSubGraphSerializerResponseToJSON,
    PathfindQueryRequestFromJSON,
    PathfindQueryRequestToJSON,
    SubGraphFromJSON,
    SubGraphToJSON,
} from '../models/index';

export interface KnowledgeGraphFetchRetrieveRequest {
    endDate: Date;
    src: number;
    startDate: Date;
    depth?: number;
    pageSize?: number;
}

export interface KnowledgeGraphInaccessibleRetrieveRequest {
    src: string;
    depth?: number;
}

export interface KnowledgeGraphNeighborsRetrieveRequest {
    src: string;
    depth?: number;
    page?: number;
    pageSize?: number;
    query?: string;
    wildcard?: boolean;
}

export interface KnowledgeGraphPathfindCreateRequest {
    pathfindQueryRequest: PathfindQueryRequest;
}

/**
 * 
 */
export class KnowledgeGraphApi extends runtime.BaseAPI {

    /**
     * Fetch graph data with entries and edges for visualization.
     * Fetch knowledge graph data
     */
    async knowledgeGraphFetchRetrieveRaw(requestParameters: KnowledgeGraphFetchRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LazyPaginatedSubGraphSerializerResponse>> {
        if (requestParameters['endDate'] == null) {
            throw new runtime.RequiredError(
                'endDate',
                'Required parameter "endDate" was null or undefined when calling knowledgeGraphFetchRetrieve().'
            );
        }

        if (requestParameters['src'] == null) {
            throw new runtime.RequiredError(
                'src',
                'Required parameter "src" was null or undefined when calling knowledgeGraphFetchRetrieve().'
            );
        }

        if (requestParameters['startDate'] == null) {
            throw new runtime.RequiredError(
                'startDate',
                'Required parameter "startDate" was null or undefined when calling knowledgeGraphFetchRetrieve().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['depth'] != null) {
            queryParameters['depth'] = requestParameters['depth'];
        }

        if (requestParameters['endDate'] != null) {
            queryParameters['end_date'] = (requestParameters['endDate'] as any).toISOString();
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['src'] != null) {
            queryParameters['src'] = requestParameters['src'];
        }

        if (requestParameters['startDate'] != null) {
            queryParameters['start_date'] = (requestParameters['startDate'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/knowledge-graph/fetch/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LazyPaginatedSubGraphSerializerResponseFromJSON(jsonValue));
    }

    /**
     * Fetch graph data with entries and edges for visualization.
     * Fetch knowledge graph data
     */
    async knowledgeGraphFetchRetrieve(requestParameters: KnowledgeGraphFetchRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LazyPaginatedSubGraphSerializerResponse> {
        const response = await this.knowledgeGraphFetchRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get entries in the knowledge graph that are inaccessible to the current user.
     * Get inaccessible graph entries
     */
    async knowledgeGraphInaccessibleRetrieveRaw(requestParameters: KnowledgeGraphInaccessibleRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GraphInaccessibleResponse>> {
        if (requestParameters['src'] == null) {
            throw new runtime.RequiredError(
                'src',
                'Required parameter "src" was null or undefined when calling knowledgeGraphInaccessibleRetrieve().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['depth'] != null) {
            queryParameters['depth'] = requestParameters['depth'];
        }

        if (requestParameters['src'] != null) {
            queryParameters['src'] = requestParameters['src'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/knowledge-graph/inaccessible/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GraphInaccessibleResponseFromJSON(jsonValue));
    }

    /**
     * Get entries in the knowledge graph that are inaccessible to the current user.
     * Get inaccessible graph entries
     */
    async knowledgeGraphInaccessibleRetrieve(requestParameters: KnowledgeGraphInaccessibleRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GraphInaccessibleResponse> {
        const response = await this.knowledgeGraphInaccessibleRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get neighboring entries in the knowledge graph for a given source entry.
     * Get graph neighbors
     */
    async knowledgeGraphNeighborsRetrieveRaw(requestParameters: KnowledgeGraphNeighborsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LazyPaginatedEntryWithDepthSerializerViewResponse>> {
        if (requestParameters['src'] == null) {
            throw new runtime.RequiredError(
                'src',
                'Required parameter "src" was null or undefined when calling knowledgeGraphNeighborsRetrieve().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['depth'] != null) {
            queryParameters['depth'] = requestParameters['depth'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        if (requestParameters['src'] != null) {
            queryParameters['src'] = requestParameters['src'];
        }

        if (requestParameters['wildcard'] != null) {
            queryParameters['wildcard'] = requestParameters['wildcard'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/knowledge-graph/neighbors/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LazyPaginatedEntryWithDepthSerializerViewResponseFromJSON(jsonValue));
    }

    /**
     * Get neighboring entries in the knowledge graph for a given source entry.
     * Get graph neighbors
     */
    async knowledgeGraphNeighborsRetrieve(requestParameters: KnowledgeGraphNeighborsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LazyPaginatedEntryWithDepthSerializerViewResponse> {
        const response = await this.knowledgeGraphNeighborsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Find paths between source and destination entries in the knowledge graph.
     * Find paths in knowledge graph
     */
    async knowledgeGraphPathfindCreateRaw(requestParameters: KnowledgeGraphPathfindCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubGraph>> {
        if (requestParameters['pathfindQueryRequest'] == null) {
            throw new runtime.RequiredError(
                'pathfindQueryRequest',
                'Required parameter "pathfindQueryRequest" was null or undefined when calling knowledgeGraphPathfindCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/knowledge-graph/pathfind/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PathfindQueryRequestToJSON(requestParameters['pathfindQueryRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubGraphFromJSON(jsonValue));
    }

    /**
     * Find paths between source and destination entries in the knowledge graph.
     * Find paths in knowledge graph
     */
    async knowledgeGraphPathfindCreate(requestParameters: KnowledgeGraphPathfindCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubGraph> {
        const response = await this.knowledgeGraphPathfindCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
