import { HighlightStyle } from '@codemirror/language';
import { tags } from '@lezer/highlight';

export const classHighlightStyle = HighlightStyle.define([
    { tag: tags.link, class: 'cm-link' },
    { tag: tags.heading, class: 'cm-header' },
    { tag: tags.emphasis, class: 'cm-em' },
    { tag: tags.strong, class: 'cm-strong' },
    { tag: tags.keyword, class: 'cm-keyword' },
    { tag: tags.atom, class: 'cm-atom' },
    { tag: tags.bool, class: 'cm-bool' },
    { tag: tags.url, class: 'cm-url' },
    { tag: tags.labelName, class: 'cm-labelName' },
    { tag: tags.inserted, class: 'cm-inserted' },
    { tag: tags.deleted, class: 'cm-deleted' },
    { tag: tags.literal, class: 'cm-literal' },
    { tag: tags.string, class: 'cm-string' },
    { tag: tags.number, class: 'cm-number' },
    { tag: [tags.regexp, tags.escape, tags.special(tags.string)], class: 'cm-string-2' },
    { tag: tags.variableName, class: 'cm-variable' },
    { tag: tags.local(tags.variableName), class: 'cm-variable-2' },
    { tag: [tags.definition(tags.variableName), tags.function(tags.variableName)], class: 'cm-variable-3' },
    { tag: tags.typeName, class: 'cm-type' },
    { tag: tags.className, class: 'cm-def' },
    { tag: tags.comment, class: 'cm-comment' },
    { tag: tags.meta, class: 'cm-meta' },
    { tag: tags.invalid, class: 'cm-invalid' },
    { tag: tags.heading1, class: 'cm-header-1' },
    { tag: tags.heading2, class: 'cm-header-2' },
    { tag: tags.heading3, class: 'cm-header-3' },
    { tag: tags.heading4, class: 'cm-header-4' },
    { tag: tags.heading5, class: 'cm-header-5' },
    { tag: tags.heading6, class: 'cm-header-6' },
    { tag: tags.quote, class: 'cm-quote' },
    { tag: tags.monospace, class: 'cm-monospace' },
]);
