"""
OpenAPI schema extensions for error responses.

This module provides utilities to automatically document error responses
in the OpenAPI specification generated by DRF Spectacular.
"""

from drf_spectacular.utils import OpenApiResponse, OpenApiExample
from drf_spectacular.openapi import AutoSchema


# Standard error response schema for OpenAPI documentation
ERROR_RESPONSE_SCHEMA = {
    'type': 'object',
    'properties': {
        'type': {
            'type': 'string',
            'description': 'URI reference identifying the problem type',
            'example': '/errors/validation-error'
        },
        'title': {
            'type': 'string',
            'description': 'Short, human-readable summary of the problem type',
            'example': 'Validation Error'
        },
        'status': {
            'type': 'integer',
            'description': 'HTTP status code',
            'example': 400
        },
        'detail': {
            'type': 'string',
            'description': 'Human-readable explanation specific to this occurrence',
            'example': 'One or more fields failed validation.'
        },
        'instance': {
            'type': 'string',
            'description': 'URI reference identifying the specific occurrence',
            'example': '/api/users/create'
        },
        'timestamp': {
            'type': 'string',
            'format': 'date-time',
            'description': 'ISO 8601 timestamp when the error occurred',
            'example': '2025-11-08T14:32:10.123456Z'
        },
        'code': {
            'type': 'string',
            'description': 'Machine-readable error code',
            'example': 'VALIDATION_ERROR'
        },
        'errors': {
            'type': 'object',
            'description': 'Field-level validation errors (only present for validation errors)',
            'additionalProperties': {
                'type': 'array',
                'items': {'type': 'string'}
            },
            'example': {
                'username': ['This field is required.'],
                'email': ['Enter a valid email address.']
            }
        }
    },
    'required': ['type', 'title', 'status', 'detail', 'timestamp', 'code']
}


def get_error_responses(*error_codes):
    """
    Generate OpenApiResponse objects for the given error codes.

    This function creates properly formatted OpenAPI response definitions
    that will be included in the API documentation.

    Args:
        *error_codes: ErrorCode enum values to document

    Returns:
        dict: Mapping of status codes to OpenApiResponse objects

    Example:
        from core.openapi import get_error_responses
        from user.exceptions import UserErrorCodes
        from drf_spectacular.utils import extend_schema

        @extend_schema(
            responses={
                **get_error_responses(
                    UserErrorCodes.DUPLICATE_USER,
                    UserErrorCodes.INVALID_PASSWORD
                )
            }
        )
        def create_user(request):
            ...
    """
    responses = {}

    for error_code in error_codes:
        status_code = error_code.status_code

        # Create example response
        example = {
            'type': error_code.type_uri,
            'title': error_code.title,
            'status': status_code,
            'detail': error_code.title,
            'instance': '/api/example',
            'timestamp': '2025-11-08T14:32:10.123456Z',
            'code': error_code.code,
        }

        # Create OpenApiResponse
        response = OpenApiResponse(
            response=ERROR_RESPONSE_SCHEMA,
            description=error_code.title,
            examples=[
                OpenApiExample(
                    name=error_code.code,
                    value=example,
                    response_only=True,
                )
            ]
        )

        # Add to responses dict (use status code as key)
        if status_code not in responses:
            responses[status_code] = response

    return responses


def get_common_error_responses():
    """
    Get common error responses that apply to most authenticated endpoints.

    Returns:
        dict: Common error responses (401, 403, 500)

    Example:
        from core.openapi import get_common_error_responses
        from drf_spectacular.utils import extend_schema

        @extend_schema(
            responses={
                200: MySerializer,
                **get_common_error_responses()
            }
        )
        def my_view(request):
            ...
    """
    from .exceptions import CoreErrorCodes

    return get_error_responses(
        CoreErrorCodes.UNAUTHENTICATED,
        CoreErrorCodes.PERMISSION_DENIED,
        CoreErrorCodes.INTERNAL_SERVER_ERROR,
    )


def get_validation_error_response():
    """
    Get validation error response (400).

    Returns:
        dict: Validation error response

    Example:
        from core.openapi import get_validation_error_response, get_common_error_responses
        from drf_spectacular.utils import extend_schema

        @extend_schema(
            responses={
                201: MySerializer,
                **get_validation_error_response(),
                **get_common_error_responses()
            }
        )
        def create_view(request):
            ...
    """
    from .exceptions import CoreErrorCodes

    # Include field-level errors in example
    example = {
        'type': CoreErrorCodes.VALIDATION_ERROR.type_uri,
        'title': CoreErrorCodes.VALIDATION_ERROR.title,
        'status': 400,
        'detail': 'One or more fields failed validation.',
        'instance': '/api/example',
        'timestamp': '2025-11-08T14:32:10.123456Z',
        'code': CoreErrorCodes.VALIDATION_ERROR.code,
        'errors': {
            'field_name': ['This field is required.'],
            'email': ['Enter a valid email address.']
        }
    }

    return {
        400: OpenApiResponse(
            response=ERROR_RESPONSE_SCHEMA,
            description='Validation Error',
            examples=[
                OpenApiExample(
                    name='VALIDATION_ERROR',
                    value=example,
                    response_only=True,
                )
            ]
        )
    }


def get_not_found_error_response():
    """
    Get not found error response (404).

    Returns:
        dict: Not found error response
    """
    from .exceptions import CoreErrorCodes

    return get_error_responses(CoreErrorCodes.NOT_FOUND)
