# Generated by Django 5.0.4 on 2025-02-26 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_newusernotification"),
        ("publish", "0003_remove_publishedreport_completed_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportProcessingErrorNotification",
            fields=[
                (
                    "messagenotification_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="notifications.messagenotification",
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "published_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_error_notifications",
                        to="publish.publishedreport",
                    ),
                ),
            ],
            bases=("notifications.messagenotification",),
        ),
        migrations.CreateModel(
            name="ReportRenderNotification",
            fields=[
                (
                    "messagenotification_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="notifications.messagenotification",
                    ),
                ),
                (
                    "published_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="render_notifications",
                        to="publish.publishedreport",
                    ),
                ),
            ],
            bases=("notifications.messagenotification",),
        ),
    ]
