# Generated by Django 5.0.4 on 2025-03-08 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0005_accessgrantednotification"),
    ]

    operations = [
        migrations.RunSQL(
            """
            DELETE FROM notifications_accessgrantednotification WHERE 1=1;
            """
        ),
        migrations.RemoveField(
            model_name="accessgrantednotification",
            name="id",
        ),
        migrations.AddField(
            model_name="accessgrantednotification",
            name="messagenotification_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="notifications.messagenotification",
            ),
            preserve_default=False,
        ),
    ]
