# Generated by Django 5.0.4 on 2025-04-02 14:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0006_remove_accessgrantednotification_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accessgrantednotification",
            name="entity",
        ),
        migrations.RemoveField(
            model_name="accessrequestnotification",
            name="entity",
        ),
    ]
