# Generated by Django 5.0.4 on 2025-04-02 14:31

import django.db.models.deletion
from django.db import migrations, models


def delete_all_accessnotification_objects(apps, schema_editor):
    AccessGrantedNotification = apps.get_model(
        "notifications", "AccessGrantedNotification"
    )
    AccessRequestNotification = apps.get_model(
        "notifications", "AccessRequestNotification"
    )
    AccessRequestNotification.objects.all().delete()
    AccessGrantedNotification.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0043_entry_aliases"),
        ("notifications", "0007_remove_accessgrantednotification_entity_and_more"),
    ]

    operations = [
        migrations.RunPython(delete_all_accessnotification_objects),
        migrations.AddField(
            model_name="accessgrantednotification",
            name="entity",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="entries.entry",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="accessrequestnotification",
            name="entity",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="entries.entry",
            ),
            preserve_default=False,
        ),
    ]
