# Generated by Django 5.0.4 on 2025-12-22 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelio', '0019_basedigest_summary_alter_basedigest_status'),
        ('notifications', '0008_accessgrantednotification_entity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrichmentCompleteNotification',
            fields=[
                ('messagenotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.messagenotification')),
                ('enrichment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complete_notifications', to='intelio.enrichmentrequest')),
            ],
            options={
                'abstract': False,
            },
            bases=('notifications.messagenotification',),
        ),
        migrations.CreateModel(
            name='EnrichmentErrorNotification',
            fields=[
                ('messagenotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.messagenotification')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('enrichment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_notifications', to='intelio.enrichmentrequest')),
            ],
            options={
                'abstract': False,
            },
            bases=('notifications.messagenotification',),
        ),
    ]
