# Generated by Django 6.0.2 on 2026-03-03 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0061_alter_attachment_context_alter_attachment_file_and_more'),
        ('intelio', '0027_alter_basedigest_digest_type_and_more'),
        ('notifications', '0009_enrichmentcompletenotification_and_more'),
        ('publish', '0011_alter_publishedreport_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessgrantednotification',
            name='entity',
            field=models.ForeignKey(help_text='Entity access was granted for.', on_delete=django.db.models.deletion.CASCADE, to='entries.entry'),
        ),
        migrations.AlterField(
            model_name='accessrequestnotification',
            name='entity',
            field=models.ForeignKey(help_text='Entity access was requested for.', on_delete=django.db.models.deletion.CASCADE, to='entries.entry'),
        ),
        migrations.AlterField(
            model_name='accessrequestnotification',
            name='requesting_user',
            field=models.ForeignKey(help_text='User who requested access.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enrichmentcompletenotification',
            name='enrichment_request',
            field=models.ForeignKey(help_text='Enrichment request that completed.', on_delete=django.db.models.deletion.CASCADE, related_name='complete_notifications', to='intelio.enrichmentrequest'),
        ),
        migrations.AlterField(
            model_name='enrichmenterrornotification',
            name='enrichment_request',
            field=models.ForeignKey(help_text='Enrichment request that failed.', on_delete=django.db.models.deletion.CASCADE, related_name='error_notifications', to='intelio.enrichmentrequest'),
        ),
        migrations.AlterField(
            model_name='enrichmenterrornotification',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error details from the enrichment failure.', null=True),
        ),
        migrations.AlterField(
            model_name='messagenotification',
            name='is_marked_unread',
            field=models.BooleanField(default=False, help_text='User manually marked as unread.'),
        ),
        migrations.AlterField(
            model_name='messagenotification',
            name='is_unread',
            field=models.BooleanField(default=True, help_text='Whether the notification has been read.'),
        ),
        migrations.AlterField(
            model_name='messagenotification',
            name='message',
            field=models.CharField(help_text='Human-readable notification text.'),
        ),
        migrations.AlterField(
            model_name='messagenotification',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='When the notification was created.'),
        ),
        migrations.AlterField(
            model_name='messagenotification',
            name='user',
            field=models.ForeignKey(help_text='Recipient of the notification.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newusernotification',
            name='new_user',
            field=models.ForeignKey(help_text='Newly registered user.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportprocessingerrornotification',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error details from the processing failure.', null=True),
        ),
        migrations.AlterField(
            model_name='reportprocessingerrornotification',
            name='published_report',
            field=models.ForeignKey(help_text='Report that failed to process.', on_delete=django.db.models.deletion.CASCADE, related_name='processing_error_notifications', to='publish.publishedreport'),
        ),
        migrations.AlterField(
            model_name='reportrendernotification',
            name='published_report',
            field=models.ForeignKey(help_text='Report that finished rendering.', on_delete=django.db.models.deletion.CASCADE, related_name='render_notifications', to='publish.publishedreport'),
        ),
    ]
