# Generated by Django 5.0.4 on 2026-01-22 16:26
# Recreates notification models after EnrichmentRequest PK change to UUID

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intelio', '0025_change_enrichmentrequest_pk_to_uuid'),
        ('notifications', '0009_enrichmentcompletenotification_and_more'),
    ]

    operations = [
        # Recreate EnrichmentCompleteNotification
        migrations.CreateModel(
            name='EnrichmentCompleteNotification',
            fields=[
                ('messagenotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.messagenotification')),
                ('enrichment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complete_notifications', to='intelio.enrichmentrequest')),
            ],
            options={
                'abstract': False,
            },
            bases=('notifications.messagenotification',),
        ),
        # Recreate EnrichmentErrorNotification
        migrations.CreateModel(
            name='EnrichmentErrorNotification',
            fields=[
                ('messagenotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.messagenotification')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('enrichment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_notifications', to='intelio.enrichmentrequest')),
            ],
            options={
                'abstract': False,
            },
            bases=('notifications.messagenotification',),
        ),
    ]
