[tool.bumpversion]
current_version = "2.10.2-beta.a070af1b"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)(-beta\\.(?P<beta>[a-f0-9]+))?"
serialize = [
    "{major}.{minor}.{patch}-beta.{beta}",
    "{major}.{minor}.{patch}"
]
search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_version = false
ignore_missing_files = false
tag = false
sign_tags = false
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = true
commit = false
message = "Bump version: {current_version} → {new_version}"

[tool.bumpversion.parts.major]
[tool.bumpversion.parts.minor]
[tool.bumpversion.parts.patch]

[tool.bumpversion.parts.beta]
optional_value = "gamma"
values = ["gamma"]
independent = false

[[tool.bumpversion.files]]
filename = "docs/content/_index.md"

[[tool.bumpversion.files]]
filename = "backend/cradle/settings_common.py"

[[tool.bumpversion.files]]
filename = "ui/package.json"
search = "\"version\": \"{current_version}\""
replace = "\"version\": \"{new_version}\""


[[tool.bumpversion.files]]
filename = "backend/pyproject.toml"
search = "version = \"{current_version}\""
replace = "version = \"{new_version}\""

