stages:
    - build
    - lint
    - test
    - deploy

image: node:20.12.2

cache:
    key: &global_cache_node_mods
        files:
            - package-lock.json
    paths:
        - .npm/
    policy: pull-push

run-build:
    stage: build
    cache:
        key: *global_cache_node_mods
    script:
        - npm ci --cache .npm --prefer-offline
        - npm run build
    artifacts:
        paths:
            - out/
        expire_in: 2 hours

run-lint:
    stage: lint
    cache:
        key: *global_cache_node_mods
    script:
        - npm ci --cache .npm --prefer-offline
        - npx eslint ./

run-test:
    stage: test
    cache:
        key: *global_cache_node_mods
    script:
        - npm ci --cache .npm --prefer-offline
        - npm test
    coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'

run-deploy:
    stage: deploy
    cache:
        key: *global_cache_node_mods
    rules:
        - if: $CI_COMMIT_REF_NAME == "dev"
        - if: $CI_COMMIT_REF_NAME == "main"
    variables:
        RSYNC_PASSWORD: RYDJZHRMPYUjICU
        API_BASE_URL: https://cradle.yigit.run/api
    script:
        - npm ci --cache .npm --prefer-offline
        - apt-get update -qq && apt-get install -qqy rsync
        - echo "VITE_API_BASE_URL=$API_BASE_URL" > ./src/renderer/.env
        - npm run tailwind
        - npm run render
        - rm ./src/renderer/.env
        - echo "$RSYNC_PASSWORD" > /tmp/rsync_password
        - chmod 600 /tmp/rsync_password
        - rsync -r --password-file=/tmp/rsync_password ./src/renderer/dist/* rsync://cradle@135.181.118.146:873/frontend/
