services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-07-16T23-46-41Z
    container_name: minio
    command: server /data --console-address "0.0.0.0:9001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: minioAdminPassword
      MINIO_SERVER_URL: http://localhost:8000
      MINIO_BROWSER_REDIRECT_URL: http://localhost:8000/minio/ui
    networks:
      cradle_demo_network:
        ipv4_address: 192.168.42.5

  postgres:
    image: pgrouting/pgrouting:16-3.5-3.7
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: cradle
      POSTGRES_PASSWORD: cradlePostgresPassword
      POSTGRES_DB: cradle
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cradle"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      cradle_demo_network:
        ipv4_address: 192.168.42.6

  redis:
    image: "redis:alpine"
    container_name: redis
    networks:
      cradle_demo_network:
        ipv4_address: 192.168.42.7

  celery:
    image: ghcr.io/prodaft/cradle:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
    container_name: celery
    restart: unless-stopped
    command: /app/entrypoint_celery.sh
    environment: &cradle_env
      INITIALIZE_ENTRYCLASSES: false
      DB_NAME: cradle
      DB_USER: cradle
      DB_PASSWORD: cradlePostgresPassword
      DB_HOST: 192.168.42.6
      DB_PORT: 5432

      MINIO_ENDPOINT: localhost:8000
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: minioAdminPassword
      MINIO_SECURE: false

      MINIO_BACKEND_URL: http://192.168.42.5:9000

      CRADLE_ADMIN_USER: admin
      CRADLE_ADMIN_EMAIL: admin@cradle.sh
      CRADLE_ADMIN_PASSWORD: admin

      CRADLE_SECRET_KEY: "super-secret-key"

      ALLOWED_HOSTS: localhost
      CRADLE_TRUSTED_ORIGINS: http://localhost
      BASE_URL: api
      FRONTEND_URL: http://localhost:8000

      DEBUG: true
      ALLOW_REGISTRATION: true
      AUTOREGISTER_ARTIFACT_TYPES: true
      MIN_ENTRY_COUNT_PER_NODE: 2
      MIN_ENTITY_COUNT_PER_NODE: 1

      EMAIL_HOST: ""
      EMAIL_PORT: 587
      EMAIL_HOST_USER: ""
      DEFAULT_FROM_EMAIL: ""
      EMAIL_HOST_PASSWORD: ""
      EMAIL_USE_TLS: false

      REQUIRE_EMAIL_CONFIRMATION: false
      REQUIRE_ADMIN_ACTIVATION: false

      INSTALL_FIXTURES: true

      REDIS_URL: "redis://192.168.42.7:6379/0"
      RABBITMQ_URL: "amqp://cradle:cradle@192.168.42.11:5672//"

      CELERY_QUEUES: "email,notes,graph,publish,import,access,enrich,digest"
      CELERY_CONCURRENCY: 4

    depends_on:
      - postgres
      - minio
    networks:
      cradle_demo_network:
        ipv4_address: 192.168.42.8

  cradle:
    image: ghcr.io/prodaft/cradle:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
    container_name: cradle
    restart: unless-stopped
    volumes:
      - ./build/www/static:/app/static
      - ./media:/media
    environment: *cradle_env
    depends_on:
      - postgres
      - minio
    networks:
      cradle_demo_network:
        ipv4_address: 192.168.42.9

  cradleweb:
    image: ghcr.io/prodaft/cradle-web:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile.ui
    container_name: cradleweb
    volumes:
      - ./build/www:/www
      - ./docker/nginx_demo.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    environment:
      NODE_ENV: production
      VITE_ENV: production
      FRONTEND_URL: http://localhost:8000
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - minio
    networks:
      cradle_demo_network:
        ipv4_address: 192.168.42.10

  rabbitmq:
    image: rabbitmq:3-management
    container_name: cradle_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: cradle
      RABBITMQ_DEFAULT_PASS: cradle
    networks:
      cradle_demo_network:
        ipv4_address: 192.168.42.11

volumes:
  postgres_data:
  minio_data:

networks:
  cradle_demo_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.42.0/24
