[project]
name = "cradle-backend"
version = "2.10.2"
description = "CRADLE Backend"
requires-python = ">=3.12"
dependencies = [
    "django==6.0.2",
    "djangorestframework==3.16.1",
    "django-cors-headers==4.9.0",
    "djangorestframework-simplejwt==5.5.1",
    "djangorestframework-stubs==3.16.8",
    "django-stubs",
    "django-stubs-ext",
    "minio",
    "django-model-utils",
    "django-extensions",
    "pytest",
    "pyyaml",
    "mistune",
    "drf-spectacular",
    "django-filter",
    "pytest-django",
    "environs",
    "django-lifecycle",
    "sentry-sdk[django]",
    "celery[redis]",
    "redis",
    "python-redis-lock",
    "diff-match-patch",
    "xeger",
    "bleach",
    "numpy",
    "psycopg2-binary",
    "dnspython",
    "bcrypt",
    "django-celery-beat",
    "requests",
    "python-frontmatter",
    "django-otp",
    "qrcode",
    "python-magic",
    "networkx",
    "scipy",
    "django-silk[formatting]==5.4.3",
    "gunicorn",
    "pydantic>=2.12.5",
    "django-storages[s3]>=1.14.6",
    "mwdblib>=4.7.0",
    "pycti>=6.9.22",
    "pymisp>=2.5.32.3",
    "pypdns>=2.3.2",
]

[project.optional-dependencies]
dev = [
    "bump-my-version>=1.2.6",
    "coverage>=7.13.1",
    "ruff>=0.14.11",
    "ipython>=9.9.0",
]

[tool.mypy]
namespace_packages = true
warn_unused_ignores = false
files = "**/*.py"
exclude = ["*/migrations/*.py","*/tests/*.py"]

[tool.mypy.plugins.django-stubs]
django_settings_module = "cradle.settings"

[tool.ruff]
line-length = 120
exclude = [
    ".git",
    "__pycache__",
    ".venv",
    "env",
    "venv",
    ".vscode",
    "cradle",
    "manage.py",
    "*/migrations/*"
]

[tool.ruff.lint]
ignore = ["E203"]
