/* tslint:disable */
/* eslint-disable */
/**
 * CRADLE
 * Threat Intelligence Knowledge Management
 *
 * The version of the OpenAPI document: 2.7.1 (2.7.1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccessEntity
 */
export interface AccessEntity {
    /**
     * 
     * @type {string}
     * @memberof AccessEntity
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AccessEntity
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AccessEntity
     */
    accessType?: string;
}

/**
 * Check if a given object implements the AccessEntity interface.
 */
export function instanceOfAccessEntity(value: object): value is AccessEntity {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function AccessEntityFromJSON(json: any): AccessEntity {
    return AccessEntityFromJSONTyped(json, false);
}

export function AccessEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'accessType': json['access_type'] == null ? undefined : json['access_type'],
    };
}

export function AccessEntityToJSON(json: any): AccessEntity {
    return AccessEntityToJSONTyped(json, false);
}

export function AccessEntityToJSONTyped(value?: AccessEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'access_type': value['accessType'],
    };
}

