/* tslint:disable */
/* eslint-disable */
/**
 * CRADLE
 * Threat Intelligence Knowledge Management
 *
 * The version of the OpenAPI document: 2.10.2-beta.0a1574ed (2.10.2-beta.0a1574ed)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserRetrieve } from './UserRetrieve';
import {
    UserRetrieveFromJSON,
    UserRetrieveFromJSONTyped,
    UserRetrieveToJSON,
    UserRetrieveToJSONTyped,
} from './UserRetrieve';

/**
 * 
 * @export
 * @interface AccessUser
 */
export interface AccessUser {
    /**
     * 
     * @type {UserRetrieve}
     * @memberof AccessUser
     */
    user: UserRetrieve;
    /**
     * * `none` - none
     * * `read` - read
     * * `read-write` - read-write
     * @type {string}
     * @memberof AccessUser
     */
    accessType: AccessUserAccessTypeEnum;
}


/**
 * @export
 */
export const AccessUserAccessTypeEnum = {
    None: 'none',
    Read: 'read',
    ReadWrite: 'read-write'
} as const;
export type AccessUserAccessTypeEnum = typeof AccessUserAccessTypeEnum[keyof typeof AccessUserAccessTypeEnum];


/**
 * Check if a given object implements the AccessUser interface.
 */
export function instanceOfAccessUser(value: object): value is AccessUser {
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('accessType' in value) || value['accessType'] === undefined) return false;
    return true;
}

export function AccessUserFromJSON(json: any): AccessUser {
    return AccessUserFromJSONTyped(json, false);
}

export function AccessUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessUser {
    if (json == null) {
        return json;
    }
    return {
        
        'user': UserRetrieveFromJSON(json['user']),
        'accessType': json['access_type'],
    };
}

export function AccessUserToJSON(json: any): AccessUser {
    return AccessUserToJSONTyped(json, false);
}

export function AccessUserToJSONTyped(value?: AccessUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': UserRetrieveToJSON(value['user']),
        'access_type': value['accessType'],
    };
}

