/* tslint:disable */
/* eslint-disable */
/**
 * CRADLE
 * Threat Intelligence Knowledge Management
 *
 * The version of the OpenAPI document: 2.9.5 (2.9.5)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Serializer for default note template.
 * @export
 * @interface DefaultNoteTemplateRequest
 */
export interface DefaultNoteTemplateRequest {
    /**
     * Default template text for new notes
     * @type {string}
     * @memberof DefaultNoteTemplateRequest
     */
    template: string;
}

/**
 * Check if a given object implements the DefaultNoteTemplateRequest interface.
 */
export function instanceOfDefaultNoteTemplateRequest(value: object): value is DefaultNoteTemplateRequest {
    if (!('template' in value) || value['template'] === undefined) return false;
    return true;
}

export function DefaultNoteTemplateRequestFromJSON(json: any): DefaultNoteTemplateRequest {
    return DefaultNoteTemplateRequestFromJSONTyped(json, false);
}

export function DefaultNoteTemplateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DefaultNoteTemplateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'template': json['template'],
    };
}

export function DefaultNoteTemplateRequestToJSON(json: any): DefaultNoteTemplateRequest {
    return DefaultNoteTemplateRequestToJSONTyped(json, false);
}

export function DefaultNoteTemplateRequestToJSONTyped(value?: DefaultNoteTemplateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'template': value['template'],
    };
}

