/* tslint:disable */
/* eslint-disable */
/**
 * CRADLE
 * Threat Intelligence Knowledge Management
 *
 * The version of the OpenAPI document: 2.9.5 (2.9.5)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailConfirmRequest
 */
export interface EmailConfirmRequest {
    /**
     * 
     * @type {string}
     * @memberof EmailConfirmRequest
     */
    token: string;
}

/**
 * Check if a given object implements the EmailConfirmRequest interface.
 */
export function instanceOfEmailConfirmRequest(value: object): value is EmailConfirmRequest {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function EmailConfirmRequestFromJSON(json: any): EmailConfirmRequest {
    return EmailConfirmRequestFromJSONTyped(json, false);
}

export function EmailConfirmRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailConfirmRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function EmailConfirmRequestToJSON(json: any): EmailConfirmRequest {
    return EmailConfirmRequestToJSONTyped(json, false);
}

export function EmailConfirmRequestToJSONTyped(value?: EmailConfirmRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

