/* tslint:disable */
/* eslint-disable */
/**
 * CRADLE
 * Threat Intelligence Knowledge Management
 *
 * The version of the OpenAPI document: 2.10.2-beta.eefb782a (2.10.2-beta.eefb782a)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EssentialUserRetrieve } from './EssentialUserRetrieve';
import {
    EssentialUserRetrieveFromJSON,
    EssentialUserRetrieveFromJSONTyped,
    EssentialUserRetrieveToJSON,
    EssentialUserRetrieveToJSONTyped,
} from './EssentialUserRetrieve';

/**
 * Serializer for detailed enrichment request information.
 * @export
 * @interface EnrichmentRequestDetail
 */
export interface EnrichmentRequestDetail {
    /**
     * 
     * @type {number}
     * @memberof EnrichmentRequestDetail
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof EnrichmentRequestDetail
     */
    readonly title?: string;
    /**
     * 
     * @type {Date}
     * @memberof EnrichmentRequestDetail
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof EnrichmentRequestDetail
     */
    readonly completedAt?: Date | null;
    /**
     * * `waiting` - Waiting
     * * `working` - Working
     * * `warning` - Warning
     * * `done` - Done
     * * `error` - Error
     * @type {string}
     * @memberof EnrichmentRequestDetail
     */
    readonly status?: EnrichmentRequestDetailStatusEnum;
    /**
     * 
     * @type {EssentialUserRetrieve}
     * @memberof EnrichmentRequestDetail
     */
    readonly userDetail?: EssentialUserRetrieve;
    /**
     * 
     * @type {string}
     * @memberof EnrichmentRequestDetail
     */
    readonly enricherTypes?: string;
    /**
     * 
     * @type {string}
     * @memberof EnrichmentRequestDetail
     */
    readonly enrichersDetail?: string;
    /**
     * 
     * @type {any}
     * @memberof EnrichmentRequestDetail
     */
    readonly request?: any | null;
    /**
     * 
     * @type {any}
     * @memberof EnrichmentRequestDetail
     */
    readonly errors?: any | null;
    /**
     * 
     * @type {any}
     * @memberof EnrichmentRequestDetail
     */
    readonly warnings?: any | null;
    /**
     * 
     * @type {any}
     * @memberof EnrichmentRequestDetail
     */
    readonly enricherStatus?: any | null;
}


/**
 * @export
 */
export const EnrichmentRequestDetailStatusEnum = {
    Waiting: 'waiting',
    Working: 'working',
    Warning: 'warning',
    Done: 'done',
    Error: 'error'
} as const;
export type EnrichmentRequestDetailStatusEnum = typeof EnrichmentRequestDetailStatusEnum[keyof typeof EnrichmentRequestDetailStatusEnum];


/**
 * Check if a given object implements the EnrichmentRequestDetail interface.
 */
export function instanceOfEnrichmentRequestDetail(value: object): value is EnrichmentRequestDetail {
    return true;
}

export function EnrichmentRequestDetailFromJSON(json: any): EnrichmentRequestDetail {
    return EnrichmentRequestDetailFromJSONTyped(json, false);
}

export function EnrichmentRequestDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnrichmentRequestDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'completedAt': json['completed_at'] == null ? undefined : (new Date(json['completed_at'])),
        'status': json['status'] == null ? undefined : json['status'],
        'userDetail': json['user_detail'] == null ? undefined : EssentialUserRetrieveFromJSON(json['user_detail']),
        'enricherTypes': json['enricher_types'] == null ? undefined : json['enricher_types'],
        'enrichersDetail': json['enrichers_detail'] == null ? undefined : json['enrichers_detail'],
        'request': json['request'] == null ? undefined : json['request'],
        'errors': json['errors'] == null ? undefined : json['errors'],
        'warnings': json['warnings'] == null ? undefined : json['warnings'],
        'enricherStatus': json['enricher_status'] == null ? undefined : json['enricher_status'],
    };
}

export function EnrichmentRequestDetailToJSON(json: any): EnrichmentRequestDetail {
    return EnrichmentRequestDetailToJSONTyped(json, false);
}

export function EnrichmentRequestDetailToJSONTyped(value?: Omit<EnrichmentRequestDetail, 'id'|'title'|'created_at'|'completed_at'|'status'|'user_detail'|'enricher_types'|'enrichers_detail'|'request'|'errors'|'warnings'|'enricher_status'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

