/* tslint:disable */
/* eslint-disable */
/**
 * CRADLE
 * Threat Intelligence Knowledge Management
 *
 * The version of the OpenAPI document: 2.10.2-beta.eefb782a (2.10.2-beta.eefb782a)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EnrichmentSettingsRequest
 */
export interface EnrichmentSettingsRequest {
    /**
     * 
     * @type {string}
     * @memberof EnrichmentSettingsRequest
     */
    id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EnrichmentSettingsRequest
     */
    enabled?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof EnrichmentSettingsRequest
     */
    forEclasses?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof EnrichmentSettingsRequest
     */
    enricherType: string;
    /**
     * 
     * @type {any}
     * @memberof EnrichmentSettingsRequest
     */
    settings?: any | null;
}

/**
 * Check if a given object implements the EnrichmentSettingsRequest interface.
 */
export function instanceOfEnrichmentSettingsRequest(value: object): value is EnrichmentSettingsRequest {
    if (!('enricherType' in value) || value['enricherType'] === undefined) return false;
    return true;
}

export function EnrichmentSettingsRequestFromJSON(json: any): EnrichmentSettingsRequest {
    return EnrichmentSettingsRequestFromJSONTyped(json, false);
}

export function EnrichmentSettingsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnrichmentSettingsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'forEclasses': json['for_eclasses'] == null ? undefined : json['for_eclasses'],
        'enricherType': json['enricher_type'],
        'settings': json['settings'] == null ? undefined : json['settings'],
    };
}

export function EnrichmentSettingsRequestToJSON(json: any): EnrichmentSettingsRequest {
    return EnrichmentSettingsRequestToJSONTyped(json, false);
}

export function EnrichmentSettingsRequestToJSONTyped(value?: EnrichmentSettingsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'enabled': value['enabled'],
        'for_eclasses': value['forEclasses'],
        'enricher_type': value['enricherType'],
        'settings': value['settings'],
    };
}

