/* tslint:disable */
/* eslint-disable */
/**
 * CRADLE
 * Threat Intelligence Knowledge Management
 *
 * The version of the OpenAPI document: 2.8.0 (2.8.0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EssentialUserRetrieve
 */
export interface EssentialUserRetrieve {
    /**
     * 
     * @type {string}
     * @memberof EssentialUserRetrieve
     */
    readonly id?: string;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     * @type {string}
     * @memberof EssentialUserRetrieve
     */
    username: string;
}

/**
 * Check if a given object implements the EssentialUserRetrieve interface.
 */
export function instanceOfEssentialUserRetrieve(value: object): value is EssentialUserRetrieve {
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function EssentialUserRetrieveFromJSON(json: any): EssentialUserRetrieve {
    return EssentialUserRetrieveFromJSONTyped(json, false);
}

export function EssentialUserRetrieveFromJSONTyped(json: any, ignoreDiscriminator: boolean): EssentialUserRetrieve {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'username': json['username'],
    };
}

export function EssentialUserRetrieveToJSON(json: any): EssentialUserRetrieve {
    return EssentialUserRetrieveToJSONTyped(json, false);
}

export function EssentialUserRetrieveToJSONTyped(value?: Omit<EssentialUserRetrieve, 'id'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
    };
}

