// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * CRADLE
 * Threat Intelligence Knowledge Management
 *
 * The version of the OpenAPI document: 2.10.2-beta.9bd46310 (2.10.2-beta.9bd46310)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Serializer for FileReference model.
 * @export
 * @interface FileReference
 */
export interface FileReference {
    /**
     * 
     * @type {string}
     * @memberof FileReference
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof FileReference
     */
    fileName?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof FileReference
     */
    readonly timestamp?: Date;
    /**
     * 
     * @type {number}
     * @memberof FileReference
     */
    fileSize?: number | null;
    /**
     * 
     * @type {string}
     * @memberof FileReference
     */
    readonly mimetype?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FileReference
     */
    readonly md5Hash?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FileReference
     */
    readonly sha1Hash?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FileReference
     */
    readonly sha256Hash?: string | null;
}

/**
 * Check if a given object implements the FileReference interface.
 */
export function instanceOfFileReference(value: object): value is FileReference {
    return true;
}

export function FileReferenceFromJSON(json: any): FileReference {
    return FileReferenceFromJSONTyped(json, false);
}

export function FileReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileReference {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'fileName': json['file_name'] == null ? undefined : json['file_name'],
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'fileSize': json['file_size'] == null ? undefined : json['file_size'],
        'mimetype': json['mimetype'] == null ? undefined : json['mimetype'],
        'md5Hash': json['md5_hash'] == null ? undefined : json['md5_hash'],
        'sha1Hash': json['sha1_hash'] == null ? undefined : json['sha1_hash'],
        'sha256Hash': json['sha256_hash'] == null ? undefined : json['sha256_hash'],
    };
}

export function FileReferenceToJSON(json: any): FileReference {
    return FileReferenceToJSONTyped(json, false);
}

export function FileReferenceToJSONTyped(value?: Omit<FileReference, 'timestamp'|'mimetype'|'md5_hash'|'sha1_hash'|'sha256_hash'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'file_name': value['fileName'],
        'file_size': value['fileSize'],
    };
}

