/* tslint:disable */
/* eslint-disable */
/**
 * CRADLE
 * Threat Intelligence Knowledge Management
 *
 * The version of the OpenAPI document: 2.7.1 (2.7.1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileReferenceWithNoteRequest
 */
export interface FileReferenceWithNoteRequest {
    /**
     * 
     * @type {string}
     * @memberof FileReferenceWithNoteRequest
     */
    minioFileName: string;
    /**
     * 
     * @type {string}
     * @memberof FileReferenceWithNoteRequest
     */
    mimetype?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FileReferenceWithNoteRequest
     */
    fileName: string;
    /**
     * 
     * @type {string}
     * @memberof FileReferenceWithNoteRequest
     */
    bucketName: string;
    /**
     * 
     * @type {string}
     * @memberof FileReferenceWithNoteRequest
     */
    md5Hash?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FileReferenceWithNoteRequest
     */
    sha1Hash?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FileReferenceWithNoteRequest
     */
    sha256Hash?: string | null;
}

/**
 * Check if a given object implements the FileReferenceWithNoteRequest interface.
 */
export function instanceOfFileReferenceWithNoteRequest(value: object): value is FileReferenceWithNoteRequest {
    if (!('minioFileName' in value) || value['minioFileName'] === undefined) return false;
    if (!('fileName' in value) || value['fileName'] === undefined) return false;
    if (!('bucketName' in value) || value['bucketName'] === undefined) return false;
    return true;
}

export function FileReferenceWithNoteRequestFromJSON(json: any): FileReferenceWithNoteRequest {
    return FileReferenceWithNoteRequestFromJSONTyped(json, false);
}

export function FileReferenceWithNoteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileReferenceWithNoteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'minioFileName': json['minio_file_name'],
        'mimetype': json['mimetype'] == null ? undefined : json['mimetype'],
        'fileName': json['file_name'],
        'bucketName': json['bucket_name'],
        'md5Hash': json['md5_hash'] == null ? undefined : json['md5_hash'],
        'sha1Hash': json['sha1_hash'] == null ? undefined : json['sha1_hash'],
        'sha256Hash': json['sha256_hash'] == null ? undefined : json['sha256_hash'],
    };
}

export function FileReferenceWithNoteRequestToJSON(json: any): FileReferenceWithNoteRequest {
    return FileReferenceWithNoteRequestToJSONTyped(json, false);
}

export function FileReferenceWithNoteRequestToJSONTyped(value?: FileReferenceWithNoteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'minio_file_name': value['minioFileName'],
        'mimetype': value['mimetype'],
        'file_name': value['fileName'],
        'bucket_name': value['bucketName'],
        'md5_hash': value['md5Hash'],
        'sha1_hash': value['sha1Hash'],
        'sha256_hash': value['sha256Hash'],
    };
}

