/* tslint:disable */
/* eslint-disable */
/**
 * CRADLE
 * Threat Intelligence Knowledge Management
 *
 * The version of the OpenAPI document: 2.10.2-beta.9bd46310 (2.10.2-beta.9bd46310)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response serializer for file upload initiation.
 * @export
 * @interface FileUploadResponse
 */
export interface FileUploadResponse {
    /**
     * 
     * @type {string}
     * @memberof FileUploadResponse
     */
    uploadId: string;
    /**
     * 
     * @type {string}
     * @memberof FileUploadResponse
     */
    presignedUrl: string;
    /**
     * 
     * @type {string}
     * @memberof FileUploadResponse
     */
    objectKey: string;
    /**
     * Expiration time in seconds
     * @type {number}
     * @memberof FileUploadResponse
     */
    expiresIn: number;
}

/**
 * Check if a given object implements the FileUploadResponse interface.
 */
export function instanceOfFileUploadResponse(value: object): value is FileUploadResponse {
    if (!('uploadId' in value) || value['uploadId'] === undefined) return false;
    if (!('presignedUrl' in value) || value['presignedUrl'] === undefined) return false;
    if (!('objectKey' in value) || value['objectKey'] === undefined) return false;
    if (!('expiresIn' in value) || value['expiresIn'] === undefined) return false;
    return true;
}

export function FileUploadResponseFromJSON(json: any): FileUploadResponse {
    return FileUploadResponseFromJSONTyped(json, false);
}

export function FileUploadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileUploadResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'uploadId': json['upload_id'],
        'presignedUrl': json['presigned_url'],
        'objectKey': json['object_key'],
        'expiresIn': json['expires_in'],
    };
}

export function FileUploadResponseToJSON(json: any): FileUploadResponse {
    return FileUploadResponseToJSONTyped(json, false);
}

export function FileUploadResponseToJSONTyped(value?: FileUploadResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'upload_id': value['uploadId'],
        'presigned_url': value['presignedUrl'],
        'object_key': value['objectKey'],
        'expires_in': value['expiresIn'],
    };
}

