/* tslint:disable */
/* eslint-disable */
/**
 * CRADLE
 * Threat Intelligence Knowledge Management
 *
 * The version of the OpenAPI document: 2.7.1 (2.7.1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Serializer for graph inaccessible response.
 * @export
 * @interface GraphInaccessibleResponse
 */
export interface GraphInaccessibleResponse {
    /**
     * List of inaccessible entry IDs
     * @type {Array<string>}
     * @memberof GraphInaccessibleResponse
     */
    inaccessible: Array<string>;
}

/**
 * Check if a given object implements the GraphInaccessibleResponse interface.
 */
export function instanceOfGraphInaccessibleResponse(value: object): value is GraphInaccessibleResponse {
    if (!('inaccessible' in value) || value['inaccessible'] === undefined) return false;
    return true;
}

export function GraphInaccessibleResponseFromJSON(json: any): GraphInaccessibleResponse {
    return GraphInaccessibleResponseFromJSONTyped(json, false);
}

export function GraphInaccessibleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GraphInaccessibleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'inaccessible': json['inaccessible'],
    };
}

export function GraphInaccessibleResponseToJSON(json: any): GraphInaccessibleResponse {
    return GraphInaccessibleResponseToJSONTyped(json, false);
}

export function GraphInaccessibleResponseToJSONTyped(value?: GraphInaccessibleResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'inaccessible': value['inaccessible'],
    };
}

