/* tslint:disable */
/* eslint-disable */
/**
 * CRADLE
 * Threat Intelligence Knowledge Management
 *
 * The version of the OpenAPI document: 2.10.2-beta.9bd46310 (2.10.2-beta.9bd46310)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntryWithDepth } from './EntryWithDepth';
import {
    EntryWithDepthFromJSON,
    EntryWithDepthFromJSONTyped,
    EntryWithDepthToJSON,
    EntryWithDepthToJSONTyped,
} from './EntryWithDepth';

/**
 * 
 * @export
 * @interface LazyPaginatedEntryWithDepthSerializerResponse
 */
export interface LazyPaginatedEntryWithDepthSerializerResponse {
    /**
     * Current page number
     * @type {number}
     * @memberof LazyPaginatedEntryWithDepthSerializerResponse
     */
    page: number;
    /**
     * Whether there are more pages available
     * @type {boolean}
     * @memberof LazyPaginatedEntryWithDepthSerializerResponse
     */
    hasNext: boolean;
    /**
     * 
     * @type {Array<EntryWithDepth>}
     * @memberof LazyPaginatedEntryWithDepthSerializerResponse
     */
    results: Array<EntryWithDepth>;
}

/**
 * Check if a given object implements the LazyPaginatedEntryWithDepthSerializerResponse interface.
 */
export function instanceOfLazyPaginatedEntryWithDepthSerializerResponse(value: object): value is LazyPaginatedEntryWithDepthSerializerResponse {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('hasNext' in value) || value['hasNext'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function LazyPaginatedEntryWithDepthSerializerResponseFromJSON(json: any): LazyPaginatedEntryWithDepthSerializerResponse {
    return LazyPaginatedEntryWithDepthSerializerResponseFromJSONTyped(json, false);
}

export function LazyPaginatedEntryWithDepthSerializerResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LazyPaginatedEntryWithDepthSerializerResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'hasNext': json['has_next'],
        'results': ((json['results'] as Array<any>).map(EntryWithDepthFromJSON)),
    };
}

export function LazyPaginatedEntryWithDepthSerializerResponseToJSON(json: any): LazyPaginatedEntryWithDepthSerializerResponse {
    return LazyPaginatedEntryWithDepthSerializerResponseToJSONTyped(json, false);
}

export function LazyPaginatedEntryWithDepthSerializerResponseToJSONTyped(value?: LazyPaginatedEntryWithDepthSerializerResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'has_next': value['hasNext'],
        'results': ((value['results'] as Array<any>).map(EntryWithDepthToJSON)),
    };
}

