/* tslint:disable */
/* eslint-disable */
/**
 * CRADLE
 * Threat Intelligence Knowledge Management
 *
 * The version of the OpenAPI document: 2.7.1 (2.7.1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Serializer for management action response.
 * @export
 * @interface ManagementActionResponse
 */
export interface ManagementActionResponse {
    /**
     * Success message
     * @type {string}
     * @memberof ManagementActionResponse
     */
    message: string;
}

/**
 * Check if a given object implements the ManagementActionResponse interface.
 */
export function instanceOfManagementActionResponse(value: object): value is ManagementActionResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ManagementActionResponseFromJSON(json: any): ManagementActionResponse {
    return ManagementActionResponseFromJSONTyped(json, false);
}

export function ManagementActionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManagementActionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function ManagementActionResponseToJSON(json: any): ManagementActionResponse {
    return ManagementActionResponseToJSONTyped(json, false);
}

export function ManagementActionResponseToJSONTyped(value?: ManagementActionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

