/* tslint:disable */
import { AccessRequestNotification, AccessRequestNotificationFromJSONTyped, AccessRequestNotificationToJSON } from "./AccessRequestNotification";
import { MessageNotification, MessageNotificationFromJSONTyped, MessageNotificationToJSON } from "./MessageNotification";
import { NewUserNotification, NewUserNotificationFromJSONTyped, NewUserNotificationToJSON } from "./NewUserNotification";
import { ReportProcessingErrorNotification, ReportProcessingErrorNotificationFromJSONTyped, ReportProcessingErrorNotificationToJSON } from "./ReportProcessingErrorNotification";
import { ReportRenderNotification, ReportRenderNotificationFromJSONTyped, ReportRenderNotificationToJSON } from "./ReportRenderNotification";

/* eslint-disable */
/**
 * CRADLE
 * Threat Intelligence Knowledge Management
 *
 * The version of the OpenAPI document: 2.10.2-beta.9bd46310 (2.10.2-beta.9bd46310)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * @type Notification
 * 
 * @export
 */
export type Notification = { notificationType: 'AccessRequestNotification' } & AccessRequestNotification | { notificationType: 'MessageNotification' } & MessageNotification | { notificationType: 'NewUserNotification' } & NewUserNotification | { notificationType: 'ReportProcessingErrorNotification' } & ReportProcessingErrorNotification | { notificationType: 'ReportRenderNotification' } & ReportRenderNotification;

export function NotificationFromJSON(json: any): Notification {
    return NotificationFromJSONTyped(json, false);
}

export function NotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Notification {
    if (json == null) {
        return json;
    }
    switch (json['notification_type']) {
        case 'AccessRequestNotification':
            return Object.assign({}, AccessRequestNotificationFromJSONTyped(json, true), { notificationType: 'AccessRequestNotification' } as const);
        case 'MessageNotification':
            return Object.assign({}, MessageNotificationFromJSONTyped(json, true), { notificationType: 'MessageNotification' } as const);
        case 'NewUserNotification':
            return Object.assign({}, NewUserNotificationFromJSONTyped(json, true), { notificationType: 'NewUserNotification' } as const);
        case 'ReportProcessingErrorNotification':
            return Object.assign({}, ReportProcessingErrorNotificationFromJSONTyped(json, true), { notificationType: 'ReportProcessingErrorNotification' } as const);
        case 'ReportRenderNotification':
            return Object.assign({}, ReportRenderNotificationFromJSONTyped(json, true), { notificationType: 'ReportRenderNotification' } as const);
        default:
            return json;
    }
}

export function NotificationToJSON(json: any): any {
    return NotificationToJSONTyped(json, false);
}

export function NotificationToJSONTyped(value?: Notification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['notificationType']) {
        case 'AccessRequestNotification':
            return Object.assign({}, AccessRequestNotificationToJSON(value), { notificationType: 'AccessRequestNotification' } as const);
        case 'MessageNotification':
            return Object.assign({}, MessageNotificationToJSON(value), { notificationType: 'MessageNotification' } as const);
        case 'NewUserNotification':
            return Object.assign({}, NewUserNotificationToJSON(value), { notificationType: 'NewUserNotification' } as const);
        case 'ReportProcessingErrorNotification':
            return Object.assign({}, ReportProcessingErrorNotificationToJSON(value), { notificationType: 'ReportProcessingErrorNotification' } as const);
        case 'ReportRenderNotification':
            return Object.assign({}, ReportRenderNotificationToJSON(value), { notificationType: 'ReportRenderNotification' } as const);
        default: return value;
    }
}

