/* tslint:disable */
/* eslint-disable */
/**
 * CRADLE
 * Threat Intelligence Knowledge Management
 *
 * The version of the OpenAPI document: 2.10.2-beta.5327a0f1 (2.10.2-beta.5327a0f1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Entry serializer for file references
 * @export
 * @interface OptimizedEntryResponseRequest
 */
export interface OptimizedEntryResponseRequest {
    /**
     * 
     * @type {string}
     * @memberof OptimizedEntryResponseRequest
     */
    name: string;
}

/**
 * Check if a given object implements the OptimizedEntryResponseRequest interface.
 */
export function instanceOfOptimizedEntryResponseRequest(value: object): value is OptimizedEntryResponseRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function OptimizedEntryResponseRequestFromJSON(json: any): OptimizedEntryResponseRequest {
    return OptimizedEntryResponseRequestFromJSONTyped(json, false);
}

export function OptimizedEntryResponseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OptimizedEntryResponseRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function OptimizedEntryResponseRequestToJSON(json: any): OptimizedEntryResponseRequest {
    return OptimizedEntryResponseRequestToJSONTyped(json, false);
}

export function OptimizedEntryResponseRequestToJSONTyped(value?: OptimizedEntryResponseRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

