/* tslint:disable */
/* eslint-disable */
/**
 * CRADLE
 * Threat Intelligence Knowledge Management
 *
 * The version of the OpenAPI document: 2.10.2-beta.9bd46310 (2.10.2-beta.9bd46310)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReportList } from './ReportList';
import {
    ReportListFromJSON,
    ReportListFromJSONTyped,
    ReportListToJSON,
    ReportListToJSONTyped,
} from './ReportList';

/**
 * 
 * @export
 * @interface PaginatedReportListList
 */
export interface PaginatedReportListList {
    /**
     * Current page number
     * @type {number}
     * @memberof PaginatedReportListList
     */
    page: number;
    /**
     * Total number of items
     * @type {number}
     * @memberof PaginatedReportListList
     */
    count: number;
    /**
     * Total number of pages
     * @type {number}
     * @memberof PaginatedReportListList
     */
    totalPages: number;
    /**
     * 
     * @type {Array<ReportList>}
     * @memberof PaginatedReportListList
     */
    results: Array<ReportList>;
}

/**
 * Check if a given object implements the PaginatedReportListList interface.
 */
export function instanceOfPaginatedReportListList(value: object): value is PaginatedReportListList {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedReportListListFromJSON(json: any): PaginatedReportListList {
    return PaginatedReportListListFromJSONTyped(json, false);
}

export function PaginatedReportListListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedReportListList {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'count': json['count'],
        'totalPages': json['total_pages'],
        'results': ((json['results'] as Array<any>).map(ReportListFromJSON)),
    };
}

export function PaginatedReportListListToJSON(json: any): PaginatedReportListList {
    return PaginatedReportListListToJSONTyped(json, false);
}

export function PaginatedReportListListToJSONTyped(value?: PaginatedReportListList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'count': value['count'],
        'total_pages': value['totalPages'],
        'results': ((value['results'] as Array<any>).map(ReportListToJSON)),
    };
}

