/* tslint:disable */
/* eslint-disable */
/**
 * CRADLE
 * Threat Intelligence Knowledge Management
 *
 * The version of the OpenAPI document: 2.8.0 (2.8.0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubGraph } from './SubGraph';
import {
    SubGraphFromJSON,
    SubGraphFromJSONTyped,
    SubGraphToJSON,
    SubGraphToJSONTyped,
} from './SubGraph';

/**
 * 
 * @export
 * @interface PaginatedSubGraphSerializerResponse
 */
export interface PaginatedSubGraphSerializerResponse {
    /**
     * Current page number
     * @type {number}
     * @memberof PaginatedSubGraphSerializerResponse
     */
    page: number;
    /**
     * Total number of items
     * @type {number}
     * @memberof PaginatedSubGraphSerializerResponse
     */
    count: number;
    /**
     * Total number of pages
     * @type {number}
     * @memberof PaginatedSubGraphSerializerResponse
     */
    totalPages: number;
    /**
     * 
     * @type {SubGraph}
     * @memberof PaginatedSubGraphSerializerResponse
     */
    results: SubGraph;
}

/**
 * Check if a given object implements the PaginatedSubGraphSerializerResponse interface.
 */
export function instanceOfPaginatedSubGraphSerializerResponse(value: object): value is PaginatedSubGraphSerializerResponse {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedSubGraphSerializerResponseFromJSON(json: any): PaginatedSubGraphSerializerResponse {
    return PaginatedSubGraphSerializerResponseFromJSONTyped(json, false);
}

export function PaginatedSubGraphSerializerResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedSubGraphSerializerResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'count': json['count'],
        'totalPages': json['total_pages'],
        'results': SubGraphFromJSON(json['results']),
    };
}

export function PaginatedSubGraphSerializerResponseToJSON(json: any): PaginatedSubGraphSerializerResponse {
    return PaginatedSubGraphSerializerResponseToJSONTyped(json, false);
}

export function PaginatedSubGraphSerializerResponseToJSONTyped(value?: PaginatedSubGraphSerializerResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'count': value['count'],
        'total_pages': value['totalPages'],
        'results': SubGraphToJSON(value['results']),
    };
}

