/* tslint:disable */
/* eslint-disable */
/**
 * CRADLE
 * Threat Intelligence Knowledge Management
 *
 * The version of the OpenAPI document: 2.8.0 (2.8.0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserRetrieve } from './UserRetrieve';
import {
    UserRetrieveFromJSON,
    UserRetrieveFromJSONTyped,
    UserRetrieveToJSON,
    UserRetrieveToJSONTyped,
} from './UserRetrieve';

/**
 * 
 * @export
 * @interface Snippet
 */
export interface Snippet {
    /**
     * 
     * @type {string}
     * @memberof Snippet
     */
    readonly id?: string;
    /**
     * 
     * @type {UserRetrieve}
     * @memberof Snippet
     */
    readonly owner?: UserRetrieve;
    /**
     * 
     * @type {string}
     * @memberof Snippet
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Snippet
     */
    content: string;
    /**
     * 
     * @type {Date}
     * @memberof Snippet
     */
    readonly createdOn?: Date;
}

/**
 * Check if a given object implements the Snippet interface.
 */
export function instanceOfSnippet(value: object): value is Snippet {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function SnippetFromJSON(json: any): Snippet {
    return SnippetFromJSONTyped(json, false);
}

export function SnippetFromJSONTyped(json: any, ignoreDiscriminator: boolean): Snippet {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'owner': json['owner'] == null ? undefined : UserRetrieveFromJSON(json['owner']),
        'name': json['name'],
        'content': json['content'],
        'createdOn': json['created_on'] == null ? undefined : (new Date(json['created_on'])),
    };
}

export function SnippetToJSON(json: any): Snippet {
    return SnippetToJSONTyped(json, false);
}

export function SnippetToJSONTyped(value?: Omit<Snippet, 'id'|'owner'|'created_on'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'content': value['content'],
    };
}

