/* tslint:disable */
/* eslint-disable */
/**
 * CRADLE
 * Threat Intelligence Knowledge Management
 *
 * The version of the OpenAPI document: 2.9.5 (2.9.5)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SnippetRequest
 */
export interface SnippetRequest {
    /**
     * 
     * @type {string}
     * @memberof SnippetRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SnippetRequest
     */
    content: string;
}

/**
 * Check if a given object implements the SnippetRequest interface.
 */
export function instanceOfSnippetRequest(value: object): value is SnippetRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function SnippetRequestFromJSON(json: any): SnippetRequest {
    return SnippetRequestFromJSONTyped(json, false);
}

export function SnippetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SnippetRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'content': json['content'],
    };
}

export function SnippetRequestToJSON(json: any): SnippetRequest {
    return SnippetRequestToJSONTyped(json, false);
}

export function SnippetRequestToJSONTyped(value?: SnippetRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'content': value['content'],
    };
}

