/* tslint:disable */
/* eslint-disable */
/**
 * CRADLE
 * Threat Intelligence Knowledge Management
 *
 * The version of the OpenAPI document: 2.10.2-beta.9bd46310 (2.10.2-beta.9bd46310)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserUpdateRequest
 */
export interface UserUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof UserUpdateRequest
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateRequest
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateRequest
     */
    catalystApiKey?: string | null;
    /**
     * Whether to enable Vim keybindings in the editor
     * @type {boolean}
     * @memberof UserUpdateRequest
     */
    vimMode?: boolean;
    /**
     * Theme to use in the UI
     * 
     * * `dark` - Dark
     * * `light` - Light
     * @type {string}
     * @memberof UserUpdateRequest
     */
    theme?: UserUpdateRequestThemeEnum;
    /**
     * * `admin` - Admin
     * * `manager` - Manager
     * * `entrymanager` - Entry Manager
     * * `author` - User
     * @type {string}
     * @memberof UserUpdateRequest
     */
    role?: UserUpdateRequestRoleEnum;
    /**
     * 
     * @type {boolean}
     * @memberof UserUpdateRequest
     */
    emailConfirmed?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserUpdateRequest
     */
    isActive?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserUpdateRequest
     */
    twoFactorEnabled?: boolean;
}


/**
 * @export
 */
export const UserUpdateRequestThemeEnum = {
    Dark: 'dark',
    Light: 'light'
} as const;
export type UserUpdateRequestThemeEnum = typeof UserUpdateRequestThemeEnum[keyof typeof UserUpdateRequestThemeEnum];

/**
 * @export
 */
export const UserUpdateRequestRoleEnum = {
    Admin: 'admin',
    Manager: 'manager',
    Entrymanager: 'entrymanager',
    Author: 'author'
} as const;
export type UserUpdateRequestRoleEnum = typeof UserUpdateRequestRoleEnum[keyof typeof UserUpdateRequestRoleEnum];


/**
 * Check if a given object implements the UserUpdateRequest interface.
 */
export function instanceOfUserUpdateRequest(value: object): value is UserUpdateRequest {
    return true;
}

export function UserUpdateRequestFromJSON(json: any): UserUpdateRequest {
    return UserUpdateRequestFromJSONTyped(json, false);
}

export function UserUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'] == null ? undefined : json['username'],
        'email': json['email'] == null ? undefined : json['email'],
        'password': json['password'] == null ? undefined : json['password'],
        'catalystApiKey': json['catalyst_api_key'] == null ? undefined : json['catalyst_api_key'],
        'vimMode': json['vim_mode'] == null ? undefined : json['vim_mode'],
        'theme': json['theme'] == null ? undefined : json['theme'],
        'role': json['role'] == null ? undefined : json['role'],
        'emailConfirmed': json['email_confirmed'] == null ? undefined : json['email_confirmed'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'twoFactorEnabled': json['two_factor_enabled'] == null ? undefined : json['two_factor_enabled'],
    };
}

export function UserUpdateRequestToJSON(json: any): UserUpdateRequest {
    return UserUpdateRequestToJSONTyped(json, false);
}

export function UserUpdateRequestToJSONTyped(value?: UserUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'email': value['email'],
        'password': value['password'],
        'catalyst_api_key': value['catalystApiKey'],
        'vim_mode': value['vimMode'],
        'theme': value['theme'],
        'role': value['role'],
        'email_confirmed': value['emailConfirmed'],
        'is_active': value['isActive'],
        'two_factor_enabled': value['twoFactorEnabled'],
    };
}

