/* tslint:disable */
/* eslint-disable */
/**
 * CRADLE
 * Threat Intelligence Knowledge Management
 *
 * The version of the OpenAPI document: 2.10.2-beta.9bd46310 (2.10.2-beta.9bd46310)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessageNotification
 */
export interface MessageNotification {
    /**
     * 
     * @type {string}
     * @memberof MessageNotification
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof MessageNotification
     */
    message: string;
    /**
     * 
     * @type {boolean}
     * @memberof MessageNotification
     */
    isMarkedUnread?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof MessageNotification
     */
    readonly timestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof MessageNotification
     */
    readonly notificationType?: string;
}

/**
 * Check if a given object implements the MessageNotification interface.
 */
export function instanceOfMessageNotification(value: object): value is MessageNotification {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function MessageNotificationFromJSON(json: any): MessageNotification {
    return MessageNotificationFromJSONTyped(json, false);
}

export function MessageNotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageNotification {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'message': json['message'],
        'isMarkedUnread': json['is_marked_unread'] == null ? undefined : json['is_marked_unread'],
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'notificationType': json['notification_type'] == null ? undefined : json['notification_type'],
    };
}

export function MessageNotificationToJSON(json: any): MessageNotification {
    return MessageNotificationToJSONTyped(json, false);
}

export function MessageNotificationToJSONTyped(value?: Omit<MessageNotification, 'id'|'timestamp'|'notification_type'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'is_marked_unread': value['isMarkedUnread'],
    };
}

