# Generated by Django 6.0.2 on 2026-03-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='key',
            field=models.CharField(help_text='Namespaced setting key (e.g. notes.min_entries).', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.JSONField(help_text='Setting value (JSON-serializable).'),
        ),
    ]
