/* tslint:disable */
/* eslint-disable */
/**
 * CRADLE
 * Threat Intelligence Knowledge Management
 *
 * The version of the OpenAPI document: 2.7.0 (2.7.0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Serializer for digest subclass information.
 * @export
 * @interface DigestSubclass
 */
export interface DigestSubclass {
    /**
     * The class name of the digest
     * @type {string}
     * @memberof DigestSubclass
     */
    className: string;
    /**
     * The display name of the digest
     * @type {string}
     * @memberof DigestSubclass
     */
    name: string;
    /**
     * Whether this digest type can infer entities
     * @type {boolean}
     * @memberof DigestSubclass
     */
    inferEntities: boolean;
}

/**
 * Check if a given object implements the DigestSubclass interface.
 */
export function instanceOfDigestSubclass(value: object): value is DigestSubclass {
    if (!('className' in value) || value['className'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('inferEntities' in value) || value['inferEntities'] === undefined) return false;
    return true;
}

export function DigestSubclassFromJSON(json: any): DigestSubclass {
    return DigestSubclassFromJSONTyped(json, false);
}

export function DigestSubclassFromJSONTyped(json: any, ignoreDiscriminator: boolean): DigestSubclass {
    if (json == null) {
        return json;
    }
    return {
        
        'className': json['class_name'],
        'name': json['name'],
        'inferEntities': json['infer_entities'],
    };
}

export function DigestSubclassToJSON(json: any): DigestSubclass {
    return DigestSubclassToJSONTyped(json, false);
}

export function DigestSubclassToJSONTyped(value?: DigestSubclass | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'class_name': value['className'],
        'name': value['name'],
        'infer_entities': value['inferEntities'],
    };
}

