/* tslint:disable */
/* eslint-disable */
/**
 * CRADLE
 * Threat Intelligence Knowledge Management
 *
 * The version of the OpenAPI document: 2.7.0 (2.7.0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntryClass } from './EntryClass';
import {
    EntryClassFromJSON,
    EntryClassFromJSONTyped,
    EntryClassToJSON,
    EntryClassToJSONTyped,
} from './EntryClass';

/**
 * 
 * @export
 * @interface EnrichmentSettings
 */
export interface EnrichmentSettings {
    /**
     * 
     * @type {string}
     * @memberof EnrichmentSettings
     */
    id?: string;
    /**
     * * `manual` - Manual
     * * `on_create` - On Create
     * * `periodic` - Periodic
     * @type {string}
     * @memberof EnrichmentSettings
     */
    strategy?: EnrichmentSettingsStrategyEnum;
    /**
     * 
     * @type {boolean}
     * @memberof EnrichmentSettings
     */
    enabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof EnrichmentSettings
     */
    periodicity?: string;
    /**
     * 
     * @type {Array<EntryClass>}
     * @memberof EnrichmentSettings
     */
    readonly forEclassesDetail?: Array<EntryClass>;
    /**
     * 
     * @type {string}
     * @memberof EnrichmentSettings
     */
    enricherType: string;
    /**
     * 
     * @type {any}
     * @memberof EnrichmentSettings
     */
    settings?: any | null;
    /**
     * 
     * @type {string}
     * @memberof EnrichmentSettings
     */
    readonly displayName?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof EnrichmentSettings
     */
    readonly formFields?: { [key: string]: any; };
}


/**
 * @export
 */
export const EnrichmentSettingsStrategyEnum = {
    Manual: 'manual',
    OnCreate: 'on_create',
    Periodic: 'periodic'
} as const;
export type EnrichmentSettingsStrategyEnum = typeof EnrichmentSettingsStrategyEnum[keyof typeof EnrichmentSettingsStrategyEnum];


/**
 * Check if a given object implements the EnrichmentSettings interface.
 */
export function instanceOfEnrichmentSettings(value: object): value is EnrichmentSettings {
    if (!('enricherType' in value) || value['enricherType'] === undefined) return false;
    return true;
}

export function EnrichmentSettingsFromJSON(json: any): EnrichmentSettings {
    return EnrichmentSettingsFromJSONTyped(json, false);
}

export function EnrichmentSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnrichmentSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'strategy': json['strategy'] == null ? undefined : json['strategy'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'periodicity': json['periodicity'] == null ? undefined : json['periodicity'],
        'forEclassesDetail': json['for_eclasses_detail'] == null ? undefined : ((json['for_eclasses_detail'] as Array<any>).map(EntryClassFromJSON)),
        'enricherType': json['enricher_type'],
        'settings': json['settings'] == null ? undefined : json['settings'],
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
        'formFields': json['form_fields'] == null ? undefined : json['form_fields'],
    };
}

export function EnrichmentSettingsToJSON(json: any): EnrichmentSettings {
    return EnrichmentSettingsToJSONTyped(json, false);
}

export function EnrichmentSettingsToJSONTyped(value?: Omit<EnrichmentSettings, 'for_eclasses_detail'|'display_name'|'form_fields'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'strategy': value['strategy'],
        'enabled': value['enabled'],
        'periodicity': value['periodicity'],
        'enricher_type': value['enricherType'],
        'settings': value['settings'],
    };
}

