/* tslint:disable */
/* eslint-disable */
/**
 * CRADLE
 * Threat Intelligence Knowledge Management
 *
 * The version of the OpenAPI document: 2.7.0 (2.7.0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntryClassSerializerNoChildren } from './EntryClassSerializerNoChildren';
import {
    EntryClassSerializerNoChildrenFromJSON,
    EntryClassSerializerNoChildrenFromJSONTyped,
    EntryClassSerializerNoChildrenToJSON,
    EntryClassSerializerNoChildrenToJSONTyped,
} from './EntryClassSerializerNoChildren';
import type { Entry } from './Entry';
import {
    EntryFromJSON,
    EntryFromJSONTyped,
    EntryToJSON,
    EntryToJSONTyped,
} from './Entry';

/**
 * 
 * @export
 * @interface Entity
 */
export interface Entity {
    /**
     * 
     * @type {number}
     * @memberof Entity
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof Entity
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Entity
     */
    description?: string | null;
    /**
     * 
     * @type {EntryClassSerializerNoChildren}
     * @memberof Entity
     */
    readonly entryClass?: EntryClassSerializerNoChildren;
    /**
     * 
     * @type {Array<Entry>}
     * @memberof Entity
     */
    readonly aliasesDetail?: Array<Entry>;
}

/**
 * Check if a given object implements the Entity interface.
 */
export function instanceOfEntity(value: object): value is Entity {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function EntityFromJSON(json: any): Entity {
    return EntityFromJSONTyped(json, false);
}

export function EntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Entity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'entryClass': json['entry_class'] == null ? undefined : EntryClassSerializerNoChildrenFromJSON(json['entry_class']),
        'aliasesDetail': json['aliases_detail'] == null ? undefined : ((json['aliases_detail'] as Array<any>).map(EntryFromJSON)),
    };
}

export function EntityToJSON(json: any): Entity {
    return EntityToJSONTyped(json, false);
}

export function EntityToJSONTyped(value?: Omit<Entity, 'id'|'entry_class'|'aliases_detail'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

