/* tslint:disable */
/* eslint-disable */
/**
 * CRADLE
 * Threat Intelligence Knowledge Management
 *
 * The version of the OpenAPI document: 2.7.0 (2.7.0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Report } from './Report';
import {
    ReportFromJSON,
    ReportFromJSONTyped,
    ReportToJSON,
    ReportToJSONTyped,
} from './Report';

/**
 * 
 * @export
 * @interface PaginatedReportList
 */
export interface PaginatedReportList {
    /**
     * Current page number
     * @type {number}
     * @memberof PaginatedReportList
     */
    page: number;
    /**
     * Total number of items
     * @type {number}
     * @memberof PaginatedReportList
     */
    count: number;
    /**
     * Total number of pages
     * @type {number}
     * @memberof PaginatedReportList
     */
    totalPages: number;
    /**
     * 
     * @type {Array<Report>}
     * @memberof PaginatedReportList
     */
    results: Array<Report>;
}

/**
 * Check if a given object implements the PaginatedReportList interface.
 */
export function instanceOfPaginatedReportList(value: object): value is PaginatedReportList {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedReportListFromJSON(json: any): PaginatedReportList {
    return PaginatedReportListFromJSONTyped(json, false);
}

export function PaginatedReportListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedReportList {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'count': json['count'],
        'totalPages': json['total_pages'],
        'results': ((json['results'] as Array<any>).map(ReportFromJSON)),
    };
}

export function PaginatedReportListToJSON(json: any): PaginatedReportList {
    return PaginatedReportListToJSONTyped(json, false);
}

export function PaginatedReportListToJSONTyped(value?: PaginatedReportList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'count': value['count'],
        'total_pages': value['totalPages'],
        'results': ((value['results'] as Array<any>).map(ReportToJSON)),
    };
}

