/* tslint:disable */
/* eslint-disable */
/**
 * CRADLE
 * Threat Intelligence Knowledge Management
 *
 * The version of the OpenAPI document: 2.7.0 (2.7.0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntryResponse } from './EntryResponse';
import {
    EntryResponseFromJSON,
    EntryResponseFromJSONTyped,
    EntryResponseToJSON,
    EntryResponseToJSONTyped,
} from './EntryResponse';

/**
 * 
 * @export
 * @interface PaginatedEntryResponseList
 */
export interface PaginatedEntryResponseList {
    /**
     * Current page number
     * @type {number}
     * @memberof PaginatedEntryResponseList
     */
    page: number;
    /**
     * Total number of items
     * @type {number}
     * @memberof PaginatedEntryResponseList
     */
    count: number;
    /**
     * Total number of pages
     * @type {number}
     * @memberof PaginatedEntryResponseList
     */
    totalPages: number;
    /**
     * 
     * @type {Array<EntryResponse>}
     * @memberof PaginatedEntryResponseList
     */
    results: Array<EntryResponse>;
}

/**
 * Check if a given object implements the PaginatedEntryResponseList interface.
 */
export function instanceOfPaginatedEntryResponseList(value: object): value is PaginatedEntryResponseList {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedEntryResponseListFromJSON(json: any): PaginatedEntryResponseList {
    return PaginatedEntryResponseListFromJSONTyped(json, false);
}

export function PaginatedEntryResponseListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedEntryResponseList {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'count': json['count'],
        'totalPages': json['total_pages'],
        'results': ((json['results'] as Array<any>).map(EntryResponseFromJSON)),
    };
}

export function PaginatedEntryResponseListToJSON(json: any): PaginatedEntryResponseList {
    return PaginatedEntryResponseListToJSONTyped(json, false);
}

export function PaginatedEntryResponseListToJSONTyped(value?: PaginatedEntryResponseList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'count': value['count'],
        'total_pages': value['totalPages'],
        'results': ((value['results'] as Array<any>).map(EntryResponseToJSON)),
    };
}

