/* tslint:disable */
/* eslint-disable */
/**
 * CRADLE
 * Threat Intelligence Knowledge Management
 *
 * The version of the OpenAPI document: 2.7.0 (2.7.0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EventLog } from './EventLog';
import {
    EventLogFromJSON,
    EventLogFromJSONTyped,
    EventLogToJSON,
    EventLogToJSONTyped,
} from './EventLog';

/**
 * 
 * @export
 * @interface PaginatedEventLogList
 */
export interface PaginatedEventLogList {
    /**
     * Current page number
     * @type {number}
     * @memberof PaginatedEventLogList
     */
    page: number;
    /**
     * Total number of items
     * @type {number}
     * @memberof PaginatedEventLogList
     */
    count: number;
    /**
     * Total number of pages
     * @type {number}
     * @memberof PaginatedEventLogList
     */
    totalPages: number;
    /**
     * 
     * @type {Array<EventLog>}
     * @memberof PaginatedEventLogList
     */
    results: Array<EventLog>;
}

/**
 * Check if a given object implements the PaginatedEventLogList interface.
 */
export function instanceOfPaginatedEventLogList(value: object): value is PaginatedEventLogList {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedEventLogListFromJSON(json: any): PaginatedEventLogList {
    return PaginatedEventLogListFromJSONTyped(json, false);
}

export function PaginatedEventLogListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedEventLogList {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'count': json['count'],
        'totalPages': json['total_pages'],
        'results': ((json['results'] as Array<any>).map(EventLogFromJSON)),
    };
}

export function PaginatedEventLogListToJSON(json: any): PaginatedEventLogList {
    return PaginatedEventLogListToJSONTyped(json, false);
}

export function PaginatedEventLogListToJSONTyped(value?: PaginatedEventLogList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'count': value['count'],
        'total_pages': value['totalPages'],
        'results': ((value['results'] as Array<any>).map(EventLogToJSON)),
    };
}

