# Generated by Django 5.0.4 on 2024-10-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_remove_cradleuser_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="cradleuser",
            name="catalyst_api_key",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="cradleuser",
            name="vt_api_key",
            field=models.TextField(null=True),
        ),
    ]
