# Generated by Django 5.0.4 on 2024-10-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_cradleuser_catalyst_api_key_cradleuser_vt_api_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cradleuser",
            name="catalyst_api_key",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cradleuser",
            name="vt_api_key",
            field=models.TextField(blank=True, null=True),
        ),
    ]
