# Generated by Django 5.0.4 on 2025-02-17 10:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_cradleuser_role"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION get_readable_notes(user_uuid UUID)
            RETURNS TABLE (note_id UUID)
            LANGUAGE plpgsql
            AS $$
            DECLARE
                is_super BOOLEAN := FALSE;
            BEGIN
                SELECT role = 'admin'
                INTO is_super
                FROM user_cradleuser
                WHERE id = user_uuid;

                IF is_super THEN
                    -- If the user is superuser, return all notes
                    RETURN QUERY
                    SELECT DISTINCT ne.note_id
                    FROM notes_note_entries AS ne;
                ELSE
                    -- Otherwise, return only the notes for which this user has access
                    RETURN QUERY
                    SELECT DISTINCT ne.note_id
                    FROM notes_note_entries AS ne
                    JOIN entries_entry ee ON ne.entry_id = ee.id
                    JOIN entries_entryclass ec ON ee.entry_class_id = ec.subtype
                    RIGHT JOIN (
                        SELECT *
                        FROM access_access
                        WHERE user_id = user_uuid
                          AND access_type <> 'none'
                    ) a ON ne.entry_id = a.entity_id
                    WHERE ec.type = 'entity';
                END IF;
            END;
            $$;
            """
        ),
        migrations.RunSQL(
            """
            UPDATE user_cradleuser
            SET role = 'admin'
            WHERE is_superuser = TRUE;
            """
        ),
    ]
