# Generated by Django 5.0.4 on 2025-02-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0010_permission_system_modification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cradleuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("entrymanager", "Entry Manager"),
                    ("user", "User"),
                ],
                default="user",
                max_length=32,
            ),
        ),
    ]
