# Generated by Django 5.0.4 on 2025-03-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0012_alter_cradleuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cradleuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("entrymanager", "Entry Manager"),
                    ("author", "User"),
                ],
                default="author",
                max_length=32,
            ),
        ),
    ]
