# Generated by Django 5.0.4 on 2025-04-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0014_alter_cradleuser_email_confirmed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cradleuser",
            name="email_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="cradleuser",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
