# Generated by Django 5.0.4 on 2025-04-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0015_alter_cradleuser_email_confirmed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cradleuser",
            name="api_key",
            field=models.TextField(blank=True, null=True),
        ),
    ]
