# Generated by Django 5.0.4 on 2025-04-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0016_cradleuser_api_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cradleuser",
            name="api_key",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
