# Generated by Django 5.0.4 on 2025-06-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0017_alter_cradleuser_api_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="cradleuser",
            name="two_factor_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
