# Generated by Django 5.0.4 on 2025-06-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0018_cradleuser_two_factor_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="cradleuser",
            name="default_note_template",
            field=models.TextField(
                blank=True, help_text="Default template for new notes", null=True
            ),
        ),
        migrations.AddField(
            model_name="cradleuser",
            name="vim_mode",
            field=models.BooleanField(
                default=False,
                help_text="Whether to enable Vim keybindings in the editor",
            ),
        ),
    ]
