# Generated by Django 5.0.4 on 2025-07-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0020_cradleuser_compact_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="cradleuser",
            name="theme",
            field=models.CharField(
                choices=[("dark", "Dark"), ("light", "Light")],
                default="dark",
                help_text="Theme to use in the UI",
            ),
        ),
    ]
