# Generated by Django 5.0.4 on 2025-10-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_cradleuser_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cradleuser',
            name='compact_mode',
        ),
    ]
