# Generated by Django 5.0.4 on 2025-10-23 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_remove_compact_mode_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cradleuser',
            name='vt_api_key',
        ),
    ]
