# Generated by Django 5.0.4 on 2025-12-29 15:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_remove_cradleuser_vt_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refresh_token_jti', models.CharField(db_index=True, help_text='JWT ID of the refresh token', max_length=255, unique=True)),
                ('device_info', models.CharField(blank=True, help_text='Device/browser information', max_length=255, null=True)),
                ('ip_address', models.CharField(blank=True, help_text='IP address of the session', max_length=45, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the session was created')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Last activity timestamp')),
                ('expires_at', models.DateTimeField(help_text='When the refresh token expires')),
                ('is_current', models.BooleanField(default=False, help_text='Whether this is the current session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['user', '-last_activity'], name='user_userse_user_id_8dbc22_idx'), models.Index(fields=['refresh_token_jti'], name='user_userse_refresh_fb6508_idx')],
            },
        ),
    ]
