# Generated by Django 5.0.4 on 2025-12-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_usersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(db_index=True, help_text='JWT ID of the blacklisted token', max_length=255, unique=True)),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True, help_text='When the token was blacklisted')),
                ('expires_at', models.DateTimeField(help_text='When the token expires (for cleanup purposes)')),
            ],
            options={
                'ordering': ['-blacklisted_at'],
                'indexes': [models.Index(fields=['jti'], name='user_blackl_jti_2e059c_idx')],
            },
        ),
    ]
