# Generated by Django 5.0.4 on 2026-01-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0025_blacklistedtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="cradleuser",
            name="file_upload_limit_override",
            field=models.PositiveBigIntegerField(
                default=None, help_text="File upload limit in bytes", null=True
            ),
        ),
    ]
