# Generated by Django 5.0.4 on 2026-01-06 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0025_blacklistedtoken"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cradleuser",
            old_name="file_upload_limit",
            new_name="file_upload_limit_override",
        ),
    ]
