# Generated by Django 5.0.4 on 2026-01-06 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0026_rename_file_upload_limit_to_override"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("provider", models.CharField(max_length=64)),
                ("subject", models.CharField(max_length=255)),
                ("issuer", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("email_verified", models.BooleanField(default=False)),
                ("display_name", models.CharField(blank=True, max_length=255, null=True)),
                ("raw_claims", models.JSONField(blank=True, null=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_identities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["provider", "subject", "issuer"], name="user_extern_provider_8d1a1f_idx"),
                    models.Index(fields=["user"], name="user_extern_user_id_3c3e23_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "subject", "issuer"),
                        name="unique_external_identity",
                    )
                ],
            },
        ),
    ]
