# Generated by Django 5.0.4 on 2026-01-08 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0027_externalidentity"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="externalidentity",
            new_name="user_extern_provide_c13c50_idx",
            old_name="user_extern_provider_8d1a1f_idx",
        ),
        migrations.RenameIndex(
            model_name="externalidentity",
            new_name="user_extern_user_id_753142_idx",
            old_name="user_extern_user_id_3c3e23_idx",
        ),
    ]
