# Generated by Django 5.0.4 on 2025-09-05

import json

from django.db import migrations, models

THEME_DARK_VARS = {
    "--background": "oklch(0.145 0 0)",
    "--foreground": "oklch(0.985 0 0)",
    "--card": "oklch(0.205 0 0)",
    "--card-foreground": "oklch(0.985 0 0)",
    "--popover": "oklch(0.205 0 0)",
    "--popover-foreground": "oklch(0.985 0 0)",
    "--primary": "oklch(0.922 0 0)",
    "--primary-foreground": "oklch(0.205 0 0)",
    "--secondary": "oklch(0.269 0 0)",
    "--secondary-foreground": "oklch(0.985 0 0)",
    "--muted": "oklch(0.269 0 0)",
    "--muted-foreground": "oklch(0.708 0 0)",
    "--accent": "oklch(0.269 0 0)",
    "--accent-foreground": "oklch(0.985 0 0)",
    "--destructive": "oklch(0.704 0.191 22.216)",
    "--destructive-foreground": "oklch(0.985 0 0)",
    "--border": "oklch(1 0 0 / 10%)",
    "--input": "oklch(1 0 0 / 15%)",
    "--ring": "oklch(0.556 0 0)",
    "--chart-1": "oklch(0.488 0.243 264.376)",
    "--chart-2": "oklch(0.696 0.17 162.48)",
    "--chart-3": "oklch(0.769 0.188 70.08)",
    "--chart-4": "oklch(0.627 0.265 303.9)",
    "--chart-5": "oklch(0.645 0.246 16.439)",
    "--sidebar": "oklch(0.205 0 0)",
    "--sidebar-foreground": "oklch(0.985 0 0)",
    "--sidebar-primary": "oklch(0.488 0.243 264.376)",
    "--sidebar-primary-foreground": "oklch(0.985 0 0)",
    "--sidebar-accent": "oklch(0.269 0 0)",
    "--sidebar-accent-foreground": "oklch(0.985 0 0)",
    "--sidebar-border": "oklch(1 0 0 / 10%)",
    "--sidebar-ring": "oklch(0.556 0 0)",
    "--font-sans": "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
    "--font-serif": "ui-serif, Georgia, Cambria, 'Times New Roman', Times, serif",
    "--font-mono": "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
    "--radius": "0.625rem",
    "--shadow-x": "0",
    "--shadow-y": "1px",
    "--shadow-blur": "3px",
    "--shadow-spread": "0px",
    "--shadow-opacity": "0.1",
    "--shadow-color": "oklch(0 0 0)",
    "--shadow-2xs": "0 1px 3px 0px hsl(0 0% 0% / 0.05)",
    "--shadow-xs": "0 1px 3px 0px hsl(0 0% 0% / 0.05)",
    "--shadow-sm": "0 1px 3px 0px hsl(0 0% 0% / 0.1), 0 1px 2px -1px hsl(0 0% 0% / 0.1)",
    "--shadow": "0 1px 3px 0px hsl(0 0% 0% / 0.1), 0 1px 2px -1px hsl(0 0% 0% / 0.1)",
    "--shadow-md": "0 1px 3px 0px hsl(0 0% 0% / 0.1), 0 2px 4px -1px hsl(0 0% 0% / 0.1)",
    "--shadow-lg": "0 1px 3px 0px hsl(0 0% 0% / 0.1), 0 4px 6px -1px hsl(0 0% 0% / 0.1)",
    "--shadow-xl": "0 1px 3px 0px hsl(0 0% 0% / 0.1), 0 8px 10px -1px hsl(0 0% 0% / 0.1)",
    "--shadow-2xl": "0 1px 3px 0px hsl(0 0% 0% / 0.25)",
}

DEFAULT_THEME = {
    "mode": "dark",
    "vars": THEME_DARK_VARS,
}


def normalize_theme(value: object) -> dict:
    if isinstance(value, str):
        if value in {"dark", "light"}:
            if value == "light":
                return {"mode": "light"}
            return DEFAULT_THEME
        try:
            parsed = json.loads(value)
        except json.JSONDecodeError:
            return DEFAULT_THEME
        if isinstance(parsed, dict):
            return parsed
        return DEFAULT_THEME
    if isinstance(value, dict):
        return value
    return DEFAULT_THEME


def forwards(apps, schema_editor):
    CradleUser = apps.get_model("user", "CradleUser")
    for user in CradleUser.objects.all().only("id", "theme"):
        user.theme = json.dumps(normalize_theme(user.theme))
        user.save(update_fields=["theme"])


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0028_rename_user_extern_provider_8d1a1f_idx_user_extern_provide_c13c50_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="cradleuser",
            name="theme",
            field=models.JSONField(
                default=DEFAULT_THEME,
                help_text="Theme settings to use in the UI",
            ),
        ),
    ]
