# Generated by Django 5.0.4 on 2026-01-19 20:27

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_add_theme_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cradleuser',
            name='theme',
            field=models.JSONField(default=user.models.default_theme, help_text='Theme settings to use in the UI'),
        ),
    ]
