# Generated by Django 6.0.2 on 2026-03-03 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_alter_cradleuser_theme'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='blacklistedtoken',
            name='user_blackl_jti_2e059c_idx',
        ),
        migrations.RemoveIndex(
            model_name='externalidentity',
            name='user_extern_provide_c13c50_idx',
        ),
        migrations.RemoveIndex(
            model_name='usersession',
            name='user_userse_refresh_fb6508_idx',
        ),
        migrations.AlterField(
            model_name='blacklistedtoken',
            name='jti',
            field=models.CharField(help_text='JWT ID of the blacklisted token', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='cradleuser',
            name='api_key',
            field=models.CharField(blank=True, help_text='API key for programmatic access', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='cradleuser',
            name='catalyst_api_key',
            field=models.TextField(blank=True, help_text='API key for Catalyst integration', null=True),
        ),
        migrations.AlterField(
            model_name='cradleuser',
            name='email',
            field=models.EmailField(help_text='User email address (used for login)', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='cradleuser',
            name='email_confirmation_token',
            field=models.TextField(blank=True, help_text='Token for email confirmation', null=True),
        ),
        migrations.AlterField(
            model_name='cradleuser',
            name='email_confirmation_token_expiry',
            field=models.DateTimeField(blank=True, help_text='When the email confirmation token expires', null=True),
        ),
        migrations.AlterField(
            model_name='cradleuser',
            name='email_confirmed',
            field=models.BooleanField(default=False, help_text='Whether the email address has been verified'),
        ),
        migrations.AlterField(
            model_name='cradleuser',
            name='file_upload_limit_override',
            field=models.PositiveBigIntegerField(help_text='File upload limit in bytes', null=True),
        ),
        migrations.AlterField(
            model_name='cradleuser',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Whether the user can log in'),
        ),
        migrations.AlterField(
            model_name='cradleuser',
            name='password_reset_token',
            field=models.TextField(blank=True, help_text='Token for password reset flow', null=True),
        ),
        migrations.AlterField(
            model_name='cradleuser',
            name='password_reset_token_expiry',
            field=models.DateTimeField(blank=True, help_text='When the password reset token expires', null=True),
        ),
        migrations.AlterField(
            model_name='cradleuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('entrymanager', 'Entry Manager'), ('author', 'User')], default='author', help_text='User role for access control', max_length=32),
        ),
        migrations.AlterField(
            model_name='cradleuser',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text='Whether 2FA is enabled for this account'),
        ),
        migrations.AlterField(
            model_name='externalidentity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the identity was linked'),
        ),
        migrations.AlterField(
            model_name='externalidentity',
            name='display_name',
            field=models.CharField(blank=True, help_text='Display name from the provider', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='externalidentity',
            name='email',
            field=models.EmailField(blank=True, help_text='Email from the identity provider', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='externalidentity',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Whether the provider verified this email'),
        ),
        migrations.AlterField(
            model_name='externalidentity',
            name='issuer',
            field=models.CharField(blank=True, help_text='OIDC issuer URL when applicable', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='externalidentity',
            name='last_login_at',
            field=models.DateTimeField(blank=True, help_text='Last login via this identity', null=True),
        ),
        migrations.AlterField(
            model_name='externalidentity',
            name='provider',
            field=models.CharField(help_text='OAuth/OIDC provider name (e.g. google, github)', max_length=64),
        ),
        migrations.AlterField(
            model_name='externalidentity',
            name='raw_claims',
            field=models.JSONField(blank=True, help_text='Raw OAuth/OIDC claims from the provider', null=True),
        ),
        migrations.AlterField(
            model_name='externalidentity',
            name='subject',
            field=models.CharField(help_text="Provider's unique identifier for this user", max_length=255),
        ),
        migrations.AlterField(
            model_name='externalidentity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AlterField(
            model_name='externalidentity',
            name='user',
            field=models.ForeignKey(help_text='Cradle user this identity is linked to', on_delete=django.db.models.deletion.CASCADE, related_name='external_identities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='refresh_token_jti',
            field=models.CharField(help_text='JWT ID of the refresh token', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(help_text='User this session belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
