# Generated by Django 6.0.8 on 2026-10-07 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0033_merge_entrymanager_into_manager"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cradleuser",
            name="catalyst_api_key",
        ),
    ]
