# Generated by Django 5.0.4 on 2025-03-24 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_transfer", "0002_initial"),
        ("intelio", "0001_initial"),
        ("publish", "0008_remove_publishedreport_report_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="filereference",
            name="digest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="intelio.basedigest",
            ),
        ),
        migrations.AddField(
            model_name="filereference",
            name="report",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="file",
                to="publish.publishedreport",
            ),
        ),
    ]
