# Generated by Django 5.0.4 on 2025-03-18 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_transfer", "0002_initial"),
        ("publish", "0006_alter_publishedreport_report_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="filereference",
            name="report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="publish.publishedreport",
            ),
        ),
    ]
