# Generated by Django 5.0.4 on 2025-03-24 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_transfer", "0003_filereference_report"),
        ("publish", "0007_alter_publishedreport_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filereference",
            name="report",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="file",
                to="publish.publishedreport",
            ),
        ),
    ]
