# Generated by Django 5.0.4 on 2025-05-19 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "file_transfer",
            "0004_filereference_md5_hash_filereference_mimetype_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filereference",
            name="fleeting_note",
        ),
    ]
