# Generated by Django 5.0.4 on 2025-05-19 15:43

from django.db import migrations
from django.db import transaction


def move_fleetingnotes_to_notes(apps, schema_editor):
    FleetingNote = apps.get_model("fleeting_notes", "FleetingNote")
    Note = apps.get_model("notes", "Note")

    for i in FleetingNote.objects.all():
        # Create a new Note instance with the same fields as FleetingNote
        note = Note.objects.create(
            author=i.user,
            editor=i.user,
            timestamp=i.last_edited,
            edit_timestamp=i.last_edited,
            content=i.content,
            fleeting=True,
        )

        note.save()
        note.files.set(i.files.all())


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        (
            "file_transfer",
            "0004_filereference_md5_hash_filereference_mimetype_and_more",
        ),
        (
            "notes",
            "0020_note_fleeting",
        ),
    ]

    operations = [
        migrations.RunPython(
            move_fleetingnotes_to_notes, reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name="filereference",
            name="fleeting_note",
        ),
    ]
