# Generated by Django 5.0.4 on 2025-12-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_transfer', '0006_filereference_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='filereference',
            name='file_size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
