# Generated by Django 5.0.4 on 2025-12-22 18:21

import file_transfer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_transfer', '0007_filereference_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='filereference',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=file_transfer.models.file_upload_path),
        ),
        migrations.AlterField(
            model_name='filereference',
            name='bucket_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filereference',
            name='file_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filereference',
            name='minio_file_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
