# Generated by Django 5.0.4 on 2025-12-22

from django.db import migrations, transaction
from django.forms.models import model_to_dict


def migrate_files_to_single_bucket(apps, schema_editor):
    FileReference = apps.get_model('file_transfer', 'FileReference')
    CradleUser = apps.get_model('user', 'CradleUser')

    from file_transfer.utils import MinioClient
    from file_transfer.storage import FileTransferStorage

    minio_client = MinioClient()
    target_bucket = FileTransferStorage.bucket_name

    if not minio_client.client.bucket_exists(target_bucket):
        minio_client.client.make_bucket(target_bucket)

    # Cast to list immediately to avoid cursor issues during deletion
    files_to_migrate = list(FileReference.objects.filter(bucket_name__isnull=False).exclude(bucket_name=''))

    for file_ref in files_to_migrate:
        try:
            with transaction.atomic():
                old_id = file_ref.id
                new_id = "-".join(file_ref.minio_file_name.split("-")[:5])
                
                if not new_id or FileReference.objects.filter(id=new_id).exists():
                    print(f"Skipping {file_ref.id}: New ID '{new_id}' is invalid or already exists.")
                    continue

                user = None
                try:
                    user = CradleUser.objects.get(id=file_ref.bucket_name)
                except CradleUser.DoesNotExist:
                    pass

                new_file_path = f"{new_id}-{file_ref.file_name}"
                if file_ref.minio_file_name and minio_client.file_exists_at_path(file_ref.bucket_name, file_ref.minio_file_name):
                    from minio.commonconfig import CopySource
                    copy_source = CopySource(file_ref.bucket_name, file_ref.minio_file_name)
                    minio_client.client.copy_object(target_bucket, new_file_path, copy_source)
                else:
                    print(f"File missing in MinIO for {file_ref.id}, skipping DB record swap.")
                    continue

                data = model_to_dict(file_ref, exclude=['id', 'file'])
        
                data.update({
                    "id": new_id,
                    "user": user,
                    "file": new_file_path,
                    "bucket_name": "", 
                })

                file_ref.delete()
                FileReference.objects.bulk_create([FileReference(**data)])

                print(f"Success: Migrated {old_id} -> {new_id}")

        except Exception as e:
            print(f"Error migrating file {file_ref.id}: {str(e)}")

def reverse_migration(apps, schema_editor):
    """
    Reverse migration is not fully supported as it would require
    moving files back to user buckets which may not exist.
    This just clears the file field.
    """
    FileReference = apps.get_model('file_transfer', 'FileReference')
    FileReference.objects.update(file='', user=None)


class Migration(migrations.Migration):

    dependencies = [
        ('file_transfer', '0009_filereference_user'),
    ]

    operations = [
        migrations.RunPython(migrate_files_to_single_bucket, reverse_migration),
    ]
