# Generated by Django 5.0.4 on 2025-12-22

from django.db import migrations


def migrate_files_to_single_bucket(apps, schema_editor):
    """
    Migrate files from per-user buckets to a single bucket.

    This migration:
    1. Looks up the user from bucket_name (user's UUID)
    2. Sets the user FK on the FileReference
    3. Copies the file from old bucket to new single bucket
    4. Updates the file field to point to the new location
    """
    FileReference = apps.get_model('file_transfer', 'FileReference')
    CradleUser = apps.get_model('user', 'CradleUser')

    # Import MinioClient and storage here to avoid issues during migration
    from file_transfer.utils import MinioClient
    from file_transfer.storage import FileTransferStorage

    minio_client = MinioClient()
    target_bucket = FileTransferStorage.bucket_name

    # Ensure target bucket exists
    try:
        if not minio_client.client.bucket_exists(target_bucket):
            minio_client.client.make_bucket(target_bucket)
    except Exception as e:
        print(f"Warning: Could not create bucket {target_bucket}: {e}")

    for file_ref in FileReference.objects.filter(bucket_name__isnull=False).exclude(bucket_name=''):
        try:
            # Look up the user from the bucket_name (which is the user's UUID)
            try:
                user = CradleUser.objects.get(id=file_ref.bucket_name)
                file_ref.user = user
            except CradleUser.DoesNotExist:
                print(f"Warning: User with ID {file_ref.bucket_name} not found for file {file_ref.id}")

            # Generate new file path
            new_file_path = f"{file_ref.id}-{file_ref.file_name}"

            # Copy file from old bucket to new bucket
            if file_ref.minio_file_name and minio_client.file_exists_at_path(file_ref.bucket_name, file_ref.minio_file_name):
                from minio.commonconfig import CopySource

                copy_source = CopySource(file_ref.bucket_name, file_ref.minio_file_name)
                minio_client.client.copy_object(
                    target_bucket,
                    new_file_path,
                    copy_source,
                )

                # Update the file field to point to the new location
                file_ref.file = new_file_path
                print(f"Migrated file {file_ref.id}: {file_ref.bucket_name}/{file_ref.minio_file_name} -> {target_bucket}/{new_file_path}")
            else:
                print(f"Warning: File not found in MinIO for {file_ref.id}: {file_ref.bucket_name}/{file_ref.minio_file_name}")

            file_ref.save()

        except Exception as e:
            print(f"Error migrating file {file_ref.id}: {e}")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration is not fully supported as it would require
    moving files back to user buckets which may not exist.
    This just clears the file field.
    """
    FileReference = apps.get_model('file_transfer', 'FileReference')
    FileReference.objects.update(file='', user=None)


class Migration(migrations.Migration):

    dependencies = [
        ('file_transfer', '0009_filereference_user'),
    ]

    operations = [
        migrations.RunPython(migrate_files_to_single_bucket, reverse_migration),
    ]
