# Generated by Django 5.0.4 on 2025-12-22 18:27

import file_transfer.models
import file_transfer.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_transfer', '0010_migrate_files_to_single_bucket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filereference',
            name='file',
            field=models.FileField(blank=True, null=True, storage=file_transfer.storage.FileTransferStorage, upload_to=file_transfer.models.file_upload_path),
        ),
    ]
