# Generated by Django 5.0.4 on 2025-12-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_transfer', '0012_add_pending_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filereference',
            name='bucket_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='filereference',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='filereference',
            name='minio_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
