# Generated by Django 5.0.4 on 2026-01-06 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_transfer', '0013_alter_filereference_bucket_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pendingupload',
            name='file_transf_expires_49a2d8_idx',
        ),
        migrations.RemoveField(
            model_name='filereference',
            name='report',
        ),
        migrations.AlterField(
            model_name='pendingupload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='pendingupload',
            table='file_transfer_pendingupload',
        ),
    ]
