# Generated by Django 6.0.2 on 2026-03-03 13:28

import django.db.models.deletion
import file_transfer.models
import file_transfer.storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_transfer', '0014_remove_pendingupload_file_transf_expires_49a2d8_idx_and_more'),
        ('intelio', '0027_alter_basedigest_digest_type_and_more'),
        ('notes', '0029_alter_archivednote_content_alter_archivednote_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='filereference',
            name='bucket_name',
            field=models.CharField(blank=True, help_text='Legacy: bucket name from old MinIO storage', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='filereference',
            name='digest',
            field=models.ForeignKey(blank=True, help_text='Digest this file belongs to, if any', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='intelio.basedigest'),
        ),
        migrations.AlterField(
            model_name='filereference',
            name='file',
            field=models.FileField(blank=True, help_text='Reference to the file in S3/MinIO storage', null=True, storage=file_transfer.storage.FileTransferStorage, upload_to=file_transfer.models.file_upload_path),
        ),
        migrations.AlterField(
            model_name='filereference',
            name='file_name',
            field=models.CharField(blank=True, help_text='Original filename for display and download', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='filereference',
            name='file_size',
            field=models.PositiveBigIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AlterField(
            model_name='filereference',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the file reference', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='filereference',
            name='md5_hash',
            field=models.CharField(blank=True, help_text='MD5 hash of file contents', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='filereference',
            name='mimetype',
            field=models.CharField(blank=True, help_text='MIME type detected from file content', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='filereference',
            name='minio_file_name',
            field=models.CharField(blank=True, help_text='Legacy: object key from old MinIO storage', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='filereference',
            name='note',
            field=models.ForeignKey(blank=True, help_text='Note this file is attached to, if any', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='notes.note'),
        ),
        migrations.AlterField(
            model_name='filereference',
            name='sha1_hash',
            field=models.CharField(blank=True, help_text='SHA-1 hash of file contents', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='filereference',
            name='sha256_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of file contents', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='filereference',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='When the file was first uploaded'),
        ),
        migrations.AlterField(
            model_name='filereference',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who uploaded the file', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pendingupload',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the upload was initiated'),
        ),
        migrations.AlterField(
            model_name='pendingupload',
            name='expires_at',
            field=models.DateTimeField(help_text='When the presigned URL expires and the upload session becomes invalid'),
        ),
        migrations.AlterField(
            model_name='pendingupload',
            name='file_name',
            field=models.CharField(help_text='Original filename provided by the user', max_length=255),
        ),
        migrations.AlterField(
            model_name='pendingupload',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique upload session identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pendingupload',
            name='object_key',
            field=models.CharField(help_text='S3 object key where the file will be stored', max_length=512),
        ),
        migrations.AlterField(
            model_name='pendingupload',
            name='user',
            field=models.ForeignKey(help_text='User who initiated the upload', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
