# Generated by Django 6.0.4 on 2026-05-14 22:04

import file_transfer.models
import file_transfer.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_transfer', '0015_alter_filereference_bucket_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filereference',
            name='file',
            field=models.FileField(blank=True, help_text='Reference to the file in S3/MinIO storage', max_length=512, null=True, storage=file_transfer.storage.FileTransferStorage, upload_to=file_transfer.models.file_upload_path),
        ),
    ]
