import { useDroppable } from '@dnd-kit/core';
import { Download } from 'iconoir-react';
import { useCallback, useEffect, useRef, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import useApi from '@/hooks/api/useApi';
import type { FileReferenceWithNote } from '@/services/cradle/models';
import type { Alert, StateSetter } from '@/types';
import { truncateText } from '@/utils/dashboard';
import { formatDate } from '@/utils/dates';
import AlertBox from '@components/base/Alert/AlertBox';
import ListView from '@components/base/ListView/ListView';
import PaginationWrapper from '@components/base/Pagination/PaginationWrapper';
import TableCard from '@components/base/Card/TableCard';

interface FilesListQuery {
    date?: string;
    keyword?: string;
    linked_to?: string;
    linked_to_exact_match?: boolean;
    mimetype?: string;
    references?: string;
    timestamp_gte?: string;
    timestamp_lte?: string;
}

/**
 * FilesList component - This component is used to display a list of files.
 * @param query - Query parameters for filtering files
 * @param filteredFiles - Files to filter out from the results
 * @param fileActions - Actions that can be performed on files
 * @param references - References for drag and drop functionality
 * @param setAlert - Function to set alerts (optional)
 * @param onError - Error handler function (optional)
 */
interface FilesListProps {
    query?: FilesListQuery;
    filteredFiles?: FileReferenceWithNote[];
    fileActions?: any[];
    references?: any;
    setAlert?: StateSetter<Alert> | null;
    onError?: ((error: any) => void) | null;
}

export default function FilesList({
    query = {},
    filteredFiles = [],
    fileActions = [],
    references = null,
    setAlert: externalSetAlert = null,
    onError = null,
}: FilesListProps) {
    const [searchParams, setSearchParams] = useSearchParams();
    const [files, setFiles] = useState<FileReferenceWithNote[]>([]);
    const [alert, setInternalAlert] = useState<Alert>({
        show: false,
        message: '',
        color: 'red',
    });

    // Use external setAlert if provided, otherwise use internal
    const setAlert = externalSetAlert || setInternalAlert;
    const [loading, setLoading] = useState(false);
    const [totalPages, setTotalPages] = useState(1);
    const [page, setPage] = useState(Number(searchParams.get('files_page')) || 1);
    const [sortField, setSortField] = useState(searchParams.get('files_sort_field') || 'timestamp');
    const [sortDirection, setSortDirection] = useState<'asc' | 'desc'>((searchParams.get('files_sort_direction') as 'asc' | 'desc') || 'desc');
    const [pageSize, setPageSize] = useState(Number(searchParams.get('files_pagesize')) || 10);
    const [selectedFiles, setSelectedFiles] = useState<string[]>([]);
    const [isDropdownOpen, setIsDropdownOpen] = useState(false);
    const dropdownRef = useRef<HTMLDivElement>(null);
    const { notesApi, fileTransferApi } = useApi();

    // Mapping of table columns to API field names
    const sortFieldMapping: Record<string, string> = {
        name: 'file_name',
        uploadedAt: 'timestamp',
        mimetype: 'mimetype',
    };

    const { setNodeRef } = useDroppable({
        id: 'files-droppable',
    });

    const handleSort = (field: string, direction: 'asc' | 'desc') => {
        setSortField(field);
        setSortDirection(direction);

        // Reset to first page when sorting changes
        setPage(1);
        const newParams = new URLSearchParams(searchParams);
        newParams.set('files_page', '1');
        newParams.set('files_sort_field', field);
        newParams.set('files_sort_direction', direction);
        setSearchParams(newParams, { replace: true });
    };

    const fetchFiles = useCallback(async () => {
        setLoading(true);

        try {
            const orderBy = sortDirection === 'desc' ? `-${sortField}` : sortField;

            // Map snake_case to camelCase for the autogenerated API
            const params: any = {
                page,
                pageSize: pageSize,
                orderBy: orderBy,
                date: query.date,
                keyword: query.keyword,
                linkedTo: query.linked_to,
                linkedToExactMatch: query.linked_to_exact_match,
                mimetype: query.mimetype,
                references: query.references,
                timestampGte: query.timestamp_gte,
                timestampLte: query.timestamp_lte,
            };

            // Remove undefined values
            Object.keys(params).forEach(key => params[key] === undefined && delete params[key]);

            const response = await notesApi.notesFilesRetrieve(params);
            setFiles(response.results);
            setTotalPages(response.totalPages);
            setLoading(false);
        } catch (error) {
            if (onError) {
                onError(error);
            } else {
                setAlert({
                    show: true,
                    message: 'Failed to fetch files. Please try again.',
                    color: 'red',
                });
            }
            setLoading(false);
        }
    }, [page, pageSize, sortField, sortDirection, query, notesApi]);

    const copyToClipboard = (text: string) => {
        navigator.clipboard
            .writeText(text)
            .catch((error) => {
                console.error('Failed to copy text: ', error);
            })
            .then(() => {
                setAlert({
                    show: true,
                    message: 'Copied to clipboard',
                    color: 'green',
                });
            });
    };

    // Download a single file
    const handleDownloadFile = async (file: FileReferenceWithNote) => {
        if (!file.bucketName || !file.minioFileName) {
            setAlert({
                show: true,
                message: 'File download information is missing.',
                color: 'red',
            });
            return;
        }

        try {
            const response = await fileTransferApi.fileTransferDownloadRetrieve({
                bucketName: file.bucketName,
                minioFileName: file.minioFileName,
            });
        } catch (error) {
            setAlert({
                show: true,
                message: 'Failed to download file. Please try again.',
                color: 'red',
            });
        }
    };

    // Download selected files
    const handleDownloadSelected = async () => {
        if (selectedFiles.length === 0) return;

        try {
            for (const fileId of selectedFiles) {
                const file = files.find(f => f.id === fileId);
                if (file && file.bucketName && file.minioFileName) {
                    const response = await fileTransferApi.fileTransferDownloadRetrieve({
                        bucketName: file.bucketName,
                        minioFileName: file.minioFileName,
                    });
                    const { presigned } = response;
                    const link = document.createElement('a');
                    link.href = presigned;
                    const fileName = file.minioFileName.split('/').pop() || file.minioFileName;
                    link.download = fileName;
                    document.body.appendChild(link);
                    link.click();
                    document.body.removeChild(link);
                }
            }
            setAlert({
                show: true,
                message: `Downloaded ${selectedFiles.length} file(s)`,
                color: 'green',
            });
        } catch (error) {
            setAlert({
                show: true,
                message: 'Failed to download files. Please try again.',
                color: 'red',
            });
        }
        setIsDropdownOpen(false);
    };

    // Close dropdown when clicking outside
    useEffect(() => {
        const handleClickOutside = (event: MouseEvent) => {
            if (dropdownRef.current && !dropdownRef.current.contains(event.target as Node)) {
                setIsDropdownOpen(false);
            }
        };

        document.addEventListener('mousedown', handleClickOutside);
        return () => {
            document.removeEventListener('mousedown', handleClickOutside);
        };
    }, []);

    useEffect(() => {
        setPage(Number(searchParams.get('files_page')) || 1);
        fetchFiles();
    }, [pageSize]);

    const handlePageChange = (newPage: number) => {
        const newParams = new URLSearchParams(searchParams);
        newParams.set('files_page', String(newPage));
        setSearchParams(newParams);

        setPage(newPage);
    };

    const columns = [
        { key: 'name', label: 'Name', className: 'w-64' },
        { key: 'entities', label: 'Entities', className: 'w-32' },
        { key: 'mimetype', label: 'MimeType', className: 'w-32' },
        { key: 'sha256', label: 'SHA256', className: 'w-48' },
        { key: 'uploadedAt', label: 'Uploaded At', className: 'w-32' },
        { key: 'actions', label: '', className: 'w-4' },
    ];

    interface SelectProps {
        enableMultiSelect?: boolean;
        isSelected?: boolean;
        onSelect?: () => void;
    }

    const renderRow = (file: FileReferenceWithNote, index: number, selectProps: SelectProps = {}) => {
        for (const f of filteredFiles) {
            if (f.id === file.id) return null;
        }

        const { enableMultiSelect, isSelected, onSelect } = selectProps;

        return (
            <tr key={file.id || index}>
                {enableMultiSelect && (
                    <td className='w-12' onClick={(e) => e.stopPropagation()}>
                        <div className='flex items-center'>
                            <input
                                type='checkbox'
                                className='cradle-checkbox'
                                checked={isSelected}
                                onChange={onSelect}
                            />
                        </div>
                    </td>
                )}
                <td className='truncate w-32'>
                    {truncateText(file.fileName, 32)}
                </td>
                <td className=''>
                    <div className='flex flex-wrap gap-1'>
                        {file.entities?.slice(0, 3).map((entity) => (
                            <span
                                key={entity.name}
                                className='badge badge-xs px-1 text-white'
                                style={{
                                    backgroundColor: entity.color || '#ccc',
                                    borderColor: entity.color || '#ccc',
                                }}
                            >
                                {entity.name}
                            </span>
                        ))}
                    </div>
                </td>
                <td className='truncate w-32'>
                    {truncateText(file.mimetype, 32)}
                </td>
                <td className='w-48'>
                    {file.sha256Hash ? (
                        <span
                            className='cursor-pointer hover:bg-zinc-400 hover:dark:bg-zinc-800 px-1 rounded truncate block'
                            onClick={() => copyToClipboard(file.sha256Hash!)}
                            title='Click to copy'
                        >
                            {file.sha256Hash!.substring(0, 21)}...
                        </span>
                    ) : (
                        '-'
                    )}
                </td>
                <td className=''>
                    {file.timestamp ? formatDate(file.timestamp) : '-'}
                </td>
                <td className='w-4 action'>
                    <button
                        onClick={(e) => {
                            e.stopPropagation();
                            handleDownloadFile(file);
                        }}
                        className='cursor-pointer rounded flex items-center justify-center p-0.5'
                        title='Download file'
                    >
                        <Download className='w-4' />
                    </button>
                </td>
            </tr>
        );
    };

    return (
        <>
            <div className='flex flex-col space-y-4'>
                <AlertBox alert={alert} />

                {/* Compact Control Bar - Actions and Pagination */}
                {!loading && (
                    <TableCard>
                        <div className='flex flex-wrap items-center justify-between gap-4'>
                            {/* Left: Actions Dropdown */}
                            <div className='flex items-center gap-4 flex-shrink-0'>
                                <div className={`${files.length === 0 ? 'opacity-50 pointer-events-none' : ''}`}>
                                    <div className="cradle-dropdown" ref={dropdownRef}>
                                        <button
                                            type="button"
                                            className={`cradle-select text-sm flex items-center justify-between gap-2 min-w-[120px] ${selectedFiles.length > 0 ? 'opacity-100 cursor-pointer' : 'opacity-50 cursor-not-allowed'}`}
                                            disabled={selectedFiles.length === 0}
                                            title={selectedFiles.length > 0 ? `${selectedFiles.length} file(s) selected` : "Select files to perform actions"}
                                            onClick={() => setIsDropdownOpen(!isDropdownOpen)}
                                        >
                                            <span className="truncate">
                                                {selectedFiles.length > 0 ? `${selectedFiles.length} selected` : 'Actions'}
                                            </span>
                                            <svg className={`w-4 h-4 transition-transform ${isDropdownOpen ? 'rotate-180' : ''}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 9l-7 7-7-7"></path>
                                            </svg>
                                        </button>

                                        {isDropdownOpen && selectedFiles.length > 0 && (
                                            <div className="cradle-dropdown-menu">
                                                <button
                                                    type="button"
                                                    className="cradle-dropdown-option flex items-center gap-2"
                                                    onClick={handleDownloadSelected}
                                                >
                                                    <Download className="w-4 h-4" />
                                                    Download
                                                </button>
                                            </div>
                                        )}
                                    </div>
                                </div>
                            </div>

                            {/* Right: Pagination */}
                            <PaginationWrapper
                                currentPage={page}
                                totalPages={totalPages}
                                onPageChange={handlePageChange}
                                pageSize={pageSize}
                                onPageSizeChange={(newSize) => {
                                    setPageSize(newSize);
                                    setPage(1);
                                    const newParams = new URLSearchParams(searchParams);
                                    newParams.set('files_page', '1');
                                    newParams.set('files_pagesize', String(newSize));
                                    setSearchParams(newParams, { replace: true });
                                }}
                                disabled={files.length === 0}
                            />
                        </div>
                    </TableCard>
                )}

                <div ref={setNodeRef} className='grid grid-cols-1 gap-2'>
                    <ListView
                        data={files}
                        columns={columns}
                        renderRow={renderRow}
                        loading={loading}
                        sortField={sortField}
                        sortDirection={sortDirection}
                        onSort={handleSort}
                        sortFieldMapping={sortFieldMapping}
                        emptyMessage="No files found!"
                        tableClassName="table"
                        enableMultiSelect={true}
                        setSelected={setSelectedFiles}
                    />
                </div>
            </div>
        </>
    );
}
