# Generated by Django 5.0.4 on 2024-07-03 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("file_transfer", "0001_initial"),
        ("fleeting_notes", "0001_initial"),
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filereference",
            name="fleeting_note",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="fleeting_notes.fleetingnote",
            ),
        ),
        migrations.AddField(
            model_name="filereference",
            name="note",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="notes.note",
            ),
        ),
    ]
