# vi: ft=dockerfile

FROM oven/bun:1-alpine AS builder

WORKDIR /ui

COPY ./ui/package.json ./ui/bun.lock ./ui/bunfig.toml ./
RUN bun install --frozen-lockfile

COPY ./ui ./

ARG GIT_BRANCH=""
ARG GIT_COMMIT=""
ARG VITE_API_BASE_URL="/api"
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
RUN bun run build

FROM alpine:3.23

RUN apk add --no-cache nginx \
    && adduser -D -g 'www' www \
    && mkdir -p /www \
    && chown -R www:www /var/lib/nginx

COPY --from=builder /ui/dist/client /cradle

COPY --chmod=755 ./docker/entrypoint_ui.sh /entrypoint_ui.sh

CMD ["/entrypoint_ui.sh"]
