services:
  postgres:
    image: postgres:16.8
    container_name: cradle_postgres
    environment:
     - POSTGRES_DB=cradle
     - POSTGRES_USER=cradle
     - POSTGRES_PASSWORD=cradle
    volumes:
    - pg_data:/var/lib/postgresql/data
    networks:
      default:
        ipv4_address: 192.168.31.40

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: cradle_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cradle.sh
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      default:
        ipv4_address: 192.168.31.43

  rabbitmq:
    image: rabbitmq:3-management
    container_name: cradle_rabbitmq
    ports:
      - "5672:5672"     # AMQP port
      - "15672:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: cradle
      RABBITMQ_DEFAULT_PASS: cradle
    networks:
      default:
        ipv4_address: 192.168.31.44

  minio:
    image: quay.io/minio/minio:RELEASE.2024-05-28T17-19-04Z
    command: server --console-address ":9001" /data
    container_name: cradle_minio
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: minio_admin
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      default:
        ipv4_address: 192.168.31.41

  redis:
    image: "redis:alpine"
    networks:
      default:
        ipv4_address: 192.168.31.42

volumes:
  pg_data:
  minio_data:

networks:
  other:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.31.32/27
