# vi: ft=dockerfile

FROM node:23-alpine3.20

RUN apk update
RUN apk add nginx curl bash

RUN adduser -D -g 'www' www

RUN mkdir /www
RUN chown -R www:www /var/lib/nginx
RUN chown -R www:www /www

# Install Bun
RUN curl -fsSL https://bun.sh/install | bash
ENV PATH="/root/.bun/bin:${PATH}"

# Copy application source code
COPY ./ui ui
WORKDIR /ui

RUN bun install

RUN mkdir -p /www
RUN cd /ui

ENV VITE_API_BASE_URL="http://localhost:8000/api"
RUN bun run build

RUN rm -rf /www/cradle
RUN cp -r dist/client /cradle
RUN chown -R www:www /www

WORKDIR /
RUN rm -rf /ui

COPY ./docker/nginx_demo.conf /etc/nginx/nginx.conf
COPY ./docker/entrypoint_ui.sh entrypoint_ui.sh
RUN chmod +x ./entrypoint_ui.sh

CMD ./entrypoint_ui.sh
