# Generated by Django 5.0.4 on 2025-01-13 11:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0005_relation_relation_unique_src_dst_note"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION get_readable_notes(user_uuid UUID)
            RETURNS TABLE (note_id UUID) AS $$
            BEGIN
            RETURN QUERY
                SELECT ne.note_id
                    FROM notes_note_entries AS ne JOIN entries_entry ee ON ne.entry_id = ee.id
                    JOIN entries_entryclass ec ON ee.entry_class_id = ec.subtype
                    RIGHT JOIN (SELECT * FROM access_access WHERE user_id = user_uuid AND access_type <> 'none') a ON ne.entry_id = a.entity_id
                    WHERE ec.type = 'entity'
                    GROUP BY ne.note_id;
            END;
            $$ LANGUAGE plpgsql;
            """
        ),
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION get_related_entry_ids_for_user(target_entry_id UUID, user_id UUID)
            RETURNS TABLE (entry_id UUID) AS $$
            BEGIN
                RETURN QUERY
                SELECT n.dst_entry_id AS entry_id
                FROM notes_relation n
                WHERE n.note_id IN (
                    SELECT ne.note_id
                    FROM notes_note_entries ne
                    WHERE ne.note_id IN (SELECT nen.note_id FROM get_readable_notes(user_id) nen)
                    GROUP BY ne.note_id
                ) AND n.src_entry_id = target_entry_id;
            END;
            $$ LANGUAGE plpgsql;
            """
        ),
    ]
