# Generated by Django 5.0.4 on 2025-04-01 23:56

from django.db import migrations, models


def copy_field_data(apps, schema_editor):
    Access = apps.get_model("access", "Access")
    for obj in Access.objects.all():
        obj.entity_id_back = obj.entity.id
        obj.save(update_fields=["entity_id_back"])


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0003_alter_access_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="access",
            name="entity_id_back",
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(copy_field_data),
    ]
