# Generated by Django 5.0.4 on 2025-04-02 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0004_access_entity_id_back"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="access",
            name="unique_user_id_entity_id",
        ),
        migrations.RemoveField(
            model_name="access",
            name="entity",
        ),
    ]
