# Generated by Django 5.0.4 on 2025-04-02 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_field_data(apps, schema_editor):
    Access = apps.get_model("access", "Access")
    Entry = apps.get_model("entries", "Entry")
    for obj in Access.objects.all():
        obj.entity = Entry.objects.get(id_copy=obj.entity_id_back)
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0005_remove_access_unique_user_id_entity_id_and_more"),
        ("entries", "0037_auto_20250401_2234"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="access",
            name="entity",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="entries.entry",
            ),
        ),
        migrations.AddConstraint(
            model_name="access",
            constraint=models.UniqueConstraint(
                fields=("user", "entity"), name="unique_user_id_entity_id"
            ),
        ),
        migrations.RunPython(copy_field_data),
        migrations.RemoveField(
            model_name="access",
            name="entity_id_back",
        ),
    ]
