# Generated by Django 5.0.4 on 2025-04-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0006_access_entity_access_unique_user_id_entity_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="access",
            name="entity_id_back",
            field=models.UUIDField(null=True),
        ),
    ]
