# Generated by Django 5.0.4 on 2025-10-23 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0007_access_entity_id_back'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access',
            name='entity_id_back',
        ),
    ]
