# Generated by Django 6.0.2 on 2026-03-02 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0008_remove_access_entity_id_back'),
        ('entries', '0060_alter_attachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access', to='entries.entry'),
        ),
    ]
