# Generated by Django 6.0.2 on 2026-03-03 13:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0009_alter_access_entity'),
        ('entries', '0061_alter_attachment_context_alter_attachment_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access',
            options={'verbose_name': 'access', 'verbose_name_plural': 'accesses'},
        ),
        migrations.AlterField(
            model_name='access',
            name='access_type',
            field=models.CharField(choices=[('none', 'No access'), ('read', 'Read access'), ('read-write', 'Read-write access')], default='none', help_text='Permission level: none, read, or read-write', max_length=20),
        ),
        migrations.AlterField(
            model_name='access',
            name='entity',
            field=models.ForeignKey(help_text='Target entity; null when not scoped to a specific entity', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access', to='entries.entry'),
        ),
        migrations.AlterField(
            model_name='access',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this access record', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='access',
            name='user',
            field=models.ForeignKey(help_text='User this access applies to', on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to=settings.AUTH_USER_MODEL),
        ),
    ]
