import { useDroppable } from '@dnd-kit/core';
import { Download } from 'iconoir-react';
import { useCallback, useEffect, useRef, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import useApi from '../../hooks/useApi/useApi';
import { truncateText } from '../../utils/dashboardUtils/dashboardUtils';
import { formatDate } from '../../utils/dateUtils/dateUtils';
import AlertBox from '../AlertBox/AlertBox';
import FileItem from '../FileItem/FileItem';
import ListView from '../ListView/ListView';
import PaginationWrapper from '../PaginationWrapper/PaginationWrapper';
import TableCard from '../TableCard/TableCard';

/**
 * FilesList component - This component is used to display a list of files.
 * @function FilesList
 * @param {Object} props - Component props
 * @param {Object} props.query - Query parameters for filtering files
 * @param {Array} props.filteredFiles - Files to filter out from the results
 * @param {Array} props.fileActions - Actions that can be performed on files
 * @param {Object} props.references - References for drag and drop functionality
 * @param {Function} props.setAlert - Function to set alerts (optional)
 * @param {Function} props.onError - Error handler function (optional)
 * @returns {JSX.Element}
 */
export default function FilesList({
    query = {},
    filteredFiles = [],
    fileActions = [],
    references = null,
    setAlert: externalSetAlert = null,
    onError = null,
}) {
    const [searchParams, setSearchParams] = useSearchParams();
    const [files, setFiles] = useState([]);
    const [alert, setInternalAlert] = useState({
        show: false,
        message: '',
        color: 'red',
    });

    // Use external setAlert if provided, otherwise use internal
    const setAlert = externalSetAlert || setInternalAlert;
    const [loading, setLoading] = useState(false);
    const [totalPages, setTotalPages] = useState(1);
    const [page, setPage] = useState(Number(searchParams.get('files_page')) || 1);
    const [sortField, setSortField] = useState(searchParams.get('files_sort_field') || 'timestamp');
    const [sortDirection, setSortDirection] = useState(searchParams.get('files_sort_direction') || 'desc');
    const [pageSize, setPageSize] = useState(Number(searchParams.get('files_pagesize')) || 10);
    const [selectedFiles, setSelectedFiles] = useState([]);
    const [isDropdownOpen, setIsDropdownOpen] = useState(false);
    const dropdownRef = useRef(null);
    const { notesApi, fileTransferApi } = useApi();

    // Mapping of table columns to API field names
    const sortFieldMapping = {
        name: 'file_name',
        uploadedAt: 'timestamp',
        mimetype: 'mimetype',
    };

    const { setNodeRef } = useDroppable({
        id: 'files-droppable',
    });

    const handleSort = (field, direction) => {
        setSortField(field);
        setSortDirection(direction);

        // Reset to first page when sorting changes
        setPage(1);
        const newParams = new URLSearchParams(searchParams);
        newParams.set('files_page', '1');
        newParams.set('files_sort_field', field);
        newParams.set('files_sort_direction', direction);
        setSearchParams(newParams, { replace: true });
    };

    const fetchFiles = useCallback(async () => {
        setLoading(true);

        try {
            const orderBy = sortDirection === 'desc' ? `-${sortField}` : sortField;

            // Map snake_case to camelCase for the autogenerated API
            const params = {
                page,
                pageSize: pageSize,
                orderBy: orderBy,
                date: query.date,
                keyword: query.keyword,
                linkedTo: query.linked_to,
                linkedToExactMatch: query.linked_to_exact_match,
                mimetype: query.mimetype,
                references: query.references,
                timestampGte: query.timestamp_gte,
                timestampLte: query.timestamp_lte,
            };

            // Remove undefined values
            Object.keys(params).forEach(key => params[key] === undefined && delete params[key]);

            const response = await notesApi.notesFilesRetrieve(params);
            setFiles(response.results);
            setTotalPages(response.totalPages);
            setLoading(false);
        } catch (error) {
            if (onError) {
                onError(error);
            } else {
                setAlert({
                    show: true,
                    message: 'Failed to fetch files. Please try again.',
                    color: 'red',
                });
            }
            setLoading(false);
        }
    }, [page, pageSize, sortField, sortDirection, query, setAlert, onError, notesApi]);

    const copyToClipboard = (text) => {
        navigator.clipboard
            .writeText(text)
            .catch((error) => {
                console.error('Failed to copy text: ', error);
            })
            .then(() => {
                setAlert({
                    show: true,
                    message: 'Copied to clipboard',
                    color: 'green',
                });
            });
    };

    // Download selected files
    const handleDownloadSelected = async () => {
        if (selectedFiles.length === 0) return;

        try {
            for (const fileId of selectedFiles) {
                const file = files.find(f => f.id === fileId);
                if (file && file.bucket_name && file.minio_file_name) {
                    const response = await fileTransferApi.fileTransferDownloadRetrieve({
                        bucketName: file.bucket_name,
                        minioFileName: file.minio_file_name,
                    });
                    const { presigned } = response;
                    const link = document.createElement('a');
                    link.href = presigned;
                    const fileName = file.minio_file_name.split('/').pop() || file.minio_file_name;
                    link.download = fileName;
                    document.body.appendChild(link);
                    link.click();
                    document.body.removeChild(link);
                }
            }
            setAlert({
                show: true,
                message: `Downloaded ${selectedFiles.length} file(s)`,
                color: 'green',
            });
        } catch (error) {
            setAlert({
                show: true,
                message: 'Failed to download files. Please try again.',
                color: 'red',
            });
        }
        setIsDropdownOpen(false);
    };

    // Close dropdown when clicking outside
    useEffect(() => {
        const handleClickOutside = (event) => {
            if (dropdownRef.current && !dropdownRef.current.contains(event.target)) {
                setIsDropdownOpen(false);
            }
        };

        document.addEventListener('mousedown', handleClickOutside);
        return () => {
            document.removeEventListener('mousedown', handleClickOutside);
        };
    }, []);

    useEffect(() => {
        setPage(Number(searchParams.get('files_page')) || 1);
        fetchFiles();
    }, [fetchFiles, pageSize]);

    const handlePageChange = (newPage) => {
        const newParams = new URLSearchParams(searchParams);
        newParams.set('files_page', newPage);
        setSearchParams(newParams);

        setPage(newPage);
    };

    const columns = [
        { key: 'name', label: 'Name', className: 'w-64' },
        { key: 'entities', label: 'Entities', className: 'w-32' },
        { key: 'mimetype', label: 'MimeType', className: 'w-32' },
        { key: 'sha256', label: 'SHA256', className: 'w-48' },
        { key: 'uploadedAt', label: 'Uploaded At', className: 'w-32' },
    ];

    const renderRow = (file, index, selectProps = {}) => {
        for (const f of filteredFiles) {
            if (f.id === file.id) return null;
        }
        console.log(file);

        const { enableMultiSelect, isSelected, onSelect } = selectProps;

        return (
            <tr key={file.id || index}>
                {enableMultiSelect && (
                    <td className='w-12' onClick={(e) => e.stopPropagation()}>
                        <input
                            type='checkbox'
                            className='cradle-checkbox'
                            checked={isSelected}
                            onChange={onSelect}
                        />
                    </td>
                )}
                <td className='truncate w-32'>
                    {truncateText(file.fileName, 32)}
                </td>
                <td className=''>
                    <div className='flex flex-wrap gap-1'>
                        {file.entities?.slice(0, 3).map((entity) => (
                            <span
                                key={entity.name}
                                className='badge badge-xs px-1 text-white'
                                style={{
                                    backgroundColor: entity.color || '#ccc',
                                }}
                            >
                                {entity.name}
                            </span>
                        ))}
                    </div>
                </td>
                <td className='truncate w-32'>
                    {truncateText(file.mimetype, 32)}
                </td>
                <td className='w-48'>
                    {file.sha256_hash ? (
                        <span
                            className='cursor-pointer hover:bg-zinc-400 hover:dark:bg-zinc-800 px-1 rounded truncate block'
                            onClick={() => copyToClipboard(file.sha256Hash)}
                            title='Click to copy'
                        >
                            {file.sha256Hash.substring(0, 21)}...
                        </span>
                    ) : (
                        '-'
                    )}
                </td>
                <td className=''>
                    {formatDate(new Date(file.timestamp))}
                </td>
            </tr>
        );
    };

    const renderCard = (file, index) => {
        for (const f of filteredFiles) {
            if (f.id === file.id) return null;
        }
        return (
            <FileItem
                id={file.id}
                key={index}
                file={file}
                setAlert={setAlert}
                actions={fileActions}
            />
        );
    };

    return (
        <>
            <div className='flex flex-col space-y-4'>
                <AlertBox alert={alert} setAlert={setAlert} />

                {/* Compact Control Bar - Actions and Pagination */}
                {!loading && (
                    <TableCard>
                        <div className='flex flex-wrap items-center justify-between gap-4'>
                            {/* Left: Actions Dropdown */}
                            <div className='flex items-center gap-4 flex-shrink-0'>
                                <div className={`${files.length === 0 ? 'opacity-50 pointer-events-none' : ''}`}>
                                    <div className="cradle-dropdown" ref={dropdownRef}>
                                        <button
                                            type="button"
                                            className={`cradle-select text-sm flex items-center justify-between gap-2 min-w-[120px] ${selectedFiles.length > 0 ? 'opacity-100 cursor-pointer' : 'opacity-50 cursor-not-allowed'}`}
                                            disabled={selectedFiles.length === 0}
                                            title={selectedFiles.length > 0 ? `${selectedFiles.length} file(s) selected` : "Select files to perform actions"}
                                            onClick={() => setIsDropdownOpen(!isDropdownOpen)}
                                        >
                                            <span className="truncate">
                                                {selectedFiles.length > 0 ? `${selectedFiles.length} selected` : 'Actions'}
                                            </span>
                                            <svg className={`w-4 h-4 transition-transform ${isDropdownOpen ? 'rotate-180' : ''}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 9l-7 7-7-7"></path>
                                            </svg>
                                        </button>

                                        {isDropdownOpen && selectedFiles.length > 0 && (
                                            <div className="cradle-dropdown-menu">
                                                <button
                                                    type="button"
                                                    className="cradle-dropdown-option flex items-center gap-2"
                                                    onClick={handleDownloadSelected}
                                                >
                                                    <Download className="w-4 h-4" />
                                                    Download
                                                </button>
                                            </div>
                                        )}
                                    </div>
                                </div>
                            </div>

                            {/* Right: Pagination */}
                            <PaginationWrapper
                                currentPage={page}
                                totalPages={totalPages}
                                onPageChange={handlePageChange}
                                pageSize={pageSize}
                                onPageSizeChange={(newSize) => {
                                    setPageSize(newSize);
                                    setPage(1);
                                    const newParams = new URLSearchParams(searchParams);
                                    newParams.set('files_page', '1');
                                    newParams.set('files_pagesize', String(newSize));
                                    setSearchParams(newParams, { replace: true });
                                }}
                                disabled={files.length === 0}
                            />
                        </div>
                    </TableCard>
                )}

                <div ref={setNodeRef} className='grid grid-cols-1 gap-2'>
                    <ListView
                        data={files}
                        columns={columns}
                        renderRow={renderRow}
                        renderCard={renderCard}
                        loading={loading}
                        sortField={sortField}
                        sortDirection={sortDirection}
                        onSort={handleSort}
                        sortFieldMapping={sortFieldMapping}
                        emptyMessage="No files found!"
                        tableClassName="table"
                        enableMultiSelect={true}
                        setSelected={setSelectedFiles}
                    />
                </div>
            </div>
        </>
    );
}
