# Generated by Django 5.0.4 on 2025-04-23 18:47

from django.db import migrations


def delete_entry_eventlogs(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    EventLog = apps.get_model("logs", "EventLog")
    Entry = apps.get_model("entries", "Entry")

    entry_ct = ContentType.objects.get_for_model(Entry)
    EventLog.objects.filter(content_type=entry_ct).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0003_alter_eventlog_details"),
    ]

    operations = [
        migrations.RunPython(
            delete_entry_eventlogs, reverse_code=migrations.RunPython.noop
        ),
    ]
