# Generated by Django 6.0.2 on 2026-03-03 13:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('logs', '0004_auto_20250423_1847'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'event log', 'verbose_name_plural': 'event logs'},
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='content_type',
            field=models.ForeignKey(help_text='Type of the content object this log refers to.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='details',
            field=models.CharField(blank=True, help_text='Optional JSON-serialized extra context for the event.', null=True),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the log entry.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='object_id',
            field=models.CharField(help_text='Primary key of the content object.'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='src_log',
            field=models.ForeignKey(blank=True, help_text='Log that triggered this event, for propagated entries.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propagated_logs', to='logs.eventlog'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='When the event was recorded.'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='type',
            field=models.CharField(choices=[('create', 'Create'), ('delete', 'Delete'), ('edit', 'Edit'), ('fetch', 'Fetch'), ('login', 'Login')], help_text='Kind of event (create, edit, delete, fetch, login).'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='user',
            field=models.ForeignKey(help_text='User who performed the action.', on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
