# Generated by Django 5.0.4 on 2025-03-24 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("intelio", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="matrushkaassociation",
            old_name="entities",
            new_name="entity",
        ),
    ]
