# Generated by Django 5.0.4 on 2025-03-26 10:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0026_alter_entry_options"),
        ("intelio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FalconDigest",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("intelio.basedigest",),
        ),
        migrations.CreateModel(
            name="FalconMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("type", models.CharField(max_length=255)),
                (
                    "internal_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="entries.entryclass",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
