# Generated by Django 5.0.4 on 2025-03-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelio", "0002_catalystmapping"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="catalystmapping",
            name="name",
        ),
        migrations.AddField(
            model_name="catalystmapping",
            name="model_class",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="catalystmapping",
            name="subtype",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="catalystmapping",
            name="type",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
