# Generated by Django 5.0.4 on 2025-03-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelio", "0002_falcondigest_falconmapping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="association",
            name="reason",
            field=models.CharField(
                choices=[
                    ("contains", "Contains"),
                    ("alias", "Alias"),
                    ("encounter", "Encounter"),
                ],
                max_length=255,
            ),
        ),
    ]
