# Generated by Django 5.0.4 on 2025-03-19 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0025_entryclass_children"),
        ("intelio", "0003_remove_catalystmapping_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnricherSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strategy",
                    models.CharField(
                        choices=[("manual", "Manual"), ("on_create", "On Create")],
                        default="manual",
                        max_length=255,
                    ),
                ),
                ("periodicity", models.DurationField(blank=True, null=True)),
                ("enricher_type", models.CharField(max_length=255, unique=True)),
                ("settings", models.JSONField(blank=True, default=dict)),
                (
                    "for_eclasses",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrichers",
                        to="entries.entryclass",
                    ),
                ),
            ],
        ),
    ]
