# Generated by Django 5.0.4 on 2025-03-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intelio", "0003_alter_association_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="association",
            name="details",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="falconmapping",
            name="type",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
