# Generated by Django 5.0.4 on 2025-03-19 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0025_entryclass_children"),
        ("intelio", "0004_enrichersettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrichersettings",
            name="for_eclasses",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrichers",
                to="entries.entryclass",
            ),
        ),
    ]
