# Generated by Django 5.0.4 on 2025-03-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intelio", "0005_remove_basedigest_entity_basedigest_entities_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="basedigest",
            name="title",
            field=models.CharField(default="Untitled Digest", max_length=255),
            preserve_default=False,
        ),
    ]
