# Generated by Django 5.0.4 on 2025-03-19 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0025_entryclass_children"),
        ("intelio", "0005_alter_enrichersettings_for_eclasses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrichersettings",
            name="for_eclasses",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrichers",
                to="entries.entryclass",
            ),
        ),
    ]
