# Generated by Django 5.0.4 on 2025-04-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0043_entry_aliases"),
        ("intelio", "0006_basedigest_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basedigest",
            name="entities",
            field=models.ManyToManyField(related_name="digests", to="entries.entry"),
        ),
    ]
