# Generated by Django 5.0.4 on 2025-03-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0025_entryclass_children"),
        ("intelio", "0006_alter_enrichersettings_for_eclasses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrichersettings",
            name="for_eclasses",
        ),
        migrations.AddField(
            model_name="enrichersettings",
            name="for_eclasses",
            field=models.ManyToManyField(
                blank=True, related_name="enrichers", to="entries.entryclass"
            ),
        ),
    ]
