# Generated by Django 5.0.4 on 2025-04-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelio", "0007_alter_basedigest_entities"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrichersettings",
            name="last_run",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="enrichersettings",
            name="strategy",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("on_create", "On Create"),
                    ("periodic", "Periodic"),
                ],
                default="manual",
                max_length=255,
            ),
        ),
    ]
