# Generated by Django 5.0.4 on 2025-03-24 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("intelio", "0007_remove_enrichersettings_for_eclasses_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="encounter",
            name="entry",
        ),
        migrations.DeleteModel(
            name="Association",
        ),
        migrations.DeleteModel(
            name="Encounter",
        ),
    ]
