# Generated by Django 5.0.4 on 2025-04-18 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelio", "0008_enrichersettings_last_run_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrichersettings",
            name="periodicity",
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
    ]
