# Generated by Django 5.0.4 on 2025-03-24 00:42

import core.fields
import django.db.models.deletion
import django_lifecycle.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0028_relation_created_at"),
        ("intelio", "0008_remove_encounter_entry_delete_association_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatrushkaAssociation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_vector",
                    core.fields.BitStringField(
                        default=16158503035655503650357438344334975980222051334857742016065172713762327569433945446598600705761456731844358980460949009747059779575245460547544076193224141560315438683650498045875098875194826053398028819192033784138396109321309878080919047169238085235290822926018152521443787945770532904303776199561965192760957166694834171210342487393282284747428088017663161029038902829665513096354230157075129296432088558362971801859230928678799175576150822952201848806616643615613562842355410104862578550863465661734839271290328348967522998634176499319107762583194718667771801067716614802322659239302476074096777926805529798115328,
                        max_length=2048,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "e1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="associations_as_entry1",
                        to="entries.entry",
                    ),
                ),
                (
                    "e2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="associations_as_entry2",
                        to="entries.entry",
                    ),
                ),
                (
                    "entities",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="associations",
                        to="entries.entry",
                    ),
                ),
                (
                    "relations",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_query_name="association",
                        to="entries.relation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
