# Generated by Django 5.0.4 on 2025-03-24 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0028_relation_created_at"),
        ("intelio", "0009_matrushkaassociation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matrushkaassociation",
            name="entities",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="associations",
                to="entries.entry",
            ),
        ),
    ]
