# Generated by Django 5.0.4 on 2025-05-30 13:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("intelio", "0009_alter_enrichersettings_periodicity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="catalystmapping",
            old_name="model_class",
            new_name="field",
        ),
        migrations.RemoveField(
            model_name="catalystmapping",
            name="subtype",
        ),
    ]
