# Generated by Django 5.0.4 on 2025-05-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intelio", "0010_rename_model_class_catalystmapping_field_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalystmapping",
            name="extras",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
