# Generated by Django 5.0.4 on 2025-05-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intelio", "0011_catalystmapping_extras"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalystmapping",
            name="link_type",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
