# Generated by Django 5.0.4 on 2025-10-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0058_relation_reason_context'),
        ('intelio', '0014_enrichmentrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrichersettings',
            name='last_run',
        ),
        migrations.RemoveField(
            model_name='enrichersettings',
            name='periodicity',
        ),
        migrations.RemoveField(
            model_name='enrichersettings',
            name='strategy',
        ),
        migrations.RemoveField(
            model_name='enrichmentrequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='enrichmentrequest',
            name='enrichment_settings',
        ),
        migrations.RemoveField(
            model_name='enrichmentrequest',
            name='entity',
        ),
        migrations.AddField(
            model_name='enrichmentrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrichmentrequest',
            name='enricher_status',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='enrichmentrequest',
            name='enrichers_settings',
            field=models.ManyToManyField(to='intelio.enrichersettings'),
        ),
        migrations.AddField(
            model_name='enrichmentrequest',
            name='entities',
            field=models.ManyToManyField(related_name='enrichment_requests', to='entries.entry'),
        ),
        migrations.AddField(
            model_name='enrichmentrequest',
            name='warnings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='enrichmentrequest',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('working', 'Working'), ('warning', 'Warning'), ('done', 'Done'), ('error', 'Error')], default='waiting', max_length=255),
        ),
    ]
