# Generated by Django 5.0.4 on 2025-10-27 18:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelio', '0015_remove_enrichersettings_last_run_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrichmentrequest',
            name='automated',
        ),
        migrations.AddField(
            model_name='enrichmentrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
