# Generated by Django 5.0.4 on 2025-12-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelio', '0016_remove_enrichmentrequest_automated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrichmentrequest',
            name='errors',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='enrichmentrequest',
            name='request',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='enrichmentrequest',
            name='warnings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
