# Generated by Django 5.0.4 on 2025-12-18 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelio', '0017_alter_enrichmentrequest_errors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrichmentrequest',
            name='ignored',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
