# Generated by Django 5.0.4 on 2025-12-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelio', '0018_enrichmentrequest_ignored'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedigest',
            name='summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='basedigest',
            name='status',
            field=models.CharField(choices=[('working', 'Working'), ('warning', 'Warning'), ('done', 'Done'), ('error', 'Error')], default='working', max_length=255),
        ),
    ]
