# Generated by Django 5.0.4 on 2025-12-22 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intelio', '0019_basedigest_summary_alter_basedigest_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StixDigest',
        ),
    ]
