# Generated by Django 5.0.4 on 2026-01-06 13:02

import django.db.models.deletion
import file_transfer.storage
import intelio.models.base
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelio', '0021_pendingdigestupload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pendingdigestupload',
            name='intelio_pen_expires_bf611c_idx',
        ),
        migrations.AddField(
            model_name='basedigest',
            name='file',
            field=models.FileField(blank=True, null=True, storage=file_transfer.storage.DigestStorage, upload_to=intelio.models.base.digest_upload_path),
        ),
        migrations.AlterField(
            model_name='pendingdigestupload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='pendingdigestupload',
            table='intelio_pendingdigestupload',
        ),
    ]
