# Generated by Django 5.0.4 on 2026-01-06 14:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0060_alter_attachment_file"),
        (
            "intelio",
            "0022_remove_pendingdigestupload_intelio_pen_expires_bf611c_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MISPMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "attribute_type",
                    models.CharField(
                        choices=[
                            ("ip-dst", "IP Destination"),
                            ("ip-src", "IP Source"),
                            ("ip-dst|port", "IP Destination with Port"),
                            ("ip-src|port", "IP Source with Port"),
                            ("domain", "Domain"),
                            ("domain|ip", "Domain with IP"),
                            ("hostname", "Hostname"),
                            ("url", "URL"),
                            ("uri", "URI"),
                            ("user-agent", "User Agent"),
                            ("md5", "MD5 Hash"),
                            ("sha1", "SHA1 Hash"),
                            ("sha256", "SHA256 Hash"),
                            ("sha512", "SHA512 Hash"),
                            ("ssdeep", "SSDEEP Hash"),
                            ("imphash", "Import Hash"),
                            ("authentihash", "Authentihash"),
                            ("email", "Email Address"),
                            ("email-src", "Email Source"),
                            ("email-dst", "Email Destination"),
                            ("email-subject", "Email Subject"),
                            ("email-attachment", "Email Attachment"),
                            ("filename", "Filename"),
                            ("filename|md5", "Filename with MD5"),
                            ("filename|sha1", "Filename with SHA1"),
                            ("filename|sha256", "Filename with SHA256"),
                            ("mutex", "Mutex"),
                            ("vulnerability", "Vulnerability (CVE)"),
                            ("AS", "Autonomous System Number"),
                            ("malware-sample", "Malware Sample"),
                            ("link", "Link"),
                            ("comment", "Comment"),
                            ("text", "Text"),
                            ("other", "Other"),
                        ],
                        help_text="MISP attribute type",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "internal_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="entries.entryclass",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MWDBMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[
                            ("file", "File"),
                            ("config", "Configuration"),
                            ("blob", "Binary Blob"),
                            ("text_blob", "Text Blob"),
                            ("md5", "MD5 Hash"),
                            ("sha1", "SHA1 Hash"),
                            ("sha256", "SHA256 Hash"),
                            ("sha512", "SHA512 Hash"),
                            ("crc32", "CRC32 Checksum"),
                            ("ssdeep", "SSDEEP Hash"),
                            ("parent", "Parent Artifact"),
                            ("child", "Child Artifact"),
                        ],
                        help_text="MWDB artifact type",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "internal_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="entries.entryclass",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OpenCTIMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "observable_type",
                    models.CharField(
                        choices=[
                            ("IPv4-Addr", "IPv4 Address"),
                            ("IPv6-Addr", "IPv6 Address"),
                            ("Domain-Name", "Domain Name"),
                            ("URL", "URL"),
                            ("Email-Addr", "Email Address"),
                            ("Mac-Addr", "MAC Address"),
                            ("Network-Traffic", "Network Traffic"),
                            ("Autonomous-System", "Autonomous System"),
                            ("File", "File"),
                            ("Artifact", "Artifact"),
                            ("Directory", "Directory"),
                            ("StixFile:hashes.MD5", "File MD5 Hash"),
                            ("StixFile:hashes.SHA-1", "File SHA-1 Hash"),
                            ("StixFile:hashes.SHA-256", "File SHA-256 Hash"),
                            ("StixFile:hashes.SHA-512", "File SHA-512 Hash"),
                            ("Software", "Software"),
                            ("User-Account", "User Account"),
                            ("Process", "Process"),
                            ("Windows-Registry-Key", "Windows Registry Key"),
                            ("Mutex", "Mutex"),
                            ("X509-Certificate", "X.509 Certificate"),
                            ("Cryptocurrency-Wallet", "Cryptocurrency Wallet"),
                            ("Text", "Text"),
                            ("Hostname", "Hostname"),
                            ("User-Agent", "User Agent"),
                        ],
                        help_text="OpenCTI STIX Cyber Observable type",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "internal_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="entries.entryclass",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="URLScanMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "observable_type",
                    models.CharField(
                        choices=[
                            ("domain", "Domain"),
                            ("ip", "IP Address"),
                            ("url", "URL"),
                            ("asn", "Autonomous System Number"),
                            ("country", "Country Code"),
                            ("server", "Server Software"),
                            ("hash", "File Hash"),
                        ],
                        help_text="URLScan observable type",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "internal_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="entries.entryclass",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
