# Generated by Django 5.0.4 on 2026-01-06 15:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0060_alter_attachment_file"),
        ("intelio", "0023_mispmapping_mwdbmapping_openctimapping_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DNSMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("A", "IPv4 Address"),
                            ("AAAA", "IPv6 Address"),
                            ("CNAME", "Canonical Name"),
                            ("PTR", "Pointer (Reverse DNS)"),
                            ("MX", "Mail Exchange"),
                            ("SRV", "Service Locator"),
                            ("NS", "Name Server"),
                            ("TXT", "Text"),
                            ("SPF", "Sender Policy Framework"),
                            ("DKIM", "DomainKeys Identified Mail"),
                            ("DMARC", "Domain-based Message Authentication"),
                            ("DNSSEC", "DNS Security Extensions"),
                            ("TLSA", "TLS Authentication"),
                            ("SOA", "Start of Authority"),
                            ("CAA", "Certification Authority Authorization"),
                            ("NAPTR", "Name Authority Pointer"),
                        ],
                        help_text="DNS record type",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "internal_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="entries.entryclass",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
