# Generated by Django 5.0.4 on 2026-01-22 16:23
# BREAKING MIGRATION: Drops all existing enrichment requests and related notifications

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0060_alter_attachment_file'),
        ('intelio', '0024_dnsmapping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Drop all tables related to EnrichmentRequest (including dependent notifications)
        migrations.RunSQL(
            sql='''
                DROP TABLE IF EXISTS "notifications_enrichmentcompletenotification" CASCADE;
                DROP TABLE IF EXISTS "notifications_enrichmenterrornotification" CASCADE;
                DROP TABLE IF EXISTS "intelio_enrichmentrequest_enrichers_settings" CASCADE;
                DROP TABLE IF EXISTS "intelio_enrichmentrequest_entities" CASCADE;
                DROP TABLE IF EXISTS "intelio_enrichmentrequest" CASCADE;
            ''',
            reverse_sql=migrations.RunSQL.noop,
        ),

        # Recreate EnrichmentRequest with UUID primary key
        migrations.CreateModel(
            name='EnrichmentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('working', 'Working'), ('done', 'Done'), ('error', 'Error'), ('warning', 'Warning')], default='waiting', max_length=255)),
                ('enricher_status', models.JSONField(blank=True, default=dict)),
                ('request', models.JSONField(default=dict)),
                ('errors', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=dict)),
                ('ignored', models.JSONField(blank=True, default=list)),
                ('entities', models.ManyToManyField(related_name='enrichment_requests', to='entries.entry')),
                ('enrichers_settings', models.ManyToManyField(to='intelio.enrichersettings')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrichment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
