# Generated by Django 5.0.4 on 2026-01-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelio', '0025_change_enrichmentrequest_pk_to_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrichmentrequest',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('working', 'Working'), ('warning', 'Warning'), ('done', 'Done'), ('error', 'Error')], default='waiting', max_length=255),
        ),
    ]
