# Generated by Django 6.0.2 on 2026-03-03 13:28

import django.db.models.deletion
import file_transfer.storage
import intelio.models.base
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0061_alter_attachment_context_alter_attachment_file_and_more'),
        ('intelio', '0026_alter_enrichmentrequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedigest',
            name='digest_type',
            field=models.CharField(help_text='Subclass name (e.g. CradleDigest, FalconDigest)', max_length=255),
        ),
        migrations.AlterField(
            model_name='basedigest',
            name='entities',
            field=models.ManyToManyField(help_text='Entities associated with this digest', related_name='digests', to='entries.entry'),
        ),
        migrations.AlterField(
            model_name='basedigest',
            name='errors',
            field=models.JSONField(blank=True, default=list, help_text='List of error messages from processing'),
        ),
        migrations.AlterField(
            model_name='basedigest',
            name='file',
            field=models.FileField(blank=True, help_text='Uploaded digest file (stored in S3)', null=True, storage=file_transfer.storage.DigestStorage, upload_to=intelio.models.base.digest_upload_path),
        ),
        migrations.AlterField(
            model_name='basedigest',
            name='status',
            field=models.CharField(choices=[('working', 'Working'), ('warning', 'Warning'), ('done', 'Done'), ('error', 'Error')], default='working', help_text='Processing status of the digest', max_length=255),
        ),
        migrations.AlterField(
            model_name='basedigest',
            name='summary',
            field=models.JSONField(blank=True, default=dict, help_text='Summary statistics from digest processing'),
        ),
        migrations.AlterField(
            model_name='basedigest',
            name='title',
            field=models.CharField(help_text='Human-readable title for the digest', max_length=255),
        ),
        migrations.AlterField(
            model_name='basedigest',
            name='user',
            field=models.ForeignKey(help_text='User who created the digest', on_delete=django.db.models.deletion.CASCADE, related_name='digests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='basedigest',
            name='warnings',
            field=models.JSONField(blank=True, default=list, help_text='List of warning messages from processing'),
        ),
        migrations.AlterField(
            model_name='catalystmapping',
            name='extras',
            field=models.CharField(blank=True, help_text='Optional extra data', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='catalystmapping',
            name='field',
            field=models.CharField(help_text='Catalyst field name', max_length=255),
        ),
        migrations.AlterField(
            model_name='catalystmapping',
            name='internal_class',
            field=models.ForeignKey(help_text='CRADLE entry class this mapping targets', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='entries.entryclass'),
        ),
        migrations.AlterField(
            model_name='catalystmapping',
            name='level',
            field=models.CharField(blank=True, help_text='Optional level', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='catalystmapping',
            name='link_type',
            field=models.CharField(help_text='Link type for relations', max_length=255),
        ),
        migrations.AlterField(
            model_name='catalystmapping',
            name='type',
            field=models.CharField(help_text='Catalyst type identifier', max_length=255),
        ),
        migrations.AlterField(
            model_name='dnsmapping',
            name='internal_class',
            field=models.ForeignKey(help_text='CRADLE entry class this mapping targets', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='entries.entryclass'),
        ),
        migrations.AlterField(
            model_name='enrichersettings',
            name='enabled',
            field=models.BooleanField(default=False, help_text='Whether this enricher is enabled'),
        ),
        migrations.AlterField(
            model_name='enrichersettings',
            name='enricher_type',
            field=models.CharField(help_text='Enricher class name (e.g. AbuseIPDBEnricher)', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='enrichersettings',
            name='for_eclasses',
            field=models.ManyToManyField(blank=True, help_text='Entry classes this enricher applies to', related_name='enrichers', to='entries.entryclass'),
        ),
        migrations.AlterField(
            model_name='enrichersettings',
            name='settings',
            field=models.JSONField(blank=True, default=dict, help_text='Enricher-specific configuration'),
        ),
        migrations.AlterField(
            model_name='enrichmentrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When all enrichers finished', null=True),
        ),
        migrations.AlterField(
            model_name='enrichmentrequest',
            name='enricher_status',
            field=models.JSONField(blank=True, default=dict, help_text='Per-enricher status (enricher_type -> status)'),
        ),
        migrations.AlterField(
            model_name='enrichmentrequest',
            name='enrichers_settings',
            field=models.ManyToManyField(help_text='Enrichers to run for this request', to='intelio.enrichersettings'),
        ),
        migrations.AlterField(
            model_name='enrichmentrequest',
            name='entities',
            field=models.ManyToManyField(help_text='Entities being enriched (for access control)', related_name='enrichment_requests', to='entries.entry'),
        ),
        migrations.AlterField(
            model_name='enrichmentrequest',
            name='errors',
            field=models.JSONField(blank=True, default=dict, help_text='Per-enricher error messages'),
        ),
        migrations.AlterField(
            model_name='enrichmentrequest',
            name='ignored',
            field=models.JSONField(blank=True, default=list, help_text='Request items ignored (no matching enricher)'),
        ),
        migrations.AlterField(
            model_name='enrichmentrequest',
            name='request',
            field=models.JSONField(default=list, help_text='List of {entry_class, name} objects to enrich'),
        ),
        migrations.AlterField(
            model_name='enrichmentrequest',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('working', 'Working'), ('warning', 'Warning'), ('done', 'Done'), ('error', 'Error')], default='waiting', help_text='Overall status of the enrichment request', max_length=255),
        ),
        migrations.AlterField(
            model_name='enrichmentrequest',
            name='title',
            field=models.CharField(help_text='Human-readable title', max_length=255),
        ),
        migrations.AlterField(
            model_name='enrichmentrequest',
            name='user',
            field=models.ForeignKey(help_text='User who created the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrichment_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enrichmentrequest',
            name='warnings',
            field=models.JSONField(blank=True, default=dict, help_text='Per-enricher warning messages'),
        ),
        migrations.AlterField(
            model_name='falconmapping',
            name='internal_class',
            field=models.ForeignKey(help_text='CRADLE entry class this mapping targets', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='entries.entryclass'),
        ),
        migrations.AlterField(
            model_name='falconmapping',
            name='type',
            field=models.CharField(help_text='Falcon type identifier', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='mispmapping',
            name='internal_class',
            field=models.ForeignKey(help_text='CRADLE entry class this mapping targets', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='entries.entryclass'),
        ),
        migrations.AlterField(
            model_name='mwdbmapping',
            name='internal_class',
            field=models.ForeignKey(help_text='CRADLE entry class this mapping targets', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='entries.entryclass'),
        ),
        migrations.AlterField(
            model_name='openctimapping',
            name='internal_class',
            field=models.ForeignKey(help_text='CRADLE entry class this mapping targets', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='entries.entryclass'),
        ),
        migrations.AlterField(
            model_name='pendingdigestupload',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the upload was initiated'),
        ),
        migrations.AlterField(
            model_name='pendingdigestupload',
            name='expires_at',
            field=models.DateTimeField(help_text='When the presigned URL expires and the upload session becomes invalid'),
        ),
        migrations.AlterField(
            model_name='pendingdigestupload',
            name='file_name',
            field=models.CharField(help_text='Original filename provided by the user', max_length=255),
        ),
        migrations.AlterField(
            model_name='pendingdigestupload',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique upload session identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pendingdigestupload',
            name='object_key',
            field=models.CharField(help_text='S3 object key where the file will be stored', max_length=512),
        ),
        migrations.AlterField(
            model_name='pendingdigestupload',
            name='user',
            field=models.ForeignKey(help_text='User who initiated the upload', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='urlscanmapping',
            name='internal_class',
            field=models.ForeignKey(help_text='CRADLE entry class this mapping targets', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='entries.entryclass'),
        ),
    ]
