# Generated by Django — one artifact per enrichment request (replaces list field `request`).

from django.db import migrations, models


def list_request_to_artifact(apps, schema_editor):
    EnrichmentRequest = apps.get_model("intelio", "EnrichmentRequest")
    for er in EnrichmentRequest.objects.iterator():
        raw = getattr(er, "request", None)
        artifact = {}
        if isinstance(raw, list) and raw:
            first = raw[0]
            if isinstance(first, dict) and "entry_class" in first and "name" in first:
                artifact = {"entry_class": str(first["entry_class"]), "name": str(first["name"])}
        elif isinstance(raw, dict) and raw.get("entry_class") is not None and raw.get("name") is not None:
            artifact = {"entry_class": str(raw["entry_class"]), "name": str(raw["name"])}
        EnrichmentRequest.objects.filter(pk=er.pk).update(artifact=artifact)


class Migration(migrations.Migration):
    dependencies = [
        ("intelio", "0027_alter_basedigest_digest_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrichmentrequest",
            name="artifact",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Single artifact to enrich: {"entry_class": subtype, "name": value}',
                null=True,
            ),
        ),
        migrations.RunPython(list_request_to_artifact, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="enrichmentrequest",
            name="request",
        ),
        migrations.AlterField(
            model_name="enrichmentrequest",
            name="artifact",
            field=models.JSONField(
                blank=False,
                default=dict,
                help_text='Single artifact to enrich: {"entry_class": subtype string, "name": value}',
            ),
        ),
    ]
