# Generated by Django 5.0.4 on 2024-07-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="entry",
            name="unique_name_type_subtype",
        ),
        migrations.AlterField(
            model_name="entry",
            name="subtype",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="entry",
            name="type",
            field=models.CharField(
                choices=[("entity", "Entity"), ("artifact", "Artifact")], max_length=20
            ),
        ),
        migrations.AddConstraint(
            model_name="entry",
            constraint=models.UniqueConstraint(
                fields=("name", "subtype"), name="unique_name_type"
            ),
        ),
    ]
