// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * CRADLE
 * Threat Intelligence Knowledge Management
 *
 * The version of the OpenAPI document: 2.10.2-beta.9bd46310 (2.10.2-beta.9bd46310)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AccessEntity,
  AccessEntityList404Response,
  AccessRequest,
  AccessUser,
  RequestAccessRequest,
} from '../models/index';
import {
    AccessEntityFromJSON,
    AccessEntityToJSON,
    AccessEntityList404ResponseFromJSON,
    AccessEntityList404ResponseToJSON,
    AccessRequestFromJSON,
    AccessRequestToJSON,
    AccessUserFromJSON,
    AccessUserToJSON,
    RequestAccessRequestFromJSON,
    RequestAccessRequestToJSON,
} from '../models/index';

export interface AccessEntityListRequest {
    entityId: number;
    search?: string;
}

export interface AccessRequestCreateRequest {
    entityId: string;
    requestAccessRequest: RequestAccessRequest;
    subtype?: string;
}

export interface AccessUserListRequest {
    userId: string;
}

export interface AccessUserUpdateRequest {
    entityId: number;
    userId: string;
    accessRequest: AccessRequest;
}

/**
 * 
 */
export class AccessApi extends runtime.BaseAPI {

    /**
     * Returns a list of all users with their access types for a specific entity. Only available to admin users.
     * Get entity access privileges
     */
    async accessEntityListRaw(requestParameters: AccessEntityListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AccessUser>>> {
        if (requestParameters['entityId'] == null) {
            throw new runtime.RequiredError(
                'entityId',
                'Required parameter "entityId" was null or undefined when calling accessEntityList().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/access/entity/{entity_id}/`;
        urlPath = urlPath.replace(`{${"entity_id"}}`, encodeURIComponent(String(requestParameters['entityId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AccessUserFromJSON));
    }

    /**
     * Returns a list of all users with their access types for a specific entity. Only available to admin users.
     * Get entity access privileges
     */
    async accessEntityList(requestParameters: AccessEntityListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AccessUser>> {
        const response = await this.accessEntityListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Allows a user to request access for an entity. All users with read-write access for that specific entity will receive a notification. If the user making the request already has read-write access, no notifications are sent but the request is deemed successful.
     * Request access to entity
     */
    async accessRequestCreateRaw(requestParameters: AccessRequestCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['entityId'] == null) {
            throw new runtime.RequiredError(
                'entityId',
                'Required parameter "entityId" was null or undefined when calling accessRequestCreate().'
            );
        }

        if (requestParameters['requestAccessRequest'] == null) {
            throw new runtime.RequiredError(
                'requestAccessRequest',
                'Required parameter "requestAccessRequest" was null or undefined when calling accessRequestCreate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['subtype'] != null) {
            queryParameters['subtype'] = requestParameters['subtype'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/access/request/{entity_id}/`;
        urlPath = urlPath.replace(`{${"entity_id"}}`, encodeURIComponent(String(requestParameters['entityId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RequestAccessRequestToJSON(requestParameters['requestAccessRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Allows a user to request access for an entity. All users with read-write access for that specific entity will receive a notification. If the user making the request already has read-write access, no notifications are sent but the request is deemed successful.
     * Request access to entity
     */
    async accessRequestCreate(requestParameters: AccessRequestCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.accessRequestCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a list of all entities with their access types for a specific user. Only available to admin users.
     * Get user access privileges
     */
    async accessUserListRaw(requestParameters: AccessUserListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AccessEntity>>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling accessUserList().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/access/user/{user_id}/`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AccessEntityFromJSON));
    }

    /**
     * Returns a list of all entities with their access types for a specific user. Only available to admin users.
     * Get user access privileges
     */
    async accessUserList(requestParameters: AccessUserListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AccessEntity>> {
        const response = await this.accessUserListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates a user\'s access privileges for a specific entity. Admin users can update access for non-admin users. Users with read-write access can update access for non-admin users who don\'t have read-write access.
     * Update user access for entity
     */
    async accessUserUpdateRaw(requestParameters: AccessUserUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['entityId'] == null) {
            throw new runtime.RequiredError(
                'entityId',
                'Required parameter "entityId" was null or undefined when calling accessUserUpdate().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling accessUserUpdate().'
            );
        }

        if (requestParameters['accessRequest'] == null) {
            throw new runtime.RequiredError(
                'accessRequest',
                'Required parameter "accessRequest" was null or undefined when calling accessUserUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/access/user/{user_id}/{entity_id}/`;
        urlPath = urlPath.replace(`{${"entity_id"}}`, encodeURIComponent(String(requestParameters['entityId'])));
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: AccessRequestToJSON(requestParameters['accessRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Updates a user\'s access privileges for a specific entity. Admin users can update access for non-admin users. Users with read-write access can update access for non-admin users who don\'t have read-write access.
     * Update user access for entity
     */
    async accessUserUpdate(requestParameters: AccessUserUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.accessUserUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
