// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * CRADLE
 * Threat Intelligence Knowledge Management
 *
 * The version of the OpenAPI document: 2.10.2-beta.9bd46310 (2.10.2-beta.9bd46310)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GraphInaccessibleResponse,
  LazyPaginatedEntryWithDepthSerializerViewResponse,
  PaginatedSubGraphSerializerResponse,
  SubGraph,
} from '../models/index';
import {
    GraphInaccessibleResponseFromJSON,
    GraphInaccessibleResponseToJSON,
    LazyPaginatedEntryWithDepthSerializerViewResponseFromJSON,
    LazyPaginatedEntryWithDepthSerializerViewResponseToJSON,
    PaginatedSubGraphSerializerResponseFromJSON,
    PaginatedSubGraphSerializerResponseToJSON,
    SubGraphFromJSON,
    SubGraphToJSON,
} from '../models/index';

export interface KnowledgeGraphInaccessibleRetrieveRequest {
    src: string;
    depth?: number;
}

export interface KnowledgeGraphNeighborsRetrieveRequest {
    src: string;
    depth?: number;
    page?: number;
    pageSize?: number;
    query?: string;
    wildcard?: boolean;
}

export interface KnowledgeGraphPathsRetrieveRequest {
    dsts: Array<number>;
    src: string;
    maxDate?: string;
    minDate?: string;
}

export interface KnowledgeGraphRetrieveRequest {
}

/**
 * 
 */
export class KnowledgeGraphApi extends runtime.BaseAPI {

    /**
     * Get entries in the knowledge graph that are inaccessible to the current user.
     * Get inaccessible graph entries
     */
    async knowledgeGraphInaccessibleRetrieveRaw(requestParameters: KnowledgeGraphInaccessibleRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GraphInaccessibleResponse>> {
        if (requestParameters['src'] == null) {
            throw new runtime.RequiredError(
                'src',
                'Required parameter "src" was null or undefined when calling knowledgeGraphInaccessibleRetrieve().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['depth'] != null) {
            queryParameters['depth'] = requestParameters['depth'];
        }

        if (requestParameters['src'] != null) {
            queryParameters['src'] = requestParameters['src'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/knowledge-graph/inaccessible/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GraphInaccessibleResponseFromJSON(jsonValue));
    }

    /**
     * Get entries in the knowledge graph that are inaccessible to the current user.
     * Get inaccessible graph entries
     */
    async knowledgeGraphInaccessibleRetrieve(requestParameters: KnowledgeGraphInaccessibleRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GraphInaccessibleResponse> {
        const response = await this.knowledgeGraphInaccessibleRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get neighboring entries in the knowledge graph for a given source entry.
     * Get graph neighbors
     */
    async knowledgeGraphNeighborsRetrieveRaw(requestParameters: KnowledgeGraphNeighborsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LazyPaginatedEntryWithDepthSerializerViewResponse>> {
        if (requestParameters['src'] == null) {
            throw new runtime.RequiredError(
                'src',
                'Required parameter "src" was null or undefined when calling knowledgeGraphNeighborsRetrieve().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['depth'] != null) {
            queryParameters['depth'] = requestParameters['depth'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        if (requestParameters['src'] != null) {
            queryParameters['src'] = requestParameters['src'];
        }

        if (requestParameters['wildcard'] != null) {
            queryParameters['wildcard'] = requestParameters['wildcard'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/knowledge-graph/neighbors/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LazyPaginatedEntryWithDepthSerializerViewResponseFromJSON(jsonValue));
    }

    /**
     * Get neighboring entries in the knowledge graph for a given source entry.
     * Get graph neighbors
     */
    async knowledgeGraphNeighborsRetrieve(requestParameters: KnowledgeGraphNeighborsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LazyPaginatedEntryWithDepthSerializerViewResponse> {
        const response = await this.knowledgeGraphNeighborsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Find paths between source and destination entries in the knowledge graph.
     * Find paths in knowledge graph
     */
    async knowledgeGraphPathsRetrieveRaw(requestParameters: KnowledgeGraphPathsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubGraph>> {
        if (requestParameters['dsts'] == null) {
            throw new runtime.RequiredError(
                'dsts',
                'Required parameter "dsts" was null or undefined when calling knowledgeGraphPathsRetrieve().'
            );
        }

        if (requestParameters['src'] == null) {
            throw new runtime.RequiredError(
                'src',
                'Required parameter "src" was null or undefined when calling knowledgeGraphPathsRetrieve().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['dsts'] != null) {
            queryParameters['dsts'] = requestParameters['dsts'];
        }

        if (requestParameters['maxDate'] != null) {
            queryParameters['max_date'] = requestParameters['maxDate'];
        }

        if (requestParameters['minDate'] != null) {
            queryParameters['min_date'] = requestParameters['minDate'];
        }

        if (requestParameters['src'] != null) {
            queryParameters['src'] = requestParameters['src'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/knowledge-graph/paths/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubGraphFromJSON(jsonValue));
    }

    /**
     * Find paths between source and destination entries in the knowledge graph.
     * Find paths in knowledge graph
     */
    async knowledgeGraphPathsRetrieve(requestParameters: KnowledgeGraphPathsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubGraph> {
        const response = await this.knowledgeGraphPathsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the full knowledge graph.
     * Get knowledge graph
     */
    async knowledgeGraphRetrieveRaw(requestParameters: KnowledgeGraphRetrieveRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedSubGraphSerializerResponse>> {
        const queryParameters: any = {};
        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/knowledge-graph/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedSubGraphSerializerResponseFromJSON(jsonValue));
    }

    /**
     * Returns the full knowledge graph.
     * Get knowledge graph
     */
    async knowledgeGraphRetrieve(requestParameters: KnowledgeGraphRetrieveRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedSubGraphSerializerResponse> {
        const response = await this.knowledgeGraphRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
