# Generated by Django 5.0.4 on 2024-07-03 15:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FleetingNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.CharField()),
                ("last_edited", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
