# Generated by Django 5.0.4 on 2025-05-19 15:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("file_transfer", "0005_remove_filereference_fleeting_note"),
        ("fleeting_notes", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FleetingNote",
        ),
    ]
