// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * CRADLE
 * Threat Intelligence Knowledge Management
 *
 * The version of the OpenAPI document: 2.10.2-beta.9bd46310 (2.10.2-beta.9bd46310)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EnrichmentCompleteNotification
 */
export interface EnrichmentCompleteNotification {
    /**
     * 
     * @type {string}
     * @memberof EnrichmentCompleteNotification
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof EnrichmentCompleteNotification
     */
    message: string;
    /**
     * 
     * @type {boolean}
     * @memberof EnrichmentCompleteNotification
     */
    isMarkedUnread?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof EnrichmentCompleteNotification
     */
    readonly timestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof EnrichmentCompleteNotification
     */
    enrichmentRequestId: string;
    /**
     * 
     * @type {string}
     * @memberof EnrichmentCompleteNotification
     */
    readonly notificationType?: string;
}

/**
 * Check if a given object implements the EnrichmentCompleteNotification interface.
 */
export function instanceOfEnrichmentCompleteNotification(value: object): value is EnrichmentCompleteNotification {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('enrichmentRequestId' in value) || value['enrichmentRequestId'] === undefined) return false;
    return true;
}

export function EnrichmentCompleteNotificationFromJSON(json: any): EnrichmentCompleteNotification {
    return EnrichmentCompleteNotificationFromJSONTyped(json, false);
}

export function EnrichmentCompleteNotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnrichmentCompleteNotification {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'message': json['message'],
        'isMarkedUnread': json['is_marked_unread'] == null ? undefined : json['is_marked_unread'],
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'enrichmentRequestId': json['enrichment_request_id'],
        'notificationType': json['notification_type'] == null ? undefined : json['notification_type'],
    };
}

export function EnrichmentCompleteNotificationToJSON(json: any): EnrichmentCompleteNotification {
    return EnrichmentCompleteNotificationToJSONTyped(json, false);
}

export function EnrichmentCompleteNotificationToJSONTyped(value?: Omit<EnrichmentCompleteNotification, 'id'|'timestamp'|'notification_type'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'is_marked_unread': value['isMarkedUnread'],
        'enrichment_request_id': value['enrichmentRequestId'],
    };
}

