// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * CRADLE
 * Threat Intelligence Knowledge Management
 *
 * The version of the OpenAPI document: 2.10.2-beta.9bd46310 (2.10.2-beta.9bd46310)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EssentialUserRetrieve } from './EssentialUserRetrieve';
import {
    EssentialUserRetrieveFromJSON,
    EssentialUserRetrieveFromJSONTyped,
    EssentialUserRetrieveToJSON,
    EssentialUserRetrieveToJSONTyped,
} from './EssentialUserRetrieve';
import type { EnrichmentRequestEnricherMinimal } from './EnrichmentRequestEnricherMinimal';
import {
    EnrichmentRequestEnricherMinimalFromJSON,
    EnrichmentRequestEnricherMinimalFromJSONTyped,
    EnrichmentRequestEnricherMinimalToJSON,
    EnrichmentRequestEnricherMinimalToJSONTyped,
} from './EnrichmentRequestEnricherMinimal';

/**
 * Serializer for detailed enrichment request information.
 * @export
 * @interface EnrichmentRequestList
 */
export interface EnrichmentRequestList {
    /**
     * 
     * @type {string}
     * @memberof EnrichmentRequestList
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof EnrichmentRequestList
     */
    readonly title?: string;
    /**
     * 
     * @type {number}
     * @memberof EnrichmentRequestList
     */
    readonly ignoredCount?: number;
    /**
     * 
     * @type {Date}
     * @memberof EnrichmentRequestList
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof EnrichmentRequestList
     */
    readonly completedAt?: Date | null;
    /**
     * * `waiting` - Waiting
     * * `working` - Working
     * * `warning` - Warning
     * * `done` - Done
     * * `error` - Error
     * @type {string}
     * @memberof EnrichmentRequestList
     */
    readonly status?: EnrichmentRequestListStatusEnum;
    /**
     * 
     * @type {EssentialUserRetrieve}
     * @memberof EnrichmentRequestList
     */
    readonly userDetail?: EssentialUserRetrieve;
    /**
     * 
     * @type {Array<EnrichmentRequestEnricherMinimal>}
     * @memberof EnrichmentRequestList
     */
    readonly enrichers?: Array<EnrichmentRequestEnricherMinimal>;
    /**
     * 
     * @type {any}
     * @memberof EnrichmentRequestList
     */
    readonly request?: any | null;
}


/**
 * @export
 */
export const EnrichmentRequestListStatusEnum = {
    Waiting: 'waiting',
    Working: 'working',
    Warning: 'warning',
    Done: 'done',
    Error: 'error'
} as const;
export type EnrichmentRequestListStatusEnum = typeof EnrichmentRequestListStatusEnum[keyof typeof EnrichmentRequestListStatusEnum];


/**
 * Check if a given object implements the EnrichmentRequestList interface.
 */
export function instanceOfEnrichmentRequestList(value: object): value is EnrichmentRequestList {
    return true;
}

export function EnrichmentRequestListFromJSON(json: any): EnrichmentRequestList {
    return EnrichmentRequestListFromJSONTyped(json, false);
}

export function EnrichmentRequestListFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnrichmentRequestList {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'ignoredCount': json['ignored_count'] == null ? undefined : json['ignored_count'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'completedAt': json['completed_at'] == null ? undefined : (new Date(json['completed_at'])),
        'status': json['status'] == null ? undefined : json['status'],
        'userDetail': json['user_detail'] == null ? undefined : EssentialUserRetrieveFromJSON(json['user_detail']),
        'enrichers': json['enrichers'] == null ? undefined : ((json['enrichers'] as Array<any>).map(EnrichmentRequestEnricherMinimalFromJSON)),
        'request': json['request'] == null ? undefined : json['request'],
    };
}

export function EnrichmentRequestListToJSON(json: any): EnrichmentRequestList {
    return EnrichmentRequestListToJSONTyped(json, false);
}

export function EnrichmentRequestListToJSONTyped(value?: Omit<EnrichmentRequestList, 'id'|'title'|'ignored_count'|'created_at'|'completed_at'|'status'|'user_detail'|'enrichers'|'request'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

