// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * CRADLE
 * Threat Intelligence Knowledge Management
 *
 * The version of the OpenAPI document: 2.10.2-beta.9bd46310 (2.10.2-beta.9bd46310)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OptimizedEntryResponse } from './OptimizedEntryResponse';
import {
    OptimizedEntryResponseFromJSON,
    OptimizedEntryResponseFromJSONTyped,
    OptimizedEntryResponseToJSON,
    OptimizedEntryResponseToJSONTyped,
} from './OptimizedEntryResponse';

/**
 * 
 * @export
 * @interface FileReferenceWithNote
 */
export interface FileReferenceWithNote {
    /**
     * 
     * @type {string}
     * @memberof FileReferenceWithNote
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof FileReferenceWithNote
     */
    mimetype?: string | null;
    /**
     * 
     * @type {Array<OptimizedEntryResponse>}
     * @memberof FileReferenceWithNote
     */
    readonly entities?: Array<OptimizedEntryResponse>;
    /**
     * 
     * @type {number}
     * @memberof FileReferenceWithNote
     */
    fileSize?: number | null;
    /**
     * 
     * @type {string}
     * @memberof FileReferenceWithNote
     */
    fileName?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof FileReferenceWithNote
     */
    readonly timestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof FileReferenceWithNote
     */
    readonly noteId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FileReferenceWithNote
     */
    md5Hash?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FileReferenceWithNote
     */
    sha1Hash?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FileReferenceWithNote
     */
    sha256Hash?: string | null;
}

/**
 * Check if a given object implements the FileReferenceWithNote interface.
 */
export function instanceOfFileReferenceWithNote(value: object): value is FileReferenceWithNote {
    return true;
}

export function FileReferenceWithNoteFromJSON(json: any): FileReferenceWithNote {
    return FileReferenceWithNoteFromJSONTyped(json, false);
}

export function FileReferenceWithNoteFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileReferenceWithNote {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'mimetype': json['mimetype'] == null ? undefined : json['mimetype'],
        'entities': json['entities'] == null ? undefined : ((json['entities'] as Array<any>).map(OptimizedEntryResponseFromJSON)),
        'fileSize': json['file_size'] == null ? undefined : json['file_size'],
        'fileName': json['file_name'] == null ? undefined : json['file_name'],
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'noteId': json['note_id'] == null ? undefined : json['note_id'],
        'md5Hash': json['md5_hash'] == null ? undefined : json['md5_hash'],
        'sha1Hash': json['sha1_hash'] == null ? undefined : json['sha1_hash'],
        'sha256Hash': json['sha256_hash'] == null ? undefined : json['sha256_hash'],
    };
}

export function FileReferenceWithNoteToJSON(json: any): FileReferenceWithNote {
    return FileReferenceWithNoteToJSONTyped(json, false);
}

export function FileReferenceWithNoteToJSONTyped(value?: Omit<FileReferenceWithNote, 'id'|'entities'|'timestamp'|'note_id'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mimetype': value['mimetype'],
        'file_size': value['fileSize'],
        'file_name': value['fileName'],
        'md5_hash': value['md5Hash'],
        'sha1_hash': value['sha1Hash'],
        'sha256_hash': value['sha256Hash'],
    };
}

