// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * CRADLE
 * Threat Intelligence Knowledge Management
 *
 * The version of the OpenAPI document: 2.10.2-beta.9bd46310 (2.10.2-beta.9bd46310)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserConfig
 */
export interface UserConfig {
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof UserConfig
     */
    oauthMethods: Array<{ [key: string]: any; }>;
    /**
     * 
     * @type {boolean}
     * @memberof UserConfig
     */
    signup: boolean;
}

/**
 * Check if a given object implements the UserConfig interface.
 */
export function instanceOfUserConfig(value: object): value is UserConfig {
    if (!('oauthMethods' in value) || value['oauthMethods'] === undefined) return false;
    if (!('signup' in value) || value['signup'] === undefined) return false;
    return true;
}

export function UserConfigFromJSON(json: any): UserConfig {
    return UserConfigFromJSONTyped(json, false);
}

export function UserConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'oauthMethods': json['oauth_methods'],
        'signup': json['signup'],
    };
}

export function UserConfigToJSON(json: any): UserConfig {
    return UserConfigToJSONTyped(json, false);
}

export function UserConfigToJSONTyped(value?: UserConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'oauth_methods': value['oauthMethods'],
        'signup': value['signup'],
    };
}

