// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * CRADLE
 * Threat Intelligence Knowledge Management
 *
 * The version of the OpenAPI document: 2.10.2-beta.9bd46310 (2.10.2-beta.9bd46310)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserCreateSerializerAdminRequest
 */
export interface UserCreateSerializerAdminRequest {
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     * @type {string}
     * @memberof UserCreateSerializerAdminRequest
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof UserCreateSerializerAdminRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserCreateSerializerAdminRequest
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof UserCreateSerializerAdminRequest
     */
    catalystApiKey?: string | null;
    /**
     * Whether to enable Vim keybindings in the editor
     * @type {boolean}
     * @memberof UserCreateSerializerAdminRequest
     */
    vimMode?: boolean;
    /**
     * 
     * @type {any}
     * @memberof UserCreateSerializerAdminRequest
     */
    theme?: any | null;
    /**
     * * `admin` - Admin
     * * `manager` - Manager
     * * `entrymanager` - Entry Manager
     * * `author` - User
     * @type {string}
     * @memberof UserCreateSerializerAdminRequest
     */
    role?: UserCreateSerializerAdminRequestRoleEnum;
    /**
     * 
     * @type {boolean}
     * @memberof UserCreateSerializerAdminRequest
     */
    emailConfirmed?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserCreateSerializerAdminRequest
     */
    isActive?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserCreateSerializerAdminRequest
     */
    twoFactorEnabled?: boolean;
    /**
     * File upload limit in bytes
     * @type {number}
     * @memberof UserCreateSerializerAdminRequest
     */
    fileUploadLimitOverride?: number | null;
}


/**
 * @export
 */
export const UserCreateSerializerAdminRequestRoleEnum = {
    Admin: 'admin',
    Manager: 'manager',
    Entrymanager: 'entrymanager',
    Author: 'author'
} as const;
export type UserCreateSerializerAdminRequestRoleEnum = typeof UserCreateSerializerAdminRequestRoleEnum[keyof typeof UserCreateSerializerAdminRequestRoleEnum];


/**
 * Check if a given object implements the UserCreateSerializerAdminRequest interface.
 */
export function instanceOfUserCreateSerializerAdminRequest(value: object): value is UserCreateSerializerAdminRequest {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function UserCreateSerializerAdminRequestFromJSON(json: any): UserCreateSerializerAdminRequest {
    return UserCreateSerializerAdminRequestFromJSONTyped(json, false);
}

export function UserCreateSerializerAdminRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserCreateSerializerAdminRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'email': json['email'],
        'password': json['password'],
        'catalystApiKey': json['catalyst_api_key'] == null ? undefined : json['catalyst_api_key'],
        'vimMode': json['vim_mode'] == null ? undefined : json['vim_mode'],
        'theme': json['theme'] == null ? undefined : json['theme'],
        'role': json['role'] == null ? undefined : json['role'],
        'emailConfirmed': json['email_confirmed'] == null ? undefined : json['email_confirmed'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'twoFactorEnabled': json['two_factor_enabled'] == null ? undefined : json['two_factor_enabled'],
        'fileUploadLimitOverride': json['file_upload_limit_override'] == null ? undefined : json['file_upload_limit_override'],
    };
}

export function UserCreateSerializerAdminRequestToJSON(json: any): UserCreateSerializerAdminRequest {
    return UserCreateSerializerAdminRequestToJSONTyped(json, false);
}

export function UserCreateSerializerAdminRequestToJSONTyped(value?: UserCreateSerializerAdminRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'email': value['email'],
        'password': value['password'],
        'catalyst_api_key': value['catalystApiKey'],
        'vim_mode': value['vimMode'],
        'theme': value['theme'],
        'role': value['role'],
        'email_confirmed': value['emailConfirmed'],
        'is_active': value['isActive'],
        'two_factor_enabled': value['twoFactorEnabled'],
        'file_upload_limit_override': value['fileUploadLimitOverride'],
    };
}

