from django.urls import path

from intelio.views.digest import (
    DigestAPIView,
    DigestSubclassesAPIView,
    DigestUploadAPIView,
    DigestUploadFinalizeAPIView,
)

from .views.enrichment import (
    EnrichmentAPIView,
    EnrichmentDetailAPIView,
    EnrichmentRelationsAPIView,
    EnrichmentRequestEnricherAPIView,
    EnrichmentRestartAPIView,
    EnrichmentSettingsAPIView,
    EnrichmentSubclassesAPIView,
)
from .views.mappings import (
    ClassMappingSubclassesAPIView,
    MappingKeysSchemaView,
    MappingSchemaView,
)

urlpatterns = [
    path(
        "mappings/",
        ClassMappingSubclassesAPIView.as_view(),
        name="classmapping-subclasses",
    ),
    path(
        "mappings/<str:class_name>/",
        MappingSchemaView.as_view(),
        name="mapping-schema",
    ),
    path(
        "mappings/<str:class_name>/keys",
        MappingKeysSchemaView.as_view(),
        name="mapping-keys-schema",
    ),
    path(
        "enrichment/",
        EnrichmentSubclassesAPIView.as_view(),
        name="enrichment-subclasses",
    ),
    path(
        "enrichment/<str:enricher_type>/",
        EnrichmentSettingsAPIView.as_view(),
        name="enrichment-schema",
    ),
    path(
        "digest/options/",
        DigestSubclassesAPIView.as_view(),
        name="enrichment-subclasses",
    ),
    path(
        "digest/",
        DigestAPIView.as_view(),
        name="enrichment-subclasses",
    ),
    path(
        "digest/upload/",
        DigestUploadAPIView.as_view(),
        name="digest-upload",
    ),
    path(
        "digest/upload/<str:upload_id>/finalize/",
        DigestUploadFinalizeAPIView.as_view(),
        name="digest-upload-finalize",
    ),
    path(
        "enrich/",
        EnrichmentAPIView.as_view(),
        name="enrichment-requests",
    ),
    path(
        "enrich/<uuid:pk>/",
        EnrichmentDetailAPIView.as_view(),
        name="enrichment-detail",
    ),
    path(
        "enrich/<uuid:pk>/restart/",
        EnrichmentRestartAPIView.as_view(),
        name="enrichment-restart",
    ),
    path(
        "enrich/<uuid:pk>/<str:enricher_type>/",
        EnrichmentRequestEnricherAPIView.as_view(),
        name="enrichment-enricher",
    ),
    path(
        "enrich/<uuid:pk>/<str:enricher_type>/relations/",
        EnrichmentRelationsAPIView.as_view(),
        name="enrichment-relations",
    ),
]
