"""URL routing for intelio API: digests, enrichment, and mappings."""

from django.urls import path

from .views.digest import (
    DigestAPIView,
    DigestDetailAPIView,
    DigestSubclassesAPIView,
    DigestUploadAPIView,
    DigestUploadFinalizeAPIView,
)
from .views.enrichment import (
    EnrichmentAPIView,
    EnrichmentDetailAPIView,
    EnrichmentRelationsAPIView,
    EnrichmentRequestEnricherAPIView,
    EnrichmentRestartAPIView,
    EnrichmentSettingsAPIView,
    EnrichmentSubclassesAPIView,
)
from .views.mappings import (
    ClassMappingSubclassesAPIView,
    MappingKeysSchemaView,
    MappingSchemaView,
)

urlpatterns = [
    path(
        "mappings/",
        ClassMappingSubclassesAPIView.as_view(),
        name="classmapping_subclasses",
    ),
    path(
        "mappings/<str:class_name>/",
        MappingSchemaView.as_view(),
        name="mapping_schema",
    ),
    path(
        "mappings/<str:class_name>/keys/",
        MappingKeysSchemaView.as_view(),
        name="mapping_keys_schema",
    ),
    path(
        "enrichment/",
        EnrichmentSubclassesAPIView.as_view(),
        name="enrichment_subclasses",
    ),
    path(
        "enrichment/<str:enricher_type>/",
        EnrichmentSettingsAPIView.as_view(),
        name="enrichment_schema",
    ),
    path(
        "digest/options/",
        DigestSubclassesAPIView.as_view(),
        name="digest_subclasses",
    ),
    path(
        "digest/",
        DigestAPIView.as_view(),
        name="digest_list",
    ),
    path(
        "digest/upload/",
        DigestUploadAPIView.as_view(),
        name="digest_upload",
    ),
    path(
        "digest/upload/<str:upload_id>/finalize/",
        DigestUploadFinalizeAPIView.as_view(),
        name="digest_upload_finalize",
    ),
    path(
        "digest/<uuid:pk>/",
        DigestDetailAPIView.as_view(),
        name="digest_detail",
    ),
    path(
        "enrich/",
        EnrichmentAPIView.as_view(),
        name="enrichment_requests",
    ),
    path(
        "enrich/<uuid:pk>/",
        EnrichmentDetailAPIView.as_view(),
        name="enrichment_detail",
    ),
    path(
        "enrich/<uuid:pk>/restart/",
        EnrichmentRestartAPIView.as_view(),
        name="enrichment_restart",
    ),
    path(
        "enrich/<uuid:pk>/<str:enricher_type>/relations/",
        EnrichmentRelationsAPIView.as_view(),
        name="enrichment_relations",
    ),
    path(
        "enrich/<uuid:pk>/<str:enricher_type>/",
        EnrichmentRequestEnricherAPIView.as_view(),
        name="enrichment_enricher",
    ),
]
