# Generated by Django 5.0.4 on 2024-07-08 22:26

import django.db.models.deletion
import entries.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0002_remove_entry_unique_name_type_subtype_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntryClass",
            fields=[
                (
                    "type",
                    models.CharField(
                        choices=[("entity", "Entity"), ("artifact", "Artifact")],
                        max_length=20,
                    ),
                ),
                (
                    "subtype",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="entry",
            name="unique_name_type",
        ),
        migrations.RemoveField(
            model_name="entry",
            name="subtype",
        ),
        migrations.AlterField(
            model_name="entry",
            name="type",
            field=models.ForeignKey(
                default=entries.models.EntryClass.get_default_pk,
                on_delete=django.db.models.deletion.PROTECT,
                to="entries.entryclass",
            ),
        ),
        migrations.AddConstraint(
            model_name="entry",
            constraint=models.UniqueConstraint(
                fields=("name", "type"), name="unique_name_class"
            ),
        ),
    ]
