# Generated by Django 5.0.4 on 2024-07-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0003_entryclass_remove_entry_unique_name_type_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="entry",
            name="unique_name_class",
        ),
        migrations.RenameField(
            model_name="entry",
            old_name="type",
            new_name="entry_class",
        ),
        migrations.AddConstraint(
            model_name="entry",
            constraint=models.UniqueConstraint(
                fields=("name", "entry_class"), name="unique_name_class"
            ),
        ),
    ]
