# Generated by Django 5.0.4 on 2024-07-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0004_remove_entry_unique_name_class_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
