# Generated by Django 5.0.4 on 2024-07-22 09:21

import django.db.models.deletion
import entries.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0007_alter_entry_entry_class_alter_entry_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="entry_class",
            field=models.ForeignKey(
                default=entries.models.EntryClass.get_default_pk,
                on_delete=django.db.models.deletion.PROTECT,
                to="entries.entryclass",
            ),
        ),
        migrations.AlterField(
            model_name="entry",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="entry",
            name="name",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="entryclass",
            name="options",
            field=models.CharField(blank=True, default="", max_length=65536),
        ),
        migrations.AlterField(
            model_name="entryclass",
            name="regex",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AlterField(
            model_name="entryclass",
            name="subtype",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="entryclass",
            name="type",
            field=models.CharField(
                choices=[("entity", "Entity"), ("artifact", "Artifact")], max_length=20
            ),
        ),
    ]
