# Generated by Django 5.0.4 on 2024-10-02 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0010_entry_timestamp_entryclass_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="entry_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="entries.entryclass"
            ),
        ),
    ]
