# Generated by Django 5.0.4 on 2024-10-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0012_entryclass_catalyst_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entryclass",
            name="catalyst_type",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
