# Generated by Django 5.0.4 on 2024-10-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0013_alter_entryclass_catalyst_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="entryclass",
            name="color",
            field=models.CharField(default="#e66100", max_length=7),
        ),
    ]
