# Generated by Django 5.0.4 on 2025-01-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0016_alter_entryclass_prefix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entryclass",
            name="subtype",
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
