# Generated by Django 5.0.4 on 2025-02-03 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0017_alter_entryclass_subtype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="entry_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="entries.entryclass",
            ),
        ),
    ]
