# Generated by Django 5.0.4 on 2025-03-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0019_entryclass_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="entryclass",
            name="generative_regex",
            field=models.CharField(blank=True, default="", max_length=65536),
        ),
    ]
