# Generated by Django 5.0.4 on 2025-03-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0021_entry_acvec_offset_alter_entry_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="status",
            field=models.JSONField(default=dict, null=True),
        ),
    ]
