# Generated by Django 5.0.4 on 2025-03-18 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0022_entry_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entryclass",
            name="catalyst_type",
        ),
    ]
