# Generated by Django 5.0.4 on 2025-03-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0023_remove_entryclass_catalyst_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="aliases",
            field=models.ManyToManyField(
                blank=True,
                help_text="Entries that are equivalent to this one",
                related_name="aliased_by",
                to="entries.entry",
            ),
        ),
    ]
