# Generated by Django 5.0.4 on 2025-03-25 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0024_remove_entryclass_catalyst_type_entry_aliases_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entry",
            name="related_entries",
        ),
    ]
