# Generated by Django 5.0.4 on 2025-03-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0024_entry_aliases"),
    ]

    operations = [
        migrations.AddField(
            model_name="entryclass",
            name="children",
            field=models.ManyToManyField(
                blank=True,
                help_text="Possible children of this entry class",
                related_name="parents",
                to="entries.entryclass",
            ),
        ),
    ]
