# Generated by Django 5.0.4 on 2025-03-26 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0025_remove_entry_related_entries"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entry",
            options={"ordering": ["-timestamp"]},
        ),
    ]
