# Generated by Django 5.0.4 on 2025-03-26 14:50

from django.db import migrations

from django.db import migrations
from django.utils.timezone import now


def set_default_timestamp(apps, schema_editor):
    Entry = apps.get_model("entries", "Entry")
    Entry.objects.filter(timestamp__isnull=True).update(timestamp=now())


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0026_alter_entry_options"),
    ]

    operations = [
        migrations.RunPython(set_default_timestamp),
    ]
