# Generated by Django 5.0.4 on 2025-03-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0026_relation_relation_unique_src_dst_object"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="related_entries",
            field=models.ManyToManyField(
                through="entries.Relation", to="entries.entry"
            ),
        ),
    ]
