# Generated by Django 5.0.4 on 2025-03-24 00:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0027_entry_related_entries"),
    ]

    operations = [
        migrations.AddField(
            model_name="relation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
