# Generated by Django 5.0.4 on 2025-03-29 00:05

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0028_auto_20250328_2355"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=0
            ),
        ),
    ]
