# Generated by Django 5.0.4 on 2025-03-29 20:12

import core.fields
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import django_lifecycle.mixins
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0029_entry_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Edge",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("src", models.UUIDField()),
                ("dst", models.UUIDField()),
                (
                    "access_vector",
                    core.fields.BitStringField(
                        default=16158503035655503650357438344334975980222051334857742016065172713762327569433945446598600705761456731844358980460949009747059779575245460547544076193224141560315438683650498045875098875194826053398028819192033784138396109321309878080919047169238085235290822926018152521443787945770532904303776199561965192760957166694834171210342487393282284747428088017663161029038902829665513096354230157075129296432088558362971801859230928678799175576150822952201848806616643615613562842355410104862578550863465661734839271290328348967522998634176499319107762583194718667771801067716614802322659239302476074096777926805529798115328,
                        max_length=2048,
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("last_seen", models.DateTimeField()),
            ],
            options={
                "db_table": "edges",
                "managed": False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.RunSQL(  # Clear the existing relations
            """
            DELETE FROM entries_relation;
            """
        ),
        migrations.AlterModelOptions(
            name="entry",
            options={"ordering": ["-last_seen"]},
        ),
        migrations.AlterModelOptions(
            name="relation",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelManagers(
            name="relation",
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="relation",
            name="unique_src_dst_object",
        ),
        migrations.RenameField(
            model_name="entry",
            old_name="timestamp",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="relation",
            name="dst_entry",
        ),
        migrations.RemoveField(
            model_name="relation",
            name="src_entry",
        ),
        migrations.AddField(
            model_name="entry",
            name="last_seen",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="relation",
            name="details",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="relation",
            name="e1",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relations_1",
                to="entries.entry",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="relation",
            name="e2",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relations_2",
                to="entries.entry",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="relation",
            name="reason",
            field=models.CharField(
                choices=[
                    ("contains", "Contains"),
                    ("alias", "Alias"),
                    ("encounter", "Encounter"),
                ],
                default=None,
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="relation",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
