# Generated by Django 5.0.4 on 2025-03-29 20:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0030_edge_alter_entry_options_alter_relation_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="relation",
            name="last_seen",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
