# Generated by Django 5.0.4 on 2025-03-29 20:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0031_relation_last_seen"),
    ]

    operations = [
        # Create the materialized view
        migrations.RunSQL(
            sql="""
            CREATE MATERIALIZED VIEW edges AS
            (
                SELECT
                    md5(LEAST(e1_id::text, e2_id::text) || GREATEST(e1_id::text, e2_id::text))::uuid AS id,
                    e1_id AS src,
                    e2_id AS dst,
                    BIT_AND(access_vector) AS access_vector,
                    MIN(created_at) AS created_at,
                    MAX(last_seen) AS last_seen,
                    EXTRACT(EPOCH FROM (now() - MAX(last_seen))) AS age
                FROM entries_relation
                GROUP BY e1_id, e2_id
            )
            UNION ALL
            (
                SELECT
                    md5(GREATEST(e1_id::text, e2_id::text) || LEAST(e1_id::text, e2_id::text))::uuid AS id,
                    e2_id AS src,
                    e1_id AS dst,
                    BIT_AND(access_vector) AS access_vector,
                    MIN(created_at) AS created_at,
                    MAX(last_seen) AS last_seen,
                    EXTRACT(EPOCH FROM (now() - MAX(last_seen))) AS age
                FROM entries_relation
                GROUP BY e1_id, e2_id
            );
            """,
            reverse_sql="DROP MATERIALIZED VIEW IF EXISTS edges;",
        ),
        # Create indexes on the materialized view
        migrations.RunSQL(
            sql="""
            CREATE UNIQUE INDEX idx_edges_id ON edges(id);
            CREATE INDEX idx_edges_src ON edges(src);
            CREATE INDEX idx_edges_dst ON edges(dst);
            CREATE INDEX idx_edges_created_at ON edges(created_at);
            CREATE INDEX idx_edges_last_seen ON edges(last_seen);
            CREATE INDEX idx_edges_src_lt_dst ON edges(src, dst, created_at, last_seen)
              WHERE src < dst;
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS idx_edges_id;
            DROP INDEX IF EXISTS idx_edges_src;
            DROP INDEX IF EXISTS idx_edges_dst;
            DROP INDEX IF EXISTS idx_edges_created_at;
            DROP INDEX IF EXISTS idx_edges_last_seen;
            DROP INDEX IF EXISTS idx_edges_src_lt_dst;
            """,
        ),
    ]
