# Generated by Django 5.0.4 on 2025-03-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0032_auto_20250329_2022"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="relation",
            options={"ordering": ["-last_seen"]},
        ),
        migrations.AlterModelManagers(
            name="relation",
            managers=[],
        ),
        migrations.AddField(
            model_name="entry",
            name="degree",
            field=models.IntegerField(default=0),
        ),
    ]
