# Generated by Django 5.0.4 on 2025-03-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0033_alter_relation_options_alter_relation_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relation",
            name="reason",
            field=models.CharField(
                choices=[
                    ("contains", "Contains"),
                    ("alias", "Alias"),
                    ("encounter", "Encounter"),
                    ("note", "Note"),
                ],
                max_length=255,
            ),
        ),
    ]
