# Generated by Django 5.0.4 on 2025-04-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0034_alter_relation_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="new_id",
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
