# Generated by Django 5.0.4 on 2025-04-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0035_entry_new_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entry",
            name="new_id",
        ),
        migrations.RemoveField(
            model_name="entry",
            name="id",
        ),
        migrations.AddField(
            model_name="entry",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
