# Generated by Django 5.0.4 on 2025-04-01 22:31

from django.db import migrations, models


def copy_field_data(apps, schema_editor):
    Entry = apps.get_model("entries", "Entry")
    for obj in Entry.objects.filter(entry_class__type="entity"):
        obj.id_copy = obj.id
        obj.save(update_fields=["id_copy"])


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0035_entry_new_id"),
        ("access", "0004_access_entity_id_back"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE notes_note_entries DROP CONSTRAINT IF EXISTS notes_note_entries_entry_id_0c8c0492_fk_entries_entry_id;
            ALTER TABLE entries_entry_aliases DROP CONSTRAINT IF EXISTS entries_entry_aliase_from_entry_id_dc27e48a_fk_entries_e;
            ALTER TABLE entries_entry_aliases DROP CONSTRAINT IF EXISTS entries_entry_aliases_to_entry_id_a6295c3a_fk_entries_entry_id;
            ALTER TABLE entries_relation DROP CONSTRAINT IF EXISTS entries_relation_e1_id_a685169c_fk_entries_entry_id;
            ALTER TABLE entries_relation DROP CONSTRAINT IF EXISTS entries_relation_e2_id_4ba42ab7_fk_entries_entry_id;
            ALTER TABLE access_access DROP CONSTRAINT IF EXISTS access_access_entity_id_eae3de6a_fk_entries_entry_id;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveField(
            model_name="entry",
            name="new_id",
        ),
        migrations.AddField(
            model_name="entry",
            name="id_copy",
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(copy_field_data),
        migrations.RemoveField(
            model_name="entry",
            name="id",
        ),
        migrations.AddField(
            model_name="entry",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
