# Generated by Django 5.0.4 on 2025-04-01 22:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0036_remove_entry_new_id_alter_entry_id"),
    ]

    operations = [
        migrations.RunSQL(  # Clear the existing relations
            """
            DELETE FROM entries_relation;
            """
        ),
    ]
