# Generated by Django 5.0.4 on 2025-04-01 22:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0037_auto_20250401_2234"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="relation",
            name="e1",
        ),
        migrations.RemoveField(
            model_name="relation",
            name="e2",
        ),
    ]
