# Generated by Django 5.0.4 on 2025-04-01 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0038_remove_relation_e1_remove_relation_e2"),
    ]

    operations = [
        migrations.AddField(
            model_name="relation",
            name="e1",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relations_1",
                to="entries.entry",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="relation",
            name="e2",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relations_2",
                to="entries.entry",
            ),
            preserve_default=False,
        ),
    ]
