# Generated by Django 5.0.4 on 2025-04-01 23:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0039_relation_e1_relation_e2"),
        ("access", "0006_access_entity_access_unique_user_id_entity_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entry",
            name="id_copy",
        ),
    ]
