# Generated by Django 5.0.4 on 2025-04-02 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0041_auto_20250402_0843"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entry",
            name="aliases",
        ),
    ]
