# Generated by Django 5.0.4 on 2025-04-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0043_entry_aliases"),
    ]

    operations = [
        migrations.AddField(
            model_name="relation",
            name="virtual",
            field=models.BooleanField(default=False),
        ),
    ]
