# Generated by Django 5.0.4 on 2025-04-03 21:45

from django.db import migrations

from entries.enums import RelationReason


def delete_existing_contains(apps, schema_editor):
    Relation = apps.get_model("entries", "Relation")
    Relation.objects.filter(reason=RelationReason.CONTAINS).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0045_auto_20250402_2147"),
    ]

    operations = [
        migrations.RunPython(delete_existing_contains),
    ]
