# Generated by Django 5.0.4 on 2025-04-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0046_auto_20250403_2145"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relation",
            name="reason",
            field=models.CharField(
                choices=[
                    ("digest", "Digest"),
                    ("contains", "Contains"),
                    ("alias", "Alias"),
                    ("encounter", "Encounter"),
                    ("note", "Note"),
                ],
                max_length=255,
            ),
        ),
    ]
