# Generated by Django 5.0.4 on 2025-04-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0048_alter_relation_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="relation",
            name="inherit_av",
            field=models.BooleanField(default=False),
        ),
    ]
