# Generated by Django 5.0.4 on 2025-04-15 14:37

import core.fields
import django_lifecycle.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0049_relation_inherit_av"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntryAccessVectors",
            fields=[
                ("id", models.CharField(primary_key=True, serialize=False)),
                (
                    "access_vector",
                    core.fields.BitStringField(
                        default=16158503035655503650357438344334975980222051334857742016065172713762327569433945446598600705761456731844358980460949009747059779575245460547544076193224141560315438683650498045875098875194826053398028819192033784138396109321309878080919047169238085235290822926018152521443787945770532904303776199561965192760957166694834171210342487393282284747428088017663161029038902829665513096354230157075129296432088558362971801859230928678799175576150822952201848806616643615613562842355410104862578550863465661734839271290328348967522998634176499319107762583194718667771801067716614802322659239302476074096777926805529798115328,
                        max_length=2048,
                    ),
                ),
            ],
            options={
                "db_table": "entry_accesses",
                "managed": False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
