# Generated by Django 5.0.4 on 2025-04-16 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0050_entryaccessvectors"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EntryAccessVectors",
        ),
    ]
