# Generated by Django 5.0.4 on 2025-05-29 15:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0052_entryclass_format"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relation",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="relation",
            name="last_seen",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
