# Generated by Django 5.0.4 on 2025-07-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0053_alter_relation_created_at_alter_relation_last_seen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="name",
            field=models.CharField(max_length=1024),
        ),
    ]
