# Generated by Django 5.0.4 on 2025-09-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0054_alter_entry_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryclass',
            name='type',
            field=models.CharField(choices=[('entity', 'Entity'), ('artifact', 'Artifact')], db_index=True, max_length=20),
        ),
    ]
