# Generated by Django 5.0.4 on 2025-09-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0055_alter_entryclass_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['entry_class'], name='entries_ent_entry_c_a85a4a_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['is_public'], name='entries_ent_is_publ_9899cf_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['created_at'], name='entries_ent_created_823464_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['last_seen'], name='entries_ent_last_se_cadf35_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['acvec_offset'], name='entries_ent_acvec_o_6c936b_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['status'], name='entries_ent_status_e7314c_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['degree'], name='entries_ent_degree_541e63_idx'),
        ),
        migrations.AddIndex(
            model_name='entryclass',
            index=models.Index(fields=['type'], name='entries_ent_type_120f19_idx'),
        ),
        migrations.AddIndex(
            model_name='entryclass',
            index=models.Index(fields=['timestamp'], name='entries_ent_timesta_028536_idx'),
        ),
        migrations.AddIndex(
            model_name='entryclass',
            index=models.Index(fields=['format'], name='entries_ent_format_daf37d_idx'),
        ),
    ]
