# Generated by Django 5.0.4 on 2025-09-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0056_entry_entries_ent_entry_c_a85a4a_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='entry',
            name='entries_ent_entry_c_a85a4a_idx',
        ),
        migrations.RemoveIndex(
            model_name='entry',
            name='entries_ent_is_publ_9899cf_idx',
        ),
        migrations.RemoveIndex(
            model_name='entry',
            name='entries_ent_created_823464_idx',
        ),
        migrations.RemoveIndex(
            model_name='entry',
            name='entries_ent_last_se_cadf35_idx',
        ),
        migrations.RemoveIndex(
            model_name='entry',
            name='entries_ent_acvec_o_6c936b_idx',
        ),
        migrations.RemoveIndex(
            model_name='entry',
            name='entries_ent_status_e7314c_idx',
        ),
        migrations.RemoveIndex(
            model_name='entry',
            name='entries_ent_degree_541e63_idx',
        ),
        migrations.RemoveIndex(
            model_name='entryclass',
            name='entries_ent_type_120f19_idx',
        ),
        migrations.RemoveIndex(
            model_name='entryclass',
            name='entries_ent_timesta_028536_idx',
        ),
        migrations.RemoveIndex(
            model_name='entryclass',
            name='entries_ent_format_daf37d_idx',
        ),
        migrations.AlterField(
            model_name='entryclass',
            name='type',
            field=models.CharField(choices=[('entity', 'Entity'), ('artifact', 'Artifact')], max_length=20),
        ),
    ]
