# Generated by Django 5.0.4 on 2025-10-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0057_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='reason_context',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
