# Generated by Django 5.0.4 on 2025-12-22 18:21

import django.db.models.deletion
import django_lifecycle.mixins
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0058_relation_reason_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='attachments/')),
                ('type', models.CharField(max_length=255)),
                ('context', models.JSONField(default=dict)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='entries.relation')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
