# Generated by Django 5.0.4 on 2025-12-22 19:34

import entries.models
import file_transfer.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0059_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(storage=file_transfer.storage.RelationStorage, upload_to=entries.models.attachment_upload_path),
        ),
    ]
