# Generated by Django 6.0.2 on 2026-03-03 13:28

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import entries.models
import file_transfer.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0060_alter_attachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='context',
            field=models.JSONField(default=dict, help_text='Extra metadata (e.g. enrichment source)'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(help_text='Stored file path', storage=file_transfer.storage.RelationStorage, upload_to=entries.models.attachment_upload_path),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='name',
            field=models.CharField(help_text='Original filename for download', max_length=255),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='relation',
            field=models.ForeignKey(help_text='Relation this attachment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='entries.relation'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='type',
            field=models.CharField(help_text='MIME type or file category', max_length=255),
        ),
        migrations.AlterField(
            model_name='entry',
            name='acvec_offset',
            field=models.PositiveIntegerField(default=0, help_text='Bit offset in access vector for entity visibility'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='degree',
            field=models.IntegerField(default=0, help_text='Number of outgoing edges in the graph'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description', null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_class',
            field=models.ForeignKey(help_text='Type of this entry (entity or artifact subtype)', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='entries.entryclass'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether this entry is visible to all users'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='last_seen',
            field=models.DateTimeField(auto_now_add=True, help_text='Last activity timestamp'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Optional geographic location', null=True, srid=0),
        ),
        migrations.AlterField(
            model_name='entry',
            name='name',
            field=models.CharField(help_text='Display name, validated by entry_class rules', max_length=1024),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.JSONField(default=dict, help_text='Transient status (e.g. during access updates)', null=True),
        ),
        migrations.AlterField(
            model_name='entryclass',
            name='color',
            field=models.CharField(default='#e66100', help_text='Hex color for UI display', max_length=7),
        ),
        migrations.AlterField(
            model_name='entryclass',
            name='description',
            field=models.TextField(blank=True, help_text='Human-readable description of this entry class', null=True),
        ),
        migrations.AlterField(
            model_name='entryclass',
            name='format',
            field=models.CharField(choices=[('regex', 'Regex'), ('options', 'Options')], default=None, help_text='Validation format: regex or options', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='entryclass',
            name='generative_regex',
            field=models.CharField(blank=True, default='', help_text='Regex for generating child entries from parent text', max_length=65536),
        ),
        migrations.AlterField(
            model_name='entryclass',
            name='options',
            field=models.CharField(blank=True, default='', help_text='Newline-separated allowed values (alternative to regex)', max_length=65536),
        ),
        migrations.AlterField(
            model_name='entryclass',
            name='prefix',
            field=models.CharField(blank=True, help_text='Prefix for entity names (e.g. E- for cases)', max_length=64),
        ),
        migrations.AlterField(
            model_name='entryclass',
            name='regex',
            field=models.CharField(blank=True, default='', help_text='Regex pattern for artifact validation', max_length=65536),
        ),
        migrations.AlterField(
            model_name='entryclass',
            name='subtype',
            field=models.CharField(help_text='Unique identifier (e.g. ip/address)', max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entryclass',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='When this class was created'),
        ),
        migrations.AlterField(
            model_name='entryclass',
            name='type',
            field=models.CharField(choices=[('entity', 'Entity'), ('artifact', 'Artifact')], help_text='Entity or artifact', max_length=20),
        ),
        migrations.AlterField(
            model_name='relation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='details',
            field=models.JSONField(blank=True, default=dict, help_text='Extra relation metadata'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='e1',
            field=models.ForeignKey(help_text='First entry (lower ID)', on_delete=django.db.models.deletion.CASCADE, related_name='relations_1', to='entries.entry'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='e2',
            field=models.ForeignKey(help_text='Second entry (higher ID)', on_delete=django.db.models.deletion.CASCADE, related_name='relations_2', to='entries.entry'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='inherit_av',
            field=models.BooleanField(default=False, help_text='Whether to inherit access from content_object'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last observation'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='object_id',
            field=models.UUIDField(help_text='ID of the content object'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='reason',
            field=models.CharField(choices=[('digest', 'Digest'), ('enrichment', 'Enrichment'), ('contains', 'Contains'), ('alias', 'Alias'), ('encounter', 'Encounter'), ('note', 'Note')], help_text='Why this relation exists (digest, enrichment, contains, etc.)', max_length=255),
        ),
        migrations.AlterField(
            model_name='relation',
            name='reason_context',
            field=models.CharField(blank=True, help_text='Additional context for reason', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='relation',
            name='virtual',
            field=models.BooleanField(default=False, help_text='Whether this relation is virtual (e.g. alias)'),
        ),
    ]
