# Generated by Django 5.0.4 on 2025-02-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0002_alter_eventlog_object_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventlog",
            name="details",
            field=models.CharField(blank=True, null=True),
        ),
    ]
