# Generated by Django 5.0.4 on 2025-02-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_alter_cradleuser_email_confirmed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cradleuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("entrymanager", "Manager"),
                    ("author", "User"),
                ],
                default="author",
                max_length=32,
            ),
        ),
    ]
