# Generated by Django 5.0.4 on 2025-02-26 16:45

import django.db.models.deletion
import logs.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("notes", "0010_alter_note_entries"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublishedReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("catalyst", "Catalyst"),
                            ("html", "HTML"),
                            ("plain", "Plain Text"),
                            ("json", "JSON"),
                        ],
                        max_length=255,
                    ),
                ),
                ("report_location", models.CharField(max_length=1024)),
                ("completed", models.BooleanField(default=False)),
                (
                    "mode",
                    models.CharField(
                        blank=True,
                        choices=[("upload", "Upload"), ("download", "Download")],
                        max_length=10,
                    ),
                ),
                (
                    "notes",
                    models.ManyToManyField(
                        related_name="published_reports", to="notes.note"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=(models.Model, logs.models.LoggableModelMixin),
        ),
    ]
