# Generated by Django 5.0.4 on 2025-02-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publish", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publishedreport",
            name="title",
            field=models.CharField(default="", max_length=512),
        ),
    ]
