# Generated by Django 5.0.4 on 2025-02-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publish", "0004_alter_publishedreport_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="publishedreport",
            name="anonymized",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="publishedreport",
            name="extra_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="publishedreport",
            name="strategy",
            field=models.CharField(
                choices=[
                    ("catalyst", "Catalyst"),
                    ("html", "HTML"),
                    ("plain", "Plain Text"),
                    ("json", "JSON"),
                    ("import", "Import"),
                ],
                max_length=255,
            ),
        ),
    ]
