# Generated by Django 5.0.4 on 2025-02-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publish", "0005_publishedreport_anonymized_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publishedreport",
            name="report_location",
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
