# Generated by Django 5.0.4 on 2025-03-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publish", "0006_alter_publishedreport_report_location"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publishedreport",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="publishedreport",
            name="mode",
        ),
        migrations.AddField(
            model_name="publishedreport",
            name="remote_url",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="publishedreport",
            name="strategy",
            field=models.CharField(
                choices=[
                    ("catalyst", "Catalyst"),
                    ("html", "HTML"),
                    ("plain", "Plain Text"),
                    ("json", "JSON"),
                ],
                max_length=255,
            ),
        ),
    ]
