# Generated by Django 5.0.4 on 2025-06-02 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("publish", "0008_remove_publishedreport_report_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publishedreport",
            old_name="remote_url",
            new_name="external_ref",
        ),
    ]
