# Generated by Django 5.0.4 on 2026-01-06 13:08

import file_transfer.storage
import publish.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0009_rename_remote_url_publishedreport_external_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedreport',
            name='file',
            field=models.FileField(blank=True, null=True, storage=file_transfer.storage.ReportStorage, upload_to=publish.models.report_upload_path),
        ),
    ]
