# Generated by Django 6.0.2 on 2026-03-03 13:28

import django.db.models.deletion
import file_transfer.storage
import publish.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0029_alter_archivednote_content_alter_archivednote_id_and_more'),
        ('publish', '0010_publishedreport_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publishedreport',
            options={'ordering': ['-created_at'], 'verbose_name': 'published report', 'verbose_name_plural': 'published reports'},
        ),
        migrations.AlterField(
            model_name='publishedreport',
            name='anonymized',
            field=models.BooleanField(default=False, help_text='Whether the report content has been anonymized.'),
        ),
        migrations.AlterField(
            model_name='publishedreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the report was created.'),
        ),
        migrations.AlterField(
            model_name='publishedreport',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error details when status is error.', null=True),
        ),
        migrations.AlterField(
            model_name='publishedreport',
            name='external_ref',
            field=models.CharField(help_text='Reference ID in external system (e.g. Catalyst).', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publishedreport',
            name='extra_data',
            field=models.JSONField(blank=True, help_text='Additional strategy-specific metadata.', null=True),
        ),
        migrations.AlterField(
            model_name='publishedreport',
            name='file',
            field=models.FileField(blank=True, help_text='Report file stored in S3.', null=True, storage=file_transfer.storage.ReportStorage, upload_to=publish.models.report_upload_path),
        ),
        migrations.AlterField(
            model_name='publishedreport',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the report.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publishedreport',
            name='notes',
            field=models.ManyToManyField(help_text='Notes included in this report.', related_name='published_reports', to='notes.note'),
        ),
        migrations.AlterField(
            model_name='publishedreport',
            name='status',
            field=models.CharField(choices=[('working', 'Working'), ('done', 'Done'), ('error', 'Error')], default='working', help_text='Current publication status.', max_length=10),
        ),
        migrations.AlterField(
            model_name='publishedreport',
            name='strategy',
            field=models.CharField(choices=[('catalyst', 'Catalyst'), ('html', 'HTML'), ('plain', 'Plain Text'), ('json', 'JSON')], help_text='Upload or download format strategy.', max_length=255),
        ),
        migrations.AlterField(
            model_name='publishedreport',
            name='title',
            field=models.CharField(default='Title', help_text='Display title of the report.', max_length=512),
        ),
        migrations.AlterField(
            model_name='publishedreport',
            name='user',
            field=models.ForeignKey(help_text='User who created the report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
