# Generated by Django 6.0.8 on 2026-10-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publish", "0011_alter_publishedreport_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publishedreport",
            name="external_ref",
        ),
        migrations.AlterField(
            model_name="publishedreport",
            name="strategy",
            field=models.CharField(
                choices=[("html", "HTML"), ("plain", "Plain Text"), ("json", "JSON")],
                help_text="Export format strategy.",
                max_length=255,
            ),
        ),
    ]
