# Generated by Django 5.0.4 on 2024-10-02 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_note_author"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="edit_timestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="note",
            name="editor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="editor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
