# Generated by Django 5.0.4 on 2025-01-15 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0006_graph_query_optimizations"),
    ]

    operations = []
