# Generated by Django 5.0.4 on 2025-01-15 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("entries", "0016_alter_entryclass_prefix"),
        ("notes", "0007_graph_query_recursive_search"),
    ]

    operations = [
        migrations.RunSQL(  # Clear the existing relations
            """
            DELETE FROM notes_relation;
            """
        ),
        migrations.RemoveConstraint(
            model_name="relation",
            name="unique_src_dst_note",
        ),
        migrations.RemoveField(
            model_name="relation",
            name="note",
        ),
        migrations.AddField(
            model_name="relation",
            name="object_id",
            field=models.UUIDField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="relation",
            name="content_type",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="relation",
            constraint=models.UniqueConstraint(
                fields=("src_entry", "dst_entry", "content_type", "object_id"),
                name="unique_src_dst_object",
            ),
        ),
    ]
