# Generated by Django 5.0.4 on 2025-02-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0018_alter_entry_entry_class"),
        ("notes", "0009_graph_traversal_functions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="entries",
            field=models.ManyToManyField(related_name="notes", to="entries.entry"),
        ),
    ]
