# Generated by Django 5.0.4 on 2025-03-07 23:32

import core.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0010_alter_note_entries"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="access_vector",
            field=core.fields.BitStringField(default=1 << 2047, max_length=2048),
        ),
    ]
