# Generated by Django 5.0.4 on 2025-03-23 21:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0013_elevate_knowledge_graph_access_control"),
    ]

    database_operations = [migrations.AlterModelTable("Relation", "entries_relation")]

    state_operations = [migrations.DeleteModel("Relation")]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations, state_operations=state_operations
        )
    ]
