# Generated by Django 5.0.4 on 2025-04-01 22:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0016_auto_20250401_2235"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="entries",
        ),
    ]
