# Generated by Django 5.0.4 on 2025-04-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0039_relation_e1_relation_e2"),
        ("notes", "0017_remove_note_entries"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="entries",
            field=models.ManyToManyField(related_name="notes", to="entries.entry"),
        ),
    ]
