# Generated by Django 5.0.4 on 2025-04-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0018_note_entries"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="last_linked",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
