# Generated by Django 5.0.4 on 2025-05-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0019_note_last_linked"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="fleeting",
            field=models.BooleanField(default=False),
        ),
    ]
