# Generated by Django 5.0.4 on 2025-05-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0020_note_fleeting"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="status",
            field=models.CharField(
                choices=[
                    ("healthy", "Healthy"),
                    ("processing", "Processing"),
                    ("warning", "Warning"),
                    ("invalid", "Editing"),
                ],
                default="healthy",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="status_message",
            field=models.CharField(default=""),
        ),
        migrations.AddField(
            model_name="note",
            name="status_timestamp",
            field=models.DateTimeField(null=True),
        ),
    ]
