# Generated by Django 5.0.4 on 2025-06-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0021_note_status_note_status_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="note",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="note",
            name="title",
            field=models.CharField(default="", max_length=255),
        ),
    ]
