# Generated by Django 5.0.4 on 2025-06-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0022_note_description_note_metadata_note_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="description",
            field=models.TextField(default="", max_length=4096),
        ),
        migrations.AlterField(
            model_name="note",
            name="status",
            field=models.CharField(
                choices=[
                    ("healthy", "Healthy"),
                    ("processing", "Processing"),
                    ("warning", "Warning"),
                    ("invalid", "Invalid"),
                ],
                default="healthy",
                max_length=20,
            ),
        ),
    ]
