# Generated by Django 5.0.4 on 2025-09-04 15:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0057_add_performance_indexes'),
        ('intelio', '0013_alter_catalystmapping_level'),
        ('notes', '0024_snippet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['-timestamp', 'fleeting'], name='notes_note_timesta_099254_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['fleeting', 'timestamp'], name='notes_note_fleetin_0348d6_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['author', '-timestamp'], name='notes_note_author__74ced8_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['editor', '-edit_timestamp'], name='notes_note_editor__57190d_idx'),
        ),
    ]
