# Generated by Django 5.0.4 on 2025-09-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0025_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='content_offset',
            field=models.IntegerField(default=0),
        ),
    ]
