# Generated by Django 5.0.4 on 2025-09-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0026_note_content_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
