# Generated by Django 5.0.4 on 2025-10-27 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0027_alter_note_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivednote',
            name='publishable',
        ),
        migrations.RemoveField(
            model_name='note',
            name='publishable',
        ),
    ]
