# Generated by Django 6.0.2 on 2026-03-03 13:28

import core.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0061_alter_attachment_context_alter_attachment_file_and_more'),
        ('intelio', '0027_alter_basedigest_digest_type_and_more'),
        ('notes', '0028_remove_archivednote_publishable_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivednote',
            name='content',
            field=models.CharField(help_text='Archived note content.'),
        ),
        migrations.AlterField(
            model_name='archivednote',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='archivednote',
            name='timestamp',
            field=models.DateTimeField(help_text='When the note was archived.'),
        ),
        migrations.AlterField(
            model_name='note',
            name='access_vector',
            field=core.fields.BitStringField(2048, default=16158503035655503650357438344334975980222051334857742016065172713762327569433945446598600705761456731844358980460949009747059779575245460547544076193224141560315438683650498045875098875194826053398028819192033784138396109321309878080919047169238085235290822926018152521443787945770532904303776199561965192760957166694834171210342487393282284747428088017663161029038902829665513096354230157075129296432088558362971801859230928678799175576150822952201848806616643615613562842355410104862578550863465661734839271290328348967522998634176499319107762583194718667771801067716614802322659239302476074096777926805529798115328, help_text='Bitmask for access control; entities with matching bits can read.'),
        ),
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.ForeignKey(help_text='User who created the note.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.CharField(help_text='Markdown content with cradle links.'),
        ),
        migrations.AlterField(
            model_name='note',
            name='content_offset',
            field=models.IntegerField(default=0, help_text='Byte offset where content starts (after frontmatter).'),
        ),
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(default='', help_text='Note description from metadata or first paragraph.', max_length=4096),
        ),
        migrations.AlterField(
            model_name='note',
            name='digest',
            field=models.ForeignKey(help_text='Digest this note was imported from, if any.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='intelio.basedigest'),
        ),
        migrations.AlterField(
            model_name='note',
            name='edit_timestamp',
            field=models.DateTimeField(help_text='When the note was last edited.', null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='editor',
            field=models.ForeignKey(help_text='User who last edited the note.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='entries',
            field=models.ManyToManyField(help_text='Entries referenced by this note.', related_name='notes', to='entries.entry'),
        ),
        migrations.AlterField(
            model_name='note',
            name='fleeting',
            field=models.BooleanField(default=False, help_text='If true, note bypasses entity/entry validation (quick notes).'),
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the note.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='last_linked',
            field=models.DateTimeField(default=None, help_text='When relations were last computed from this note.', null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata from frontmatter.', null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('processing', 'Processing'), ('warning', 'Warning'), ('invalid', 'Invalid')], default='healthy', help_text='Processing status: healthy, processing, warning, or invalid.', max_length=20),
        ),
        migrations.AlterField(
            model_name='note',
            name='status_message',
            field=models.CharField(default='', help_text='Message describing status (e.g. validation error).'),
        ),
        migrations.AlterField(
            model_name='note',
            name='status_timestamp',
            field=models.DateTimeField(help_text='When the status was last updated.', null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='When the note was created.'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='', help_text='Note title from metadata or first heading.', max_length=255),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='content',
            field=models.TextField(help_text='Snippet content (markdown).'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, help_text='When the snippet was created.'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='default',
            field=models.BooleanField(default=False, help_text='Whether this is the default snippet for new notes.'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='name',
            field=models.CharField(help_text='Display name of the snippet.', max_length=255),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='owner',
            field=models.ForeignKey(help_text='Owner of the snippet; null for system snippets.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL),
        ),
    ]
